### ISSUE TITLE
Can't retrieve the domains and base URI using the information

### ISSUE THREAD

**Issue by mmehta-navomi** [LivePersonInc/developers-community#10]
Suggestion: Please include the example of request to get domain and baseURI. 
When we request for the domain to http://api.liveperson.net/api/account/accountId it doesn't respond. 

http://api.liveperson.net/api/account/{accountId}/service/{serviceName}/baseURI.json?version=1.0
Where can we find the serviceName?

**Comment by pmolensky** [comment]
Hi, all overview pages list the relevant service name:
![chrome_2017-06-30_20-24-18](https://user-images.githubusercontent.com/29775347/27749074-4950d86a-5dd2-11e7-902f-86436f770461.png)
_for example Engagement History_

Tip: you can also use the URL without the service name to get the full list:
https://api.liveperson.net/api/account/{accountId}/service/baseURI.json?version=1.0
