### ISSUE TITLE
Question: Sending page navigation using the Monitoring API

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#1011]
Hi,

one of our clients has implemented the [Monitoring API](https://developers.liveperson.com/monitoring-api-methods-engagement.html) -instead of using the javascript-tag- for monitoring visitors acros their website. When sending page navigation context using the engagement-method they experienced two issues. (I'm not sure if this is by design or we just overlook some property):
1. The Monitoring API is implemented on a website, so an url is still usefull data. The client sends the visited url using the entryPoints-property.
- In the agent workspace the url shows up as a section-keyword. Ideally, the behavior would be similar to webmessaging/-chat where the url would show up with a title and a clickable url. Is there a different property to correctly send the URL?
2. An invocation of the engagement-method updates the previous send visitor and session information.
- In the agent workspace the page navigation is updated and removing previous visited pages. Ideally, the behavior would be similar to webmessaging/-chat where the last entryPoint would show as 'current page' and older info as 'previous pages'. Is there a property for the visitor on a different page, opposed to overwrite the existing information?

Regards

**Comment by j9t** [comment]
Hi @pmolensky—thanks for the patience here. Can you confirm this is still an issue?

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
