### ISSUE TITLE
Chat Agent API: Accept a chat

### ISSUE THREAD

**Issue by mayukanki** [LivePersonInc/developers-community#102]
https://developers.liveperson.com/agent-accept-chat.html

Document says 'No body parameters should be posted.' but body parameters require {"chat": "start"}.

I received the error if I don't include  {"chat": "start"}.
{"error":{"time":"2017-12-11T22:18:59.205-05:00","message":"request body does not contain a valid JSON statement!","internalCode":5}}

**Comment by donmanguno** [comment]
Closing this issue. Documentation will be updated as necessary.
