### ISSUE TITLE
Messaging Interactions API

### ISSUE THREAD

**Issue by mayukanki** [LivePersonInc/developers-community#103]
When will all data be available? 
With Engagement History API, it's 2 hours. Is this the same for Messaging Interaction API?

**Comment by EdenKupe** [comment]
Hey @mayukanki 

Can you please clarify? Are you trying to find out how long before an interaction appears on the Messaging Interaction API?

**Comment by mayukanki** [comment]
Hi @EdenKupe, yes I'm looking for the statement like below for Messaging Interaction API.

Engagement History API
https://developers.liveperson.com/data-engagement-history-overview.html
------------------------------
Brands can now search, filter and keep copies of chat transcripts and related data, for example surveys, to later integrate and further analyze their data with third-party tools (DWH, CRM systems, etc.). **99.5 % of chat transcript data is available within 5 minutes. All other chat transcript data (including metadata like Engagement Attributes) is available for up to 2 hours after a chat has ended, and is stored for 13 months**. 
------------------------------

**Comment by EdenKupe** [comment]
From Lital:

The messaging interactions API expose data for the last 13 months. Authenticated engagement attributes data is available for display in near realtime. The ability to search on this data is  available only after two hours from the time the data is sent.

**Comment by donmanguno** [comment]
Hi @mayukanki, I'm closing this issue but if you need more clarification let me know and I can reopen it.
