### ISSUE TITLE
Retrieving engagementInfo.agentNote

### ISSUE THREAD

**Issue by kstrickland09** [LivePersonInc/developers-community#104]
Is there a way to retrieve the agentNote via API?

**Comment by donmanguno** [comment]
Hi @kstrickland09, I have reached out to the owners of the Chat Agent API for an answer on this.

**Comment by donmanguno** [comment]
Hi Kristin,

It is not currently possible to retrieve the AgentNote via API but our Product team is going to consider adding this ability to our roadmap and it may be available in the future.
