### ISSUE TITLE
Unable to resolve "util/EventsUtil" when using the Javascript SDK in React Native

### ISSUE THREAD

**Issue by gyfis** [LivePersonInc/developers-community#105]
I'm trying to use the LivePerson Javascript SDK provided as a minified .js file (`lpChat.min.js`) in a react native project. However, on require, the whole app crashes with the error of not being able to find `util/EventsUtil`. I'm not familiar with such package, is it a code I should download from somewhere else and include in the respective folder?

**Comment by dvillacis94** [comment]
Which SDK are you using? are you referring to the Javascript Chat SDK?

**Comment by gyfis** [comment]
@dvillacis94 Yes. After I posted the issue I read that the SDK should be used only on web, I've also seen the `window` references in the .js file, so we fell back to the Server Chat API. Closing this issue.
