### ISSUE TITLE
OpenID JWT Encryption

### ISSUE THREAD

**Issue by tburgess-nbs** [LivePersonInc/developers-community#1056]
Hello @lpbarber is there a code example for this?
https://github.com/LivePersonInc/developers-community/blob/c0c9de1431283be7443da3a4f7187842b68c77c7/pages/Documents/Security%26Authentication/ConsumerAuthentication/detailed-api.md#openid-jwt-encryption

**Comment by j9t** [comment]
(Feeling free to close; if you or @lpbarber like to follow up, okay to reopen.)
