### ISSUE TITLE
Available Slots - error in URL

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#106]
https://developers.liveperson.com/agent-retrieve-available-slots.html

It was "available-Slots" in the URL, but it should be "availableSlots" (i.e. there is no hyphen).

Will

**Comment by donmanguno** [comment]
Hi @lp-wodell. There is actually no hyphen in the document (which you can see if you copy-paste the URL): a CSS stylesheet included on this page is inserting it.  We'll get that fixed.
