### ISSUE TITLE
LivePerson Chat Callback

### ISSUE THREAD

**Issue by LPoehlmann** [LivePersonInc/developers-community#107]
My client is using chat, but needs to add padding around the button so that it doesn't run into a sticky footer they are using.SO they are doing it on the back end. The chat uses element styling for its positioning, so the developer can't use CSS to position it. Using his own JS to style chat has drawbacks in that he has to make sure his JS fires at the right time. Is there a callback that fires once chat has loaded and the icon is visible?

**Comment by donmanguno** [comment]
Yes, you can do this using the LE Tag's Events API: https://developers.liveperson.com/lp-tag-engagement.html
