### ISSUE TITLE
How to delete "・・・" and "Mark as Urgent" option

### ISSUE THREAD

**Issue by mayukanki** [LivePersonInc/developers-community#108]
I cannot find document that describe:
1. how to delete dots (three dots on right top corner)
2. how to delete 'mark as urgent' 
3. how to delete 'clear history' 
4. how to delete 'mark as resolved' 
![screen shot 2017-12-21 at 15 12 23](https://user-images.githubusercontent.com/34560443/34245213-426656c4-e66c-11e7-82bd-1b0bb60ab30f.png)

![screen shot 2017-12-21 at 15 12 31](https://user-images.githubusercontent.com/34560443/34245219-4a0ea728-e66c-11e7-97b2-0b6b9abc4150.png)

**Comment by EdenKupe** [comment]
Hey,

Please approach the mobile team directly with this. You can email Itay Sagiv, he's the Product Manager of this. In general, this issues section is for specific problems and questions on the documentation, not general questions :)
