### ISSUE TITLE
LPMessagingSDK - Fatal Exception - NSInvalidUnarchiveOperationException

### ISSUE THREAD

**Issue by fabioacri81** [LivePersonInc/developers-community#1088]
Hello,

I got a crash with the latest version of LPMessagingSDK (XCFramework) noticed on iOS 14.2 iPhone 8 device :

*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (LPInfra.QuickReplyItem) for key (root) because no class named "LPInfra.QuickReplyItem" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

Is this a known issue? if not anyone might be looking into this and confirm it's an SDK issue?
Thanks,
Best

**Comment by luandrecast-lp** [comment]
@fabioacri81 are you using the latest LPMessagingSDK version, 6.1?

**Comment by fabioacri81** [comment]
yes, 6.1.0 release, the one that says support for iOS 14, we are compiling in fact with Xcode 12.2.

**Comment by j9t** [comment]
Thanks for sharing this, @fabioacri81, as well as for the patience. Does the issue still persist?

@luandrecast-lp, any other thoughts on your end, would you be able to advise?

**Comment by fabioacri81** [comment]
Better something in years time than never in an entire life right? thanks for chasing. Honestly, my team codebase and dependencies are all upgraded now, so I wouldn't be able to confirm on that issue. We could mark it as sorted I believe. Thanks again @j9t

**Comment by j9t** [comment]
Thanks for following up, @fabioacri81, and also thanks for bearing with us!
