### ISSUE TITLE
SDK Size for iOS less than 4 MB

### ISSUE THREAD

**Issue by Majo-Paez** [LivePersonInc/developers-community#111]
A major bank in LATAM needs the SDK for iOS to be less than 4 mb and having The possibility to remove features from The SDK to be able to reduce the size even more.

**Comment by donmanguno** [comment]
Hi Majo,
This would need to be handled as an Enhancement Request as it's a request for a major overhaul of the SDK. This bank can use our Messaging API to build their own messaging integration, but be forewarned that this API's documentation is currently very limited.

https://developers.liveperson.com/agent-int-api-reference.html

**Comment by donmanguno** [comment]
Hi @Majo-Paez, I am going to close this issue now. If my response failed to address your inquiry let me know and we can re-open this issue.
