### ISSUE TITLE
[Server Chat API] Cannot add line while not in chat

### ISSUE THREAD

**Issue by gyfis** [LivePersonInc/developers-community#112]
Hi, I'm integrating the Server Chat API to our application and met an error while trying to use the "addLine/endChat" action.

The sequence of actions is this:
1. GET `Start Chat` action (successful) 
2. GET `Retrieve Chat Resources, Events and Information` with the `sessionUri` from 1. (successful)
3. POST `Add Lines / End Chat` with the eventsUri from 2. (fails on `400: Cannot add line while not in chat, internalCode: 5` error)

Any idea on what am I doing wrong?

EDIT: When trying to POST the Set Visitor Typing action, the returned error is `400: Cannot set visitor's typing status. Chat was ended`. This implies that the chat is ended right after it's started. Still no idea why that happens, though...

EDIT2: After I set a timeout for the step 3. POST, and _accepted_ the chat before the call was made, it went through. So it seems that unless the chat is accepted, you cannot post anything to it. Is there any way of overcoming this, so that the process is more streamlined and the "waiting for agent" is skipped?

**Comment by donmanguno** [comment]
HI @gyfis, you are correct that the visitor cannot send messages into the chat before the chat is accepted by an agent. This is the expected behavior of the system and it cannot be changed. If you want the visitor to be able to initiate the chat having already sent some message to their future agent I suggest you use the pre-chat survey mechanism.

**Comment by gyfis** [comment]
Thanks for the response @donmanguno ! Do you think polling and repeating the `Add Lines / End Chat` POST action until it passes is a valid strategy to overcome this system design decision?

**Comment by donmanguno** [comment]
@gyfis I suggest that instead you repeatedly poll the `Retrieve Chat Events` endpoint until you receive an event of `"@type": "state"` and `"state": "chatting"` like event 2 in the example on [this page](https://developers.liveperson.com/consumer-experience-server-chat-retrieve-chat-events.html)

**Comment by gyfis** [comment]
Thanks for the tips @donmanguno ! I think this can be closed :)
