### ISSUE TITLE
How to set up authentication server for the Auth Chat?

### ISSUE THREAD

**Issue by nullmicgo** [LivePersonInc/developers-community#1162]
i was trying to following this document to create a Auth Chat 
https://developers.liveperson.com/essential-resources-authentication.html

Could anyone help to provide a sample Authentication server for this setup?

![image](https://user-images.githubusercontent.com/1070485/104700981-f5096a80-574f-11eb-9b88-41b4e31c3db2.png)

thank you

**Comment by j9t** [comment]
Thanks for filing this, @nullmicgo, and for the patience…! Is this still an issue? We would aim to either update docs or provide a contact to help resolve this.

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
