### ISSUE TITLE
 chat button display issue

### ISSUE THREAD

**Issue by pltlg** [LivePersonInc/developers-community#117]
Often happends that the button loads a few seconds after the page loaded. There are cases where the chat button wont appear but we see the 3sec requests in the background. Do you have any idea what causes the issue?

**Comment by donmanguno** [comment]
Hi @pltlg, this question is best suited for our support department who can help you understand why the button isn't appearing on your page sometimes.  You can chat with them in the Connection Area in LiveEngage by clicking on the tab on the right side of the interface.
![image](https://user-images.githubusercontent.com/10452169/34733384-1fb2f668-f536-11e7-9538-eb6264c0a2be.png)
