### ISSUE TITLE
visitorId sid issue

### ISSUE THREAD

**Issue by pltlg** [LivePersonInc/developers-community#118]
Where can I get the "visitorId" (path parameter) and the "sid" (query parameter)?
I found the visitorId in the agent retrieve chat resources (https://developers.liveperson.com/agent-retrieve-chat-resources.html) request (chat->info->visitorId) and a sessionId in the start agent session (https://developers.liveperson.com/agent-start-agent-session.html) but it's not working. I got this message:
{"error":{"time":"2017-12-07T09:35:14.097-05:00","message":"null for uri: /api/account/13478843/monitoring/visitors/172890972197/visits/current/state?v=1&filter=agent&sid=1006403717","internalCode":28}}

**Comment by donmanguno** [comment]
Hi @pltlg, can you briefly describe what you're trying to accomplish and with which APIs?

Our requests that require a visitorId and sessionId are referring to the _Visitor's_ sessionId. The sessionId referred to in the Start Agent Session method is an Agent Session Id.

**Comment by hypernics** [comment]
Additional information to the original question:
I want to fetch data with [Visit information API](https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html).
Where can I get the "visitorId" (path parameter) and the "sid" (query parameter)?

**Comment by donmanguno** [comment]
In order for our service to issue a visitorId/sessionId and store the visit information you're seeking you need to create a visitor session on our service, either by using the LiveEngage tag or by using one of the related API's (such as the [App Engagement API](https://developers.liveperson.com/rt-interactions-app-engagement-overview.html))  Do you have the LiveEngage tag on your website?

**Comment by donmanguno** [comment]
Hi @hypernics and @pltlg, let me know if you still need help with this. Thanks.

**Comment by donmanguno** [comment]
Closing issue due to lack of response. If your problems persist this can be re-opened.
