### ISSUE TITLE
Login as app issue

### ISSUE THREAD

**Issue by pltlg** [LivePersonInc/developers-community#119]
I want to login as an application but there is no "User Type - Bot" option in API key editor page

**Comment by donmanguno** [comment]
Hi @pltlg.   First you need to ensure that your account has the necessary features to allow bot-type users (your account team or our sales department can help you with that). Once the necessary features are in place, you will create a bot-type user in the regular user creation screen, and generate your keys there as well.

![image](https://user-images.githubusercontent.com/10452169/34733146-59919ba6-f535-11e7-9dd0-71d4f8840e2f.png)

**Comment by donmanguno** [comment]
Hi @pltlg Since you haven't replied I'm going to close this issue now.
