### ISSUE TITLE
How to implement the Messaging Window API in an Android or iOS app?

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#121]
Is there a guide for how to implement [this API ](https://developers.liveperson.com/consumer-int-overview.html
)inside of an app? Any best practices? Any tips on linking with[ the push service](https://developers.liveperson.com/push-service-overview.html)?

**Comment by donmanguno** [comment]
No, we have no such guide nor best practice guidelines at this time. Also, as stated in [the push service documentation you linked](https://developers.liveperson.com/push-service-overview.html), "Note - the push service is available only for customers using the In-App Messaging SDK, for iOS or Android."
