### ISSUE TITLE
Live Person - Data Access API Details

### ISSUE THREAD

**Issue by ivysrini** [LivePersonInc/developers-community#122]
Hi,

Data Access API provides the data in the raw data format.
We need the following information to build our reports. Can someone please help/provide the details how we can extract the following information from the raw data (in JSON format) we get from Data Access API in a time frame
1.  How many Visitors visited the website 
2. How many Visitors are qualified for the engagements (engagement wise & also campaign wise)
3. Qualified Visitor behavior towards these campaigns/engagements like follows along with reasons
    a. How many Visitors responded to the chats device wise/campaign wise
    b. How many Visitors did not respond/decline to the chats device wise/campaign wise
    c. How many Visitors missed the chat due to the unavailability of agents
4. How many Visitors did not qualify for the engagements (engagement wise & also campaign wise)

Thanks,
Srini

**Comment by orenkatz** [comment]
@ivysrini You will need to talk to your account manager about working with Data Access data.
This forum is for technical questions related to our API / SDK code/implementation, if you have a question about using the API, we will be more than happy to help.
