### ISSUE TITLE
Messaging Interactions API - metadata.href links - required source url param missing - defect?

### ISSUE THREAD

**Issue by JonElliottGT** [LivePersonInc/developers-community#1225]
I am consuming the Messaging Interactions API and was adding the new required "source" URL Parameter as specified in the Live Person documentation. (This will be made required in March 2021).

This worked fine, but I noticed that the _metadata.href links that are given in the response from Live Person do **NOT** include the source parameter that I added to the URL in the initial call. They had all of the other parameters we gave in the initial URL though.

I checked the documentation for the response's metadata.href: "A specific link to be used in the next request."

However, if this metadata href link does not include the soon to be required source parameter it will fail when we use it for paginated requests. **This would be a bug and/or defect** and would require all of the consumers to manually add their source parameter again to the metadata href links in the response before using them. 

I believe this would also effect other APIs that will be using the required source parameter and require pagination (such as Engagement History API)?

Are the metadata.href links in the response going to be updated to include the required "source" URL parameter before it is made required? 

If not, I think the documentation should be updated because if we use the links as they are given then it will create errors and is confusing.

**Comment by j9t** [comment]
Hi @JonElliottGT—thanks for the patience here. Can you confirm this is still an issue?

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
