### ISSUE TITLE
"submitExitSurvey" method returns 400 error

### ISSUE THREAD

**Issue by Sharath-kancharla** [LivePersonInc/developers-community#123]
I am getting 400 error when I submit the survey. Here is the data I am sending:
{  
   "survey":{  
      "id":225279, (this is the id of the survey I'm getting)
      "question":[  
         {  
            "id":4509431, (id of the question )
            "answer":"10"
         },
         {  
            "id":4509433,
            "answer":"test!!"
         }
      ],
      "chatReferrer":"http://localhost:3000/" (this is getting added automatically)
   } 

The response I am getting is : 

internalCode: 5,
message: "Error in submitting survey:1: A hidden question was answered;2.   Question id: 4509431  Question: How likely are you to recommend live chat to a colleague or a friend?  Where 0 is Not at all Likely and 10 is Extremely Likely  Error: Value entered must be from the proposed options;"

**Comment by donmanguno** [comment]
Hi Sharath, please email me at mmanguno@liveperson.com with your account number.

**Comment by Sharath-kancharla** [comment]
Hi Mark,
 
My account number is 43953940. Login Name: yl-test.
 
Thanks,
Sharath
 
----- Original message -----From: Mark <notifications@github.com>To: LivePersonInc/developers-community <developers-community@noreply.github.com>Cc: Sharath-kancharla <Sharath.kancharla@ibm.com>, Author <author@noreply.github.com>Subject: Re: [LivePersonInc/developers-community] "submitExitSurvey" method returns 400 error (#123)Date: Tue, Jan 16, 2018 5:01 PM 
Hi Sharath, please email me at mmanguno@liveperson.com with your account number.

**Comment by donmanguno** [comment]
Hi @Sharath-kancharla I am still looking into this. Because you are using a Dynamic Survey it is a bit complicated, but I'll have some good information for you tomorrow.

**Comment by donmanguno** [comment]
Hi @Sharath-kancharla, I was able to determine what is going wrong.

I was able to submit the following without issue:
```javascript
chat.submitExitSurvey({
            survey: {
                "survey": {
                    "id": 225279,
                    "question": [
                        {
                            "id": 4509431,
                            "answer": "10 Extremely Likely"
                        },
                        {
                            "id": 4509442,
                            "answer": "test!!"
                        }
                    ]
                }
            },
            success: function () {console.log("exit survey submitted")},
            error: function (e) {console.error("exit survey submit failed: "+JSON.stringify(e))},
            context: chat
        })
```

First of all, you need to submit an answer that exactly matches one of the values in the survey you receive when you `getExitSurvey()`. Note that the value for the "10" answer is actually "10 Extremely Likely"

Also, the survey you are using is dynamic: which of the "why" questions the user should submit depends on which answer is chosen for the first question.  Note that the answer "10 Extremely Likely" is associated with logicId '47'
```
          "entry": [
            {
              "checked": false,
              "value": "10 Extremely Likely",
              "displayValue": "10 Extremely Likely",
              "logic": {
                "showLogicId": [
                  "47" // note that this answer refers to logicId 47
                ]
              }
            }, ...
```

You were submitting ID 4509433 for the second question, but the logicId of 4509433 is not 47, it's 16. As a result question 16 was "hidden" because it was not exposed by the answer to question 1.
```
{
          "type": "Text Field",
          "validationType": "alpha_numeric",
          "id": 4509433,
          "logicId": 16,
          "order": 2,
          "mandatory": false,
          "label": "We are so pleased that you feel this way about the chat service! Care to tell us why? ",
          "lastKnownValue": ""
        },
```

You need to ensure that the second answer submitted is the one that corresponds to the answer selected on question 1. The answer "10 Extremely Likely" exposed the question with logicId 47, which is question 4509442:
```
{
          "type": "Text Field",
          "validationType": "alpha_numeric",
          "id": 4509442,
          "logicId": 47,
          "order": 11,
          "mandatory": false,
          "label": "We are so pleased that you feel this way about the chat service! Care to tell us why? ",
          "lastKnownValue": ""
        }
```

**Comment by Sharath-kancharla** [comment]
hi Mark,
 
Thanks for getting back to me. Is it expected behavior where I don't receive any response after it gets posted successfully ?
 
 
 
----- Original message -----From: Mark <notifications@github.com>To: LivePersonInc/developers-community <developers-community@noreply.github.com>Cc: Sharath-kancharla <Sharath.kancharla@ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [LivePersonInc/developers-community] "submitExitSurvey" method returns 400 error (#123)Date: Fri, Jan 19, 2018 11:28 AM 
Hi @Sharath-kancharla, I was able to determine what is going wrong.
I was able to submit the following without issue:
chat.submitExitSurvey({            survey: {                "survey": {                    "id": 225279,                    "question": [                        {                            "id": 4509431,                            "answer": "10 Extremely Likely"                        },                        {                            "id": 4509442,                            "answer": "test!!"                        }                    ]                }            },            success: function () {console.log("exit survey submitted")},            error: function (e) {console.error("exit survey submit failed: "+JSON.stringify(e))},            context: chat        })
First of all, you need to submit an answer that exactly matches one of the values in the survey you receive when you getExitSurvey(). Note that the value for the "10" answer is actually "10 Extremely Likely"
Also, the survey you are using is dynamic: which of the "why" questions the user should submit depends on which answer is chosen for the first question. Note that the answer "10 Extremely Likely" is associated with logicId '47'
          "entry": [            {              "checked": false,              "value": "10 Extremely Likely",              "displayValue": "10 Extremely Likely",              "logic": {                "showLogicId": [                  "47" // note that this answer refers to logicId 47                ]              }            }, ...
You were submitting ID 4509433 for the second question, but the logicId of 4509433 is not 47, it's 16. As a result question 16 was "hidden" because it was not exposed by the answer to question 1.
{          "type": "Text Field",          "validationType": "alpha_numeric",          "id": 4509433,          "logicId": 16,          "order": 2,          "mandatory": false,          "label": "We are so pleased that you feel this way about the chat service! Care to tell us why? ",          "lastKnownValue": ""        },
You need to ensure that the second answer submitted is the one that corresponds to the answer selected on question 1. The answer "10 Extremely Likely" exposed the question with logicId 47, which is question 4509442:
{          "type": "Text Field",          "validationType": "alpha_numeric",          "id": 4509442,          "logicId": 47,          "order": 11,          "mandatory": false,          "label": "We are so pleased that you feel this way about the chat service! Care to tell us why? ",          "lastKnownValue": ""        }

**Comment by donmanguno** [comment]
Hi @Sharath-kancharla are you defining an `success` callback in your `submitExitSurvey`? The callback will fire when the survey is submitted successfully. It will not have any associated data, but the fact that it fires indicates that the survey was submitted successfully.
```
chat.submitExitSurvey(
	{...},
	success: function () {console.log("exit survey submitted")},
	error: function (e) {console.error("exit survey submit failed: "+JSON.stringify(e))},
	context: chat
})
```

**Comment by Sharath-kancharla** [comment]
Yes, I'm doing that but, was just curious if there is an associated data. I really appreciate your help. 
Thank you!
 
----- Original message -----From: Mark <notifications@github.com>To: LivePersonInc/developers-community <developers-community@noreply.github.com>Cc: Sharath-kancharla <Sharath.kancharla@ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [LivePersonInc/developers-community] "submitExitSurvey" method returns 400 error (#123)Date: Fri, Jan 19, 2018 1:06 PM 
Hi @Sharath-kancharla are you defining an success callback in your submitExitSurvey? The callback will fire when the survey is submitted successfully. It will not have any associated data, but the fact that it fires indicates that the survey was submitted successfully.
chat.submitExitSurvey({...},success: function () {console.log("exit survey submitted")},error: function (e) {console.error("exit survey submit failed: "+JSON.stringify(e))},context: chat})

**Comment by donmanguno** [comment]
Happy to help. I'm closing this issue now.
