### ISSUE TITLE
3.0.0:  Linking Error

### ISSUE THREAD

**Issue by rplankenhorn** [LivePersonInc/developers-community#124]
![screen shot 2018-01-16 at 2 11 43 pm](https://user-images.githubusercontent.com/228338/35010258-f2ea2ac4-fac7-11e7-9bae-b017af547619.jpg)

I am getting this build error when I try to pull in the latest version 3.0.0.17.1448 using Cocoapods.  If I had to guess, this is probably an issue with not including the simulator symbols in the SDK.

**Comment by dvillacis94** [comment]
Hi,

Are you still integrating a React-Native project?

I've tested version 3.0.0.17.1448, on React-Native 0.51.0 and everything is working as expected.

**Comment by rplankenhorn** [comment]
@dvillacis94 Yeah I am.  I was only seeing the issues when I actually called LPMessagingSDK.instance.showConversation and LPMessagingSDK.instance.reconnect.  If I comment out those calls, it builds fine.

**Comment by rplankenhorn** [comment]
I figured out this issue.  Since the LP frameworks are over 10MB in size, we are actually splitting them for storage in Git and then joining them at compile time.  I had forgotten to create new split files so it was joining the old files.  Closing this.
