### ISSUE TITLE
Error in the documentation (Authentication)

### ISSUE THREAD

**Issue by lp-adevakrupakar** [LivePersonInc/developers-community#126]
I think I found an error in the  documentation regarding the implicit flow and Code flow here, I was told to contact you. 

It is mentioned that implicit flow expects an Oauth 2 code and JWT token for Code flow. I think it should be the other way around under the topic principles. Link:https://developers.liveperson.com/guides-authentication-introduction.html#principles

**Comment by EdenKupe** [comment]
@lpbarber can you confirm?

**Comment by dvillacis94** [comment]
@lpbarber can you confirm Eden?

**Comment by lpbarber** [comment]
Correct.
It should be the other way around:
an OAuth 2.0 code (for Code Flow) or a JWT token (for Implicit Flow).
@dvillacis94 Thank you!

**Comment by dvillacis94** [comment]
We're making the change on the documentation, I'm closing this.
