### ISSUE TITLE
Data Access API - Downloading the files

### ISSUE THREAD

**Issue by ivysrini** [LivePersonInc/developers-community#129]
Hi,

We have got the access to the Data Access API and getting the web session files as below
        "file": [
            {
                "@name": "WebSession.1516784400000.1516788000000.part-00044-0.gz",
                "@scopeStartDate": "2018-01-24T04:00:00-05:00",
                "@scopeEndDate": "2018-01-24T05:00:00-05:00",
                "@href": "https://lo.da.liveperson.net/data_access_le/account/5003492/le/webSession/WebSession.1516784400000.1516788000000.part-00044-0.gz"
            }, 

But when we are trying to call the URL https://lo.da.liveperson.net/data_access_le/account/5003492/le/webSession/WebSession.1516784400000.1516788000000.part-00044-0.gz with same authorization keys & header as – Accept : application/octet-stream
getting the response as
<error>
    <time>2018-01-25T01:19:15.196-05:00</time>
    <message>Unauthorized request</message>
    <internalCode>10</internalCode>
</error>

with same authorization keys & header as – Accept : application/gzip
<error>
    <time>2018-01-25T01:24:39.728-05:00</time>
    <message>This request is not supported, verify request headers and method</message>
    <internalCode>5</internalCode>
</error>

Can you provide the way we can download these files. What should be the headers & authorization needed for this download etc.

**Comment by donmanguno** [comment]
Hi,

I am able to access the specific file in question using the Data Access API and using your key/secret/token/tokenSecret combination.  You can see my successful postman request below:
```
GET /data_access_le/account/5003492/le/webSession/WebSession.1516784400000.1516788000000.part-00044-0.gz HTTP/1.1
Host: lo.da.liveperson.net
Authorization: OAuth oauth_consumer_key="441.......bf8",oauth_token="f38.....88",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1516914504",oauth_nonce="eFWbg1",oauth_signature="ufGNrNDZziFWiXxUsTKBskN959I%3D"
Cache-Control: no-cache
Postman-Token: 66b39149-133a-6a6a-8365-2b8c8537d4be
```

**Comment by donmanguno** [comment]
Hi @ivysrini did this help?

**Comment by donmanguno** [comment]
I am closing this issue due to lack of response
