### ISSUE TITLE
Exposing underlining Messaging API from SDK

### ISSUE THREAD

**Issue by gyfis** [LivePersonInc/developers-community#130]
Hi, I was wondering if it would be possible to expose the API used by the iOS and Android SDK for Messaging. In that way, one wouldn't have to be restricted to use the SDKs on the specific platforms and could instead write their own solution or even new SDKs for different platforms (react native is the one I have in mind). 

Thanks for any info!

**Comment by donmanguno** [comment]
Currently the API has incredibly sparse documentation. More extensive documentation for leveraging the API directly is planned, but I can provide no ETA at this time.

**Comment by gyfis** [comment]
Hi @donmanguno , as far as I can see the documentation you provided is for the agent side of things. I'd be more interested in the client/visitor side of things, which is now done by the iOS Messaging SDK ( https://developers.liveperson.com/consumer-experience-ios-sdk-overview.html ). We don't want to replicate the liveperson agent dashboard, we (probably) want to create a new SDK for visitors using the same messaging API. Can we re-open this?
