### ISSUE TITLE
There is no EH API response example that shows the Survey Data structure

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#131]
The Survey Data is listed at the very bottom of this page in a template, but it's very general and not useful for developers that need to know what data is included and what the structure is. For example, is Survey ID included in the Survey objects? What about Survey Question ID?

https://developers.liveperson.com/data-engagement-history-methods.html

Can you also link to the Response data on the left hand side for quicker access to the json sample?

**Comment by donmanguno** [comment]
@EdenKupe Let's replace the example on this page with one that includes survey data.
@WildYorkies better formatting and navigation is coming soon.

**Comment by EdenKupe** [comment]
Let's not close this one yet so I can get that example replaced. @litalh can you please review with your team and add an example which includes survey data?

**Comment by donmanguno** [comment]
Hi @EdenKupe and @litalh any progress with this?

**Comment by EdenKupe** [comment]
I'll sync with Lital on this today.

**Comment by donmanguno** [comment]
Documentation updated
