### ISSUE TITLE
How to know the exit survey is disabled

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#1317]
Our client has the following question:

> When using the Server Chat API to retrieve [Chat Resources, Events and Information](../blob/master/pages/Documents/ClientSideConfiguration/ServerChatAPI/Methods/retrieve-chat-resources-events-and-information.md) the response gives a link to the Exit Survey. Even if the survey is disabled in the engagement. Is it somewhere else in the response we haven't seen?

How should the client check if the survey is enable/disabled?

**Comment by j9t** [comment]
Hi @pmolensky—thanks for the patience here. Can you confirm this is still an issue?

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
