### ISSUE TITLE
Chat session not found.

### ISSUE THREAD

**Issue by gyfis** [LivePersonInc/developers-community#132]
I'm using the Server Chat API. 

I start the chat, there is a conversation. After some time, the chat ends and I keep the reference (session url). But if I want to access the chat events again, I get a server response 404: "Chat session not found, internal code: 12". 

When asking about chat deleting previously, I got a response from the live person support that the chats are retained for 11 months. 

I can go to the dashboard and see the past chat. Is this a limitation of the server chat api?

**Comment by donmanguno** [comment]
@gyfis This is not a limitation, it is the expected behavior of this particular API: it interacts directly with the chat service, which is not where we store historical data. The LiveEngage UI uses the [Engagement History API](https://developers.liveperson.com/data-engagement-history-overview.html) to present past chats' information.

**Comment by gyfis** [comment]
@donmanguno Hi Mark. I see the API, thanks! I don't see a way of querying a chat based on its session ID - should I extract the "chatID" (the last part of the session URL) and use that as an engagement ID?

**Comment by donmanguno** [comment]
@gyfis Try using the `engagementId` body parameter in your Engagement History API request.  The value you should pass can be generated by concatenating your `accountId` and the `rtSessionId` you should have received in your [Server Chat API responses](https://developers.liveperson.com/consumer-experience-server-chat-retrieve-chat-information.html#response).

In other words, if your account is 72740529 and your rtSessionId was 4294967981, use the following payload:

```json
{engagementId: "727405294294967981"}
```
