### ISSUE TITLE
Android LiveEngage Enterprise In-App Messenger SDK  (v2.9 ) - Integration issue CompileSDKversion/BuildToolsVersion as "23""

### ISSUE THREAD

**Issue by KGandhimadinathan-BSFT** [LivePersonInc/developers-community#135]
Sample Application provided in SDK contains CompileSDKVersion/buildToolsVersion as "26". In document, as it mentioned to set minimum Version as 23. We tried to integrate with the latest library. Its not building with those configuration. We need to set compileSDKVersion as "25" to build successfully. Please let me know the way to integrate in version 23.

**Comment by KGandhimadinathan-BSFT** [comment]
Reference link for the document : https://developers.liveperson.com/android-quickstart.html#step-1-download-and-unzip-the-sdk

**Comment by shaymLP** [comment]
Hi @KGandhimadinathan-BSFT,
I wasn't able to replicate the issues you are having.. Can you please post a pic of the issues you are getting? 
You can use [this Gradle file](https://docs.google.com/document/d/1eU9MmR2ZyxkZmWkRk3Vz2xQ6KMk5im9VKUxPTa3sZ9U/edit?usp=sharing) for example of how to run LPSDK29 on Android SDK 23

**Comment by KGandhimadinathan-BSFT** [comment]
Hi @shaymLP,

After including the sample gradle. We are getting the below error.

 error: Error: String types not allowed (at 'lp_progress_bar_image' with value '').

**Comment by shaymLP** [comment]
@KGandhimadinathan-BSFT , what about your runnable module gradle? 
you can this one for [Reference](https://docs.google.com/document/d/19cceai-Rm1zScIbMcvb_V0CeT1L0R7rgdONgfk6esPI/edit?usp=sharing) . Which Android Studio version are you using? Which gradle plugin version are you using? Make sure to use the latest 
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.1.2'

**Comment by KGandhimadinathan-BSFT** [comment]
HI @shaymLP ,

Its working fine. After modifying Gradle to 3.0.1. Thanks for the support.
