### ISSUE TITLE
Access Engagement History for More than 13 Months

### ISSUE THREAD

**Issue by strin** [LivePersonInc/developers-community#136]
According to LivePerson account,

```
All other chat transcript data (including metadata like Engagement Attributes) is available for up to 2 hours after a chat has ended, and is stored for 13 months.
```

Does it mean the data is deleted after 13 months? Or the data is still persistent, just not available?

**Comment by EdenKupe** [comment]
Hey! 

After 13 months, the data is deleted from our servers. It's not locked away or non available, it gets removed.

**Comment by donmanguno** [comment]
I am closing this issue now
