### ISSUE TITLE
Android SDK: ClassNotFoundException in call to handlePushMessage

### ISSUE THREAD

**Issue by bramley-turner-stride** [LivePersonInc/developers-community#137]
I have raised this on the Android-Messaging-SDK issue page earlier (https://github.com/LP-Messaging/Android-Messaging-SDK/issues/44), but was advised it should be raised here instead

I get a ClassNotFoundException with
`Didn't find class "android.support.v7.app.NotificationCompat$Builder"`
After a call to LivePerson.handlePushMessage.

The v7 NotificationCompat was deprecated in r26 and removed from the support library in r27. I'm using 27.0.2 in my project. See release notes https://developer.android.com/topic/libraries/support-library/revisions.html#27-0-0

**Comment by dvillacis94** [comment]
Can you share the dependency you're using as you're probably no using `implementation 'com.android.support:appcompat-v7:26.1.0'` and the App Gradle so we can dig further into that.

**Comment by bramley-turner-stride** [comment]
I'm using 27.0.2

**Comment by dvillacis94** [comment]
I'm setting targetSdkVersion 27 and :

```Java
dependencies {
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
}
```

I'm able to display the notification correctly.

**Comment by bramley-turner-stride** [comment]
Not sure how that works for you, that's in your app gradle (not sdk gradle)? I use compile rather than implementation...

The problem is simple: the class the SDK is relying on (`android.support.v7.app.NotificationCompat`) was deprecated in r26 and removed entirely from the support library in r27. You can only have one version of the support lib in an app. Anyone wanting to use r27 in their app will have this problem when a notification is issued.

**Comment by shaymLP** [comment]
@bramley-turner-stride, which LP Android SDK version are you using?

**Comment by dvillacis94** [comment]
@bramley-turner-stride,

Even when using compile is working,

I teste it on an Oreo Device (Pixel 2):

**Comment by donmanguno** [comment]
Hi @bramley-turner-stride should we keep this issue open?

**Comment by bramley-turner-stride** [comment]
Yes, the issue still exists

**Comment by bramley-turner-stride** [comment]
I forked the repo and made a simple repro from the sample app:
https://github.com/bramley-turner-stride/Android-Messaging-SDK

To reproduce, run the sample app, open 3 dots menu -> test notify. App crashes with the ClassNotFoundException.


Diff:
https://github.com/bramley-turner-stride/Android-Messaging-SDK/commit/eb6aa79352358092795385bb3eef2ba561c17ad6

**Comment by dvillacis94** [comment]
Hi @bramley-turner-stride,

We have identified this as a bug, we're planing on fixing this on a future release, for now, you can build your our Notification that can handle for this:

```Java
// Check OS Version
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  Log.d("NotificationUI::", "Oreo");
  // Will Create new Notification Channel
  createNotificationChannel(ctx);
  // Build Notification
  builder = new NotificationCompat.Builder(ctx, NOTIFICATION_CHANNEL);
  // Set When to Show Notification
  builder.setWhen(System.currentTimeMillis());
} else {
  Log.d("NotificationUI::", "Not-Oreo");
  // Build Notification
  builder = new NotificationCompat.Builder(ctx);
  // Set Notification Priority
  builder.setPriority(Notification.PRIORITY_HIGH);
}
```
