### ISSUE TITLE
Android SDK: Roadmap to support newer Android versions (eg Notification Channels)

### ISSUE THREAD

**Issue by bramley-turner-stride** [LivePersonInc/developers-community#138]
I have raised this on the Android-Messaging-SDK issue page earlier (https://github.com/LP-Messaging/Android-Messaging-SDK/issues/49), but was advised it should be raised here instead.

The Play Store will require new/updated apps to target Android 8.0 API 26 from August/November 2018 respectively (see https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html )

We are currently unable to target 8.0, mostly due to the changes regarding Notification Channels. Apps that do not provide a Notification Channel (such as the LP SDK) will crash when targeting 8.0.

We are wondering if LP has plans to support notification channels before Google's deadline, and what the roadmap might be.

There are other issues with updating libraries, eg #135, https://github.com/LP-Messaging/Android-Messaging-SDK/issues/44 , and https://github.com/LP-Messaging/Android-Messaging-SDK/issues/37

**Comment by dvillacis94** [comment]
HI @bramley-turner-stride,

You can always set the LivePerson.handlePushMessage(this, remoteMessage.getData(),Account, false) show notification flag to false, and create your own Notification:
`
   // Check OS Version
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Log.d("NotificationUI::", "Oreo");
      // Will Create new Notification Channel
      createNotificationChannel(ctx);
      // Build Notification
      builder = new NotificationCompat.Builder(ctx, NOTIFICATION_CHANNEL);
      // Set When to Show Notification
      builder.setWhen(System.currentTimeMillis());
    } else {
      Log.d("NotificationUI::", "Not-Oreo");
      // Build Notification
      builder = new NotificationCompat.Builder(ctx);
      // Set Notification Priority
      builder.setPriority(Notification.PRIORITY_HIGH);
    }
`

That way you can create your Notification Channel and still handle lower version of Android, that don't support that.

**Comment by bramley-turner-stride** [comment]
Yes, I know I can do that, and draw the notifications myself. I wanted to know how and when you plan to add this in the future. For example, if you plan to define notification channels yourself within your library, or allow developers to create them ourselves and tell the library which one(s) to use (personally I'd prefer the latter, seems more flexible)

**Comment by shaymLP** [comment]
@bramley-turner-stride, Though we don't have an exact date, We do intent to support Android O and adding Notification Channel support to our SDK in the near future.

**Comment by shaymLP** [comment]
@bramley-turner-stride, As this was answered 5 days ago - This issue will be closed. Do not hesitate to open a new issue if you have any further questions.
