### ISSUE TITLE
not found object "csatResolutionFeedbackText" in LPConfig in latest LPMessaging SDK version "3.0.0.17"

### ISSUE THREAD

**Issue by tameshwari** [LivePersonInc/developers-community#141]
I have upgraded LPMessaging SDK to version "3.0.0.17".  I am facing this issue. 
Please help me out.

**Comment by dvillacis94** [comment]
Hi @tameshwari,

In 3.0.0.17, that attribute is not available on the LPConfig, as that is now a String Localization as shown in the [Documentation](https://developers.liveperson.com/consumer-experience-ios-sdk-localizationkeys.html)
