### ISSUE TITLE
Private YouTube video embedded in docs page

### ISSUE THREAD

**Issue by andrew-wharton** [LivePersonInc/developers-community#1421]
The video embedded in the page -> https://github.com/LivePersonInc/developers-community/blob/master/pages/Documents/ClientSideConfiguration/EngagementWindowWidgetSDK/overview.md is private and not able to be viewed.

![Screen Shot 2021-09-17 at 3 11 10 pm](https://user-images.githubusercontent.com/428298/133728179-77d44fa7-ed8a-49d0-b5f1-b8b87bd282f7.png)

The video referenced is https://www.youtube.com/embed/wV9ecP0n7d

![Screen Shot 2021-09-17 at 3 13 08 pm](https://user-images.githubusercontent.com/428298/133728174-2807aa9b-b1b3-466e-8767-33f5573654fa.png)

**Comment by j9t** [comment]
Thanks for reporting this and the patience! The video was commented in the meantime; we’re removing the reference if we can’t pinpoint an owner to share it.
