### ISSUE TITLE
Incorrect redirect_uri

### ISSUE THREAD

**Issue by AOprawko** [LivePersonInc/developers-community#144]
The redirect_uri sent by LP is not https://www.liveperson.com/ as described here https://developers.liveperson.com/guides-authentication-majorcomponents.html and here https://developers.liveperson.com/guides-authentication-detailedapi.html#openid-connect-provider-op-development-details but it actually is https://liveperson.net/

**Comment by donmanguno** [comment]
Hi @AOprawko.  We're checking this and will get back to you shortly.

**Comment by EdenKupe** [comment]
This has been corrected, apologies for the delay and thanks for reporting.
