### ISSUE TITLE
Retrieving ExternalId of a clicked button in a structure content

### ISSUE THREAD

**Issue by shaz1v** [LivePersonInc/developers-community#145]
Hi,
I'm trying to build a structured content that will have buttons on it.
My plan is that the buttons will send a message back to the Messaging SDK, displaying the button content in the chat, and using the ExternalId feature in the meta data of the button, providing a "payload" to the SDK containing Id to the next part of the conversation.

For example the button I created looks like this:
{
    "type": "button",
    "tooltip": "button tooltip",
    "title": "Opening Hours",
    "click": {
        "metadata": [{
            "type": "ExternalId",
            "id": "HOURS"
        }],
        "actions": [{
            "type": "publishText",
            "text": "Opening Hours"
        }]
    }
}

As I wrote at the beginning, displaying "Opening Hours" in the chat, and sending "HOURS" in the notification to the SDK.

My issue is that after sending the rich content, the message being sent to the SDK after clicking the button won't contain the meta data and will only contain the text itself:

"event": {
    "type": "ContentEvent",
    "message": "Opening Hours",
    "contentType": "text/plain"
}

How can I access the meta data of the button, knowing which button External Id was clicked?

Thanks!

**Comment by donmanguno** [comment]
Currently the structured content metadata is not provided to any of the participants in the conversation (including the bot agent). It is currently only available for use in reporting.
