### ISSUE TITLE
Agent Widget Limitations doesn't list cookie limitations

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#1477]
https://developers.liveperson.com/agent-workspace-widget-sdk-limitations.html

If a brand sets any cookies inside the iFrame, these are considered as 3rd party cookies from LP's PoV and are blocked as a result.

This information is missing.

**Comment by lp-tattwell** [comment]
To correct my last message, the docs should say "You can set 3rd party cookies but should add the `SameSite=None; Secure;` attributes to them"

**Comment by j9t** [comment]
@lp-tattwell, thanks for the report and the patience. Would you be open to filing a PR for this? This could help us while we’re reviewing and getting on top of the open issues. (Thanks!)

**Comment by lp-tattwell** [comment]
You are probably sick of hearing from me by now haha.

For the PR, are you suggesting I add the info myself and raise the PR? My problem with that is...I might be completely wrong. Can we get the product owner to validate and then they create the PR?

**Comment by j9t** [comment]
(Followed up internally.)

**Comment by j9t** [comment]
This was kindly handled by @oholzer in #1766. Thanks!
