### ISSUE TITLE
Android Issue -  Need Call Back Method

### ISSUE THREAD

**Issue by pramodalapati** [LivePersonInc/developers-community#148]
We have cordova app, we are using LP SDK for our Android app we are running into one issue on Android whereas on iOS it works fine. 

On Android when we put app in background with LP Chat window and then bring it to foreground 'resume' event is not fired.

However once we close the LP chat window 'resume' event gets fired. We need this event as we have some functionality around resuming app from background.

Please not this event gets fired on iOS and it works fine.

**Comment by donmanguno** [comment]
Are you using fragment mode or activity mode?

**Comment by pramodalapati** [comment]
We had integrated in hybrid app with LP SDP v2.9.3 for iOs and v2.9.2 for Android

**Comment by dvillacis94** [comment]
There are 2 ways to integrate LivePerson SDK:

- iOS: Window Mode (Default SDK View) & ViewController Mode (You create the ViewController),
- Android: Activity Mode (Default SDK Activity) & Fragment Mode ( You create the Fragment),

@donmanguno question was related to your implementation, as if you want to have control over the ViewController/Fragment LifeCycle Events, you will need to create your own.

**Comment by pramodalapati** [comment]
Thanks for the Reply

But in the Default SDK Activity mode, how do we know if the app has resumed when the chat window is open. May be it will help us to solve the problem.

**Comment by pramodalapati** [comment]
As per the LP documentation, the LP_ON_CONNECTION_CHANGED_INTENT_ACTION is used to get the isConnected parameter which is a Boolean value indicating:
true - connection established
false – disconnected

Upon debugging the app and running the chat it can be seen that the isConnected value is returned as false as the chat window is opened and eventually returns true once the connections are established. However the same behaviour is noticed if the app is brought from background to foreground too with the chat window opened, i.e. the value is returned as false soon after the app is brought to foreground and eventually returns true once the connections are established.

Thus it may not be feasible to differentiate out the ‘resume’ functionality with the mentioned option.

**Comment by dvillacis94** [comment]
Hi @pramodalapati,

As I mentioned before, `LP_ON_CONNECTION_CHANGED_INTENT_ACTION` is not the same as onResume,

We appreciate your suggestion, we'll escalate this request to R&D.

Right now, if you want to have control over the application lifecycle, you will need to implement your own fragment.
