### ISSUE TITLE
Visit Info API - Chat Only

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#15]
https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html - this API is chat only

**Comment by EdenKupe** [comment]
Hey,

While the Visit Info API relies on SDEs (which are mostly unsupported in Messaging right now), it still should work. You might not receive information and experience a lack of data but the API still pertains to both Chat and Messaging. Once SDEs are supported in Messaging, it'll be useful.

Thanks, hope that's clear.

**Comment by lp-wodell** [comment]
To call the Visit Info API, you need a Shark visitor id and a Shark session id. These do not relate to the messaging session. That's why, to me, this is chat-only. You cannot use the visitor info API to read authenticated SDEs passed in a messaging session, for example.

**Comment by lpbarber** [comment]
@lp-wodell In Web Messaging flow, the use of Shark is a part of the flow, although is not fully supported for all monitoring elements,  can be used if necessary.
Therefore, hypothetically, the use of both App Engagement API& Visit Information API is valid but not so valuable yet.
We will consider marking them as Chat only for reduce wrong usage and overhead.
Thank you for this highlighting.

**Comment by EdenKupe** [comment]
Closing this issue for now. @lp-wodell, we'll update you if we decide to change these documents to chat only. Thanks again for drawing our attention to this!
