### ISSUE TITLE
ios Push Notifications - Receving only After opening Chat Window

### ISSUE THREAD

**Issue by pramodalapati** [LivePersonInc/developers-community#150]
I am using a hybrid application with Live Person integrated into it.
In iOs we are receiving push notifications only after we opening the chat window, until user clicks on Chat window opened. Is there any call back mechanism to receive the notifications without opening the chat, Please suggest.

**Comment by dvillacis94** [comment]
Hi @pramodalapati,

LivePerson Push Notifications work this way:

- Register the Push to LPMessagingSDK.instance.registerPushNotification(),
- LivePerson sends the Push to APN, then is distributed to the device.

Usually the AppDelegate on iOS will handle the notification using the following event:

- `application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)`

-  Inside that event, LPMessagingSDK will display the Push:
`LPMessagingSDK.instance.handlePush(userInfo)`

That would change as Cordova has different events.

**Comment by pramodalapati** [comment]
Our implementation is done as per above guidelines only.

Once we logout from the app, we are logging out from Liveperson and as per their documentation it 'unregisters from the push notification service' as well. Upon logging back into the app, even if we are explicitly calling the Liveperson register_pusher method and getting a success for the same, notifications aren't received by the app. This is due to the fact that the 'performRegisterPusher' call is made by LP SDK only upon the first access of the chat post logout (during the time when 'Loading' text is displayed on chat window).

**Comment by orenkatz** [comment]
Thanks for the information @pramodalapati, we are checking the behavior and will update soon with our results.

**Comment by orenkatz** [comment]
We have checked it and it's an expected behavior.
I know that you are working with your account team on requesting it as a feature enhancement, closing this issue
