### ISSUE TITLE
Auth Code and Public key  -LP-Messaging/Android-Messaging-SDK

### ISSUE THREAD

**Issue by bhavyahmehta** [LivePersonInc/developers-community#151]
To run sample app from where I get Auth Code and Public Key?
I able to get Account ID after signing up LiveEngage developer account.

Regards

**Comment by donmanguno** [comment]
I do not understand your request. Which public key are you referring to? And when you say 'auth code' are you referring to the code used in code-flow authentication? If so, you need to generate this within your own authentication server. Authentication configuration is described in more detail [here](https://developers.liveperson.com/guides-authentication-introduction.html).

**Comment by bhavyahmehta** [comment]
Hello donmanguno,

I am trying to run SampleApp-Source/sample_app 
from https://github.com/LP-Messaging/Android-Messaging-SDK.

I want to develop sample app for inapp-messaging.
For that I create developer account using below link
http://register.liveperson.com/developer/signup
And get AccountID in my mail.

This account ID I used in sample application.
My question is From Where I get Auth Code and Public Key for running above sample application ?
Do Live Person provide Product / service for authentication..
From Where I get this Code / keys?
OR Do I have to implement my own authentication server to get AuthCode and Public Key?

![device-2018-02-21-130845](https://user-images.githubusercontent.com/756776/36468195-65ea54ca-1708-11e8-95ba-dcdf378e1c64.png)

Regards,
Bhavya

**Comment by donmanguno** [comment]
You do not need an authcode or public key to run the sample application. Those fields are there in case you want to test the features associated with them, but they are not required.

**Comment by bhavyahmehta** [comment]
Hello ,

Thank you for your response.
While running app got following error..
**ConnectionStateMachine_ConnectingState**: Connection task OPEN_SOCKET failed Open Socket - CLOSED

detailed log file attached.
[log.txt](https://github.com/LivePersonInc/developers-community/files/1744303/log.txt)

If possible kindly let me know appropriate solution.

Regards,
Bhavya

**Comment by dvillacis94** [comment]
@bhavyahmehta,

This could be because, your account is not enable for Messaging, to get messaging enabled on your account you can speak with your LivePerson Account Team, or if you don't have one, click [here](https://www.liveperson.com/?lp_offsite=%7B%22type%22%3A0%2C%22campaignId%22%3A333765313%2C%22engagementId%22%3A333765413%2C%22contextId%22%3A%22d062bca0-224a-4225-8d6d-cfcde5cdbe69%22%2C%22accountId%22%3A%2275555851%22%2C%22webView%22%3Afalse%7D) to chat with Sales who can provision your account for you.
