### ISSUE TITLE
Determine Incoming Chat Request: ringingCount is always "0"

### ISSUE THREAD

**Issue by ao** [LivePersonInc/developers-community#152]
If I login to the agent console I can see incoming requests (bottom left);
But if I use the `incomingRequests` endpoint (https://developers.liveperson.com/agent-determine-incoming.html), it always returns:
`{"incomingRequests":{"ringingCount":"0"}}`

**Comment by donmanguno** [comment]
HI @ao,

First, ensure that the agent you are using with the Agent API is in the appropriate skill to receive the chat.

Also, be aware that depending on your ACD configuration chats may be either presented to all qualified agents simultaneously, or be presented to each qualifying agent in turn one at a time, depending on your ACD configuration.
![image](https://user-images.githubusercontent.com/10452169/36446016-f18c54da-164d-11e8-9bce-043b03066d3a.png)

For more information about ACD please chat with LivePerson Support.
