### ISSUE TITLE
About setting 'lp_bubble_phone_links_regex' with Android SDK

### ISSUE THREAD

**Issue by jha-lp** [LivePersonInc/developers-community#153]
Hi.

I've been trying to set 'lp_bubble_phone_links_regex' in Branding.xml. they only want to make 157 after TEL: as a link. so I made regex as "(?<=TEL:)[0-9]+" and '<' this makes error in XML so replaced with '&lt;'.
but it doesn't work for 'TEL:157'. however I tried to set 'lp_bubble_phone_links_regex' with the same regex "(?&lt;=TEL:)[0-9]+" and it's working. is this a bug or not? if it not how can i set this pattern?

**Comment by donmanguno** [comment]
Hi @jha-lp,

There does seem to be a limitation with using lookbehinds in these regexes. We are consulting with the product team to determine whether this is a bug. Shoot me an email describing the use-case in more detail so that I can present it to product.

**Comment by donmanguno** [comment]
Thanks @jha-lp. This has been identified as a bug and will be fixed in a future release of the SDK.
