### ISSUE TITLE
Need info on control group

### ISSUE THREAD

**Issue by rajeswarr** [LivePersonInc/developers-community#158]
How do get the information for which customers pushchat was not triggered due to control group criteria from data access api?

**Comment by donmanguno** [comment]
HI @rajeswarr I believe this information will be returned in the [Web Session Data Access files](https://developers.liveperson.com/data-data-access-web-session.html) as the `siteControlGroup` parameter.  I am getting confirmation of this and will let you know as soon as possible.

**Comment by donmanguno** [comment]
Hi @rajeswarr, I can confirm that the `siteControlGroup` attribute reflects this information.
