### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by lp-adevakrupakar** [LivePersonInc/developers-community#159]
Last row of "new parameters" is missing. 
Scroll all the way to the bottom of the page to see error. 
Link: https://github.com/LP-Messaging/Android-Messaging-SDK

**Comment by EdenKupe** [comment]
Hey,

This has been fixed on the Developers' Community (where the bug originated) and will be fixed shortly on the LP-Messaging Repo.

Thanks for reporting!
