### ISSUE TITLE
App Engagement API - Chat Only

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#16]
https://developers.liveperson.com/rt-interactions-update-session.html

This API is chat only.

**Comment by EdenKupe** [comment]
See my answer on issue #15. If you rely on passing SDEs, it won't be supported but once they are, you could definitely create an app for Messaging using this API.

**Comment by lp-wodell** [comment]
Same response on this as to issue #15 - this API relates to Shark visitor/session ids and therefore I believe will make it irrelevant to messaging going forward, unless there are plans to merge the Shark and UMS systems when it comes to introducing SDEs into messaging.

**Comment by EdenKupe** [comment]
Close as per discussion on issue #15
