### ISSUE TITLE
Photo sharing permission bug

### ISSUE THREAD

**Issue by milkaman** [LivePersonInc/developers-community#160]
This bug was redirected from here: https://github.com/LP-Messaging/Android-Messaging-SDK/issues/53

We're integration LP into our app, and faced a bug while using Photo sharing feature.
If we press "Gallery" button and Permission dialog appeared, then we'll press "**Allow**" , `ConversationFragment.onRequestPermissionsResult() is called` with `grantResults`={0, -1}

```
public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        switch(requestCode) {
        case 1:
            LPMobileLog.d(TAG, "permission result = " + grantResults[0]);
            if(this.checkAllPermissionsGranted(grantResults)) {  //returns false because of {0, -1}
                this.startGallery();
                return;
            }
            break;
        case 2:
            ...
        }
...
```

As a result menu with "Gallery" and "Camera" collapsed and Gallery **won't be opened**.

This is happening because of targeting Android O and some changes about  READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE: https://developer.android.com/about/versions/oreo/android-8.0-changes.html#rmp

We use next parameters:
targetSdk              : 26,
compileSdk           : 26,
buildTools             : '26.0.1'

**Comment by dvillacis94** [comment]
Hi @milkaman,

We're looking into that one.

**Comment by dvillacis94** [comment]
Hi @milkaman,

After doing some testing on my fragment, even with the call is returning me a 0, i'm able to start the Camera Menu.

```
03-02 13:47:15.318 6187-6187/com.liveperson.samplesdk30 I/System.out: Permission :: android.permission.READ_EXTERNAL_STORAGE Result :: 0
03-02 13:47:15.318 6187-6187/com.liveperson.samplesdk30 I/System.out: Permission :: android.permission.WRITE_EXTERNAL_STORAGE Result :: 0
03-02 13:47:15.318 6187-6187/com.liveperson.samplesdk30 I/System.out: Permission :: android.permission.CAMERA Result :: 0
```

What are you trying to achieve with that call? as I'm seeing the method `this.startGallery`?

**Comment by dvillacis94** [comment]
Hi @milkaman,

It's been 3 days since we last heard from you, I'm closing this.
