### ISSUE TITLE
Data Access API - Enagagement Method

### ISSUE THREAD

**Issue by ivysrini** [LivePersonInc/developers-community#162]
Hi,

We are trying to read the transcripts of Enagagement in data Access API
But the transcript seems to be LP encrypted, Message.text even though Message.contentFormat is TEXT_PLAIN.
We do not find any where in the documentation how this transcript is encrypted and can be decrypted by the consumer. Please provide more insight into this so that we will proceed.

Regards,
Srini.

**Comment by donmanguno** [comment]
HI @ivysrini,

The encryption of data in Data Access API files is an optional feature that was enabled on your account at the request of someone from your organization. The public key used to encrypt the data was provided by you, and only someone possessing the associated private key can decrypt the data. I suggest that you speak to someone from your LivePerson Account Team who can help you identify when encryption was enabled on your account and at whose request, as only that person can provide the private key needed to decrypt the data.

**Comment by ivysrini** [comment]
Thank you for the suggestion. We will check with Live Person Account manager
