### ISSUE TITLE
CaseNumber 00628749  - Unauthorized error

### ISSUE THREAD

**Issue by sekhar-becu** [LivePersonInc/developers-community#164]
API using - https://{0}/messaging_history/api/account/{1}/conversations/consumer/search

{0} - is populated with the account number which is 50262409
{1} - populated with a conversation ID. 

When trying to retrieve a conversation we get an unauthorized error

**_Message: Error occurred when retrieving conversation by id 79978d7d-2ef5-42ec-a461-a029d584fdc2. Error is Exception : Response status code does not indicate success: 401 (Unauthorized).**_** 

This API started failing since 22 Feb 2018. This call was working on 21 Feb 2018

Please suggest. 

Case Number - 00628749 

Account Number - 50262409

**Comment by donmanguno** [comment]
- Are you able to make this API call successfully using Postman or another API testing tool?
- Does the call now fail 100% of the time for all conversations?
- What language is your application written in?
- Has anything changed about your application?

**Comment by sekhar-becu** [comment]
We havent tried it in POSTMAN. 
Yes it fails for every conversation
Language written - C#
No changes made to the application

**Comment by sekhar-becu** [comment]
I just tried it from POSTMAN as well. Its failing in there as well

**Comment by elie7747** [comment]
Hi Sekhar, this is Eliezer from the Support Team. Remember that we tested the APIs on one of your tools and we got many responses for them. The BaseURI API and the Message Interactions API as well. Can you tell us the name of the tool you used?

**Comment by sekhar-becu** [comment]
We didnt test it on any tool. we were reviewing the logs.

**Comment by orenkatz** [comment]
Closing this issue as it's being handled as a case
