### ISSUE TITLE
Can you use the Chat Agent API to listen to all conversations without sending responses?

### ISSUE THREAD

**Issue by johnsorrentino** [LivePersonInc/developers-community#165]
I'm looking for a real time feed of all messages (both agent and visitor lines) in all conversations. I was looking at the Chat Agent API, but I'm not interested in creating a bot to send responses. Is it possible to only listen to messages with the Chat Agent API or is there a more appropriate API available?

**Comment by WildYorkies** [comment]
@johnsorrentino You could also try this: https://developers.liveperson.com/agent-workspace-sdk-overview.html

Create a widget with a blank screen that just listens to each incoming chat message. This widget can be set to appear by default in every conversation.

Depending on your use case, though, there may be a much better solution than pulling in each message in real time.

**Comment by johnsorrentino** [comment]
@WildYorkies thanks!

I'd like to send tips/alerts to each agent based on the individual messages in the conversation so I'd like to receive each message with little delay.

**Comment by WildYorkies** [comment]
@johnsorrentino Oh, you could display the tips / alerts in the agent widget itself then. And you can have agent widgets appear for only some skills and not others if you want.
