### ISSUE TITLE
Is there a .NET equivalent for Messaging SDK?

### ISSUE THREAD

**Issue by timu** [LivePersonInc/developers-community#168]
I tried to find at least a .NET wrapper for Messaging SDK but couldn't find one. Can someone please direct me to it if there is any?

**Comment by dvillacis94** [comment]
Hi @timu, are you talking about the LPMessagingSDK ([Android](https://developers.liveperson.com/android-overview.html)/[iOS](https://developers.liveperson.com/consumer-experience-ios-sdk-overview.html)) or the [Messaging Agent SDK](https://developers.liveperson.com/messaging-agent-sdk-overview.html)?

**Comment by timu** [comment]
Hi @dvillacis94, I’m referring to Messaging Agent Sdk

**Comment by dvillacis94** [comment]
Hi @timu,

The Messaging Agent SDK is a wrapper of one of our [Agent Messaging API](https://developers.liveperson.com/agent-int-api-reference.html#), you can feel free to create your own wrapper for .NET
