### ISSUE TITLE
How to save conversation ?

### ISSUE THREAD

**Issue by bhavyahmehta** [LivePersonInc/developers-community#171]
How to get / save whole transcript in android mobile app?

**Comment by dvillacis94** [comment]
Hi @bhavyahmehta,

if you want to get all the archived and closed conversations, I would recommend you to check the [Consumer Messaging History API](https://developers.liveperson.com/consumer-experience-messaging-history-overview.html)

**Comment by bhavyahmehta** [comment]
I found in SDK whole conversation is saved in Database in encrypted format.. How I get that conversation ?

**Comment by WildYorkies** [comment]
@bhavyahmehta You can download conversations from within LiveEngage, but if you want to use an API, you can use https://developers.liveperson.com/data-messaging-interactions-overview.html . It accepts parameters like date timeframe, consumerID, or conversationID

**Comment by dvillacis94** [comment]
@bhavyahmehta,

The conversations stored on the Device can only be handle by the SDK as this are encrypted, if you want to fetch the conversations, you would need to use and API, as @WildYorkies mention.
