### ISSUE TITLE
Snackbar is not getting Displayed for Off Hours

### ISSUE THREAD

**Issue by abhishghosh** [LivePersonInc/developers-community#172]
Android SDK
When the Agent is Not Available and the client tries to send the message from the chat activity. According to documentation of LivePerson Snackbar will be shown but snackbar is not popping up

**Comment by dvillacis94** [comment]
Are you talking about the Response Time or the Shift Status?

**Comment by abhishghosh** [comment]
![device-2018-03-06-225814](https://user-images.githubusercontent.com/3381362/37047752-efc5f81e-2191-11e8-8919-14ee9f7fd86f.png)
<img width="1261" alt="screen shot 2018-03-06 at 10 57 37 pm" src="https://user-images.githubusercontent.com/3381362/37047753-eff0c7b0-2191-11e8-9bf8-25256dcf5d8c.png">

I have Attached the screen shot of the Live Person Agent dashboard ( Away state)

Android Live Person Chat Activity Screen Shot: Where client is trying to chat with offline Agent

**Comment by dvillacis94** [comment]
@abhishghosh,

The LivePerson SDK works in an Asynchronous way to interact with the Client, this way the client can always start a Conversation anytime.

**Comment by abhishghosh** [comment]
But as per doc we can show Some messages in the SnackBar of the chat activity. I am trying to configure that. But it is not happening

lp_ttr_message_off_hours_message

**Comment by dvillacis94** [comment]
@abhishghosh,

I would recommend that you check this with your Account Manager or CSM, as this is not only an SDK configuration, as there are some configurations needed on the Account too.

**Comment by orenkatz** [comment]
Hey @abhishghosh ,
Are you referring to the message that appears when you send a message and the account is on off-hours? something like "Thank you for your message, We will be back online tomorrow at 9:00 AM".

If so, on what device have you tried to check it? did it ever work?
