### ISSUE TITLE
Chat Agent Api add line with structured content return text format not support

### ISSUE THREAD

**Issue by mkwong04** [LivePersonInc/developers-community#173]
I try to use the structured content type in add line API in Chat Agent API, but received a 400 bad request 

### Sample Request
POST /api/account/**xxxxxx**/agentSession/**yyyyyyy**/chat/**zzzzzzzzzzzzz**/events?v=1&NC=true

``
{
   "event": {
          "@type":"line",
           "textType":"rich-content",
           "json": {
                 "type":"horizontal",
                 "elements":[
                   {
                        "type":"text",
                        "text":"Do you need "
                  },
                 {
                         "type":"text",
                         "text":"coffee?"
                 }
                 ]
            }
      }
}
``

### Response
``
{"error":{"time":"2018-03-08T04:19:58.923-05:00","message":"Text format is not supported.","internalCode":5}}
``

What could be the issue? Is there any sample payload for using rich-content textType in Chat Agent API add Line method?

**Comment by timu** [comment]
hi @mkwong04 I'm also getting 403 Forbidden when trying to send a rich content with the below request

### Request
`{"event":{"@type":"line","text":"Hi there, your session id is 4294967678. How can I help you?","textType":"rich-content","json":{"elements":[{"type":"button","tooltip":"","title":"I can help you with refunds","click":{"actions":[{"type":"publishText","text":"I need a refund"}]}},{"type":"button","tooltip":"","title":"I can help you finding price of a product","click":{"actions":[{"type":"publishText","text":"I need the price of a product"}]}},{"type":"button","tooltip":"","title":"I can help you finding stock information ","click":{"actions":[{"type":"publishText","text":"Can you give me the stock information of a product?"}]}}],"type":"vertical"}}}`

### Response
`{"error":{"time":"2018-03-08T12:03:29.408-05:00","message":"Rich content is not provisioned for this account.","internalCode":29}}`

**Comment by mkwong04** [comment]
Hi @timu 

403 error is something related to access rights of your account to the invoked API. Your case should be different issue from my case, your account manager may need to grant some rights for your account to use the feature?

**Comment by donmanguno** [comment]
@timu @mkwong04 is on the right track: your error stems from not having the relevant feature enabled on your account.  Your Account Manager can help with that.

**Comment by dvillacis94** [comment]
Hi @mkwong04,

Are you still having this issue?

When sending Structure Content, the Request Headers should look similar to this:

```
    // Define Request Options
    const options = {
      method  : 'POST',
      url     : url,
      headers : {
        'Authorization'    : bearer,
        'content-type'     : 'application/json',
        'X-Requested-With' : 'XMLHttpRequest'
      },
      json    : true,
      body    : {
        "event" : {
          "@type"    : "line",
          "textType" : "rich-content",
          "json"     : content
        }
      }
    }; 
```

you can try to replace the content variable with the following:
```
{
  "type"    : "text",
  "text"    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis egestas dignissim arcu, quis facilisis augue pharetra quis. Phasellus convallis ullamcorper felis in ultrices. Morbi pharetra at urna ut laoreet. Ut mauris ipsum, imperdiet eu quam at, dignissim malesuada tellus. Mauris in eros tincidunt, ullamcorper enim quis, cursus elit. Nam eu dui sed nisi laoreet aliquam. Sed eget lorem ut neque dapibus placerat. Donec sapien leo, volutpat a quam eget, cursus tincidunt dolor. Sed suscipit, mauris at tincidunt luctus, neque leo mattis est, sed ornare elit felis et libero. Vestibulum blandit luctus quam. Integer et enim eleifend, semper justo vel, feugiat quam. Nullam eu ultrices lectus. Curabitur nibh dui, mattis vel purus sed, viverra interdum ante. Maecenas pellentesque dapibus dui, ac vulputate velit.",
  "tooltip" : "text tooltip"
}
```

If you try to use an image, that image domain needs to be whitelisted or you'll get an error.

**Comment by shaymLP** [comment]
@mkwong04, As it seems like your question has been answered, this issue will be closed now. If you have any further questions please refer to our new look [Support Forum](https://support.liveperson.com/forum/).
