### ISSUE TITLE
Difference between Messaging Interactions API and Consumer Messaging History API?

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#174]
![image](https://user-images.githubusercontent.com/1299322/37154911-422486b6-2296-11e8-8be5-bd9fa0afef40.png)

Consumer Messaging History only allows GET and only one conversation at a time?

Messaging Interactions only allows POST and allows bulk download? 

Messaging Interactions is the only API you need, right?

**Comment by donmanguno** [comment]
Hi @WildYorkies 

There are differences driven by the use-cases each was designed for.

The Messaging Interactions API authenticates requests using oAuth, meaning the requestor needs access to the associated oAuth secrets. It was designed for brands to use to retrieve conversation data for their own processing.

The Consumer Messaging History API was designed for use on the consumer side (in app, messaging window api implementation, etc). Thus, it authenticates using a jwt token tied to a specific consumer, as opposed to using oAuth which would require hard-coding keys and secrets on the consumer side. This grants the consumer access only to those conversations relevant to themselves. Also, the service is designed to be able to handle the scale of consumer-side use, which could be orders of magnitude greater than brand-scale use of the Messaging Interactions API.

**Comment by WildYorkies** [comment]
@donmanguno thanks. But in the Consumer Messaging History, doesn't it require information that the consumer wouldn't have a way of knowing? Things like ConsumerID and Domain?

**Comment by donmanguno** [comment]
Indeed, this is not designed to be directly implemented _by_ the user, simply at the user scale. You might, for example, use the Messaging Window API to create a custom messaging interface, and provide within that interface the ability for the consumer to view and search their own conversation history. Your application would use this API.
