### ISSUE TITLE
LivePerson IN-APP MESSAGING SDK 3.1 Integration with Xamarin Platform

### ISSUE THREAD

**Issue by pphamzc** [LivePersonInc/developers-community#175]
Hi all,

We are trying to integrate the In-App Messaging SDK with Xamarin Platform.  We can not even compile the sdk.  We have ran into below error.  We have asked LP for help and they referred us to here.  Any insight into this would be most appreciated.
![lp-xam-error](https://user-images.githubusercontent.com/10777415/37285733-2804eb02-25bd-11e8-973d-d9fd70ff6f62.png)

**Comment by dvillacis94** [comment]
Hi @pphamzc,

We're not currently supporting the Xamarin Platform, that can probably change in the future, but we're currently using only Native Platforms.
