### ISSUE TITLE
Response from API call and the actual site call differs

### ISSUE THREAD

**Issue by ssamaga3** [LivePersonInc/developers-community#179]
Hi Team,

When we try running the Agent Metrics API with required details, the response received is always 0.
Example:

API Call : https://va.msghist.liveperson.net/messaging_history/api/account/28084016/agent-view/summary
API response :
{
  "accountID": "28084016",
  "summaryResults": {
    "openAssignedConversations": 0,
    "numAwayAgents": 0,
    "numBackSoonAgents": 0,
    "numOnlineAgents": 0
  }
}

When we login to the site https://sso3-prod.te.com/adfs//IdpInitiatedSignon.aspx?LoginToRP=LiveEngage 
and check the result we can see 3 online agents , 4 Away agents ...

![image](https://user-images.githubusercontent.com/35951704/37587054-26e8705a-2b84-11e8-8d6d-200433064c50.png)

We are using oAuth 1.0. If you need more information please let us know.
We expect the API response to match the results of the site.

Thanks, 
Swathi

**Comment by donmanguno** [comment]
Hi @ssamaga3,

The [Agent Metrics API](https://developers.liveperson.com/data-messaging-agent-metrics-overview.html) is only for Messaging accounts. I see that this is not clear enough from the documentation; we'll update it.

For Chat accounts, the data in your screenshot is retrieved using the [Chat Agent API's Retrieve Available Agents](https://developers.liveperson.com/agent-retrieve-available-agents.html) method.

**Comment by ssamaga3** [comment]
Thanks @donmanguno for pointing this out.
We will get back to you in case of more queries.

Thanks,
Swathi
