### ISSUE TITLE
Server Chat API question from client

### ISSUE THREAD

**Issue by ksatoLP** [LivePersonInc/developers-community#182]
Hi team,

This is Kohki, I am PSG support engineer in Tokyo.

We got question from our customer that they want to know details about Server Chat API response value.

They are using Server Chat API to check the chat status and got the value below and got the response as below.

2018-03-19 16:04:28,764 - DEBUG - : [chat_bot.py#main:103] 
events: [{'@id': '14', '@type': 'line-status', 'time': '2018-03-19T03:04:27.186-04:00', 'metadata': [], 'source': 'visitor', 'lineStatus': 'ACCEPT', 'refSequenceId': '11'}] 

They want to know what "'@type': 'line-status'" means and what 'lineStatus': 'ACCEPT' means., of course we looked at the developer community article but we can'find the answer there.

https://developers.liveperson.com/consumer-experience-server-chat-retrieve-chat-events.html

Would you be able to help with that ?

(I created same ticket before by personal account mistakenly so I created it again.)

**Comment by EdenKupe** [comment]
Thanks Kohki.

Guys, let me know if you need me to investigate with R&D.

**Comment by ksatoLP** [comment]
Hello guys, 
Did you have any update on our question ?
It would be appreciated if you could check this as we kept customer wating.

**Comment by EdenKupe** [comment]
@donmanguno can we take a look at this please?

**Comment by kohki1234** [comment]
Hi guys,

Would you be able to check the answer to my question please ?
It has been 1 week since I posted the question on behalf of the customer.

**Comment by ksatoLP** [comment]
Did you have any update guys ?
Sorry I logged in with wrong account so I deleted the previous comment before.

**Comment by EdenKupe** [comment]
I'm checking with R&D since DevSupport don't know the answer. I'll keep you updated.

**Comment by manzalyshay** [comment]
@EdenKupe @ksatoLP , I'm looking into it.

**Comment by shaymLP** [comment]
@EdenKupe @ksatoLP, i'm looking into it guys

**Comment by shaymLP** [comment]
@ksatoLP , We are waiting for an answer from the developers of this API. @orenkatz @EdenKupe

**Comment by orenkatz** [comment]
Closing this issue as it's being handled as a case outside Github
