### ISSUE TITLE
Disable logs for iOS

### ISSUE THREAD

**Issue by asalom** [LivePersonInc/developers-community#183]
Is there a way to disable the logs that the iOS SDK is posting in the console? There are lots of them and can potentially hide our own logs

**Comment by shaymLP** [comment]
Hi @asalom,
You can change the the LogLevel you subscribed to with Liveperson in a simple configuration step, you can use [this](https://drive.google.com/file/d/1SllKhRHWRV159ZS-w5qjeKj1mWWAYO43/view?usp=sharing) pic as a reference. Info is the lowest level of log provided.

**Comment by shaymLP** [comment]
@asalom, As it seems like your question has been answered, this issue will be closed now. If you have any further questions please refer to our new look [Support Forum](https://support.liveperson.com/forum/).
