### ISSUE TITLE
Common between Engagement API and Websession API

### ISSUE THREAD

**Issue by ivysrini** [LivePersonInc/developers-community#186]
Hi,

We are trying generate a report to get the transcripts for the visitors as follows
1. Getting the web session details from Web session API whom we have the impressions.
2. Getting the Enagagement Details by Engagement API
3. Correlating these two APIs using the visitID to get the transcripts for that visitor.

Problem we are facing here is, We are not really getting the transcripts.

Is our approach correct? Can you suggest the right approach to get the transcripts for the visitors whom we have taken from Web Session API?

Regards,
Srini.

**Comment by dvillacis94** [comment]
Hi @ivysrini,

Is this related to Messaging or Chat?

**Comment by ivysrini** [comment]
This is related to chat

**Comment by orenkatz** [comment]
Hey @ivysrini ,
What API are you referring when you mention Web session API?
Also, did you try using the Engagement History API to extract engagements with their transcripts?
https://developers.liveperson.com/data-engagement-history-methods.html

Oren

**Comment by shaymLP** [comment]
@ivysrini, As it looks like your question has been answered - this issue will be closed soon. If you have any further questions regarding this or any other issue please do not hesitate to open a new post.
