### ISSUE TITLE
Broken link - https://developers.liveperson.com/android-push-notifications.html

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#19]
Get your app’s AppKey from Google GCM or Google FCM and set it in the LiveEngage backend, as explained **here**, to identify your app by LiveEngage

The link on "here" is broken

**Comment by EdenKupe** [comment]
Thanks, this is fixed. The documents were consolidated so there's no need for a link, the instructions are in the same document below.
