### ISSUE TITLE
Agent Workspace Widget SDK: method "get" of the API returns incorrect data

### ISSUE THREAD

**Issue by dualbr** [LivePersonInc/developers-community#194]
Hello, 

We created widget using by API: [Agent Workspace Widget SDK]( https://developers.liveperson.com/agent-workspace-sdk-overview.html).

I found strange behavior of the method "**get**" of the API for Public Model Structure "**chatTranscript.lines**".

Steps to reproduce:
1. Login to LiveEngage (https://authentication.liveperson.net) as an Agent -> Set online status for the account;
2. Create the first chat conversation with several messages exchanged: 
![first chat](https://user-images.githubusercontent.com/22812746/38015425-63e668b2-3274-11e8-8563-0a4cc7612dfe.png)
If you can see **lpTag.agentSDK.get("chatTranscript.lines", onSuccess, onError);** returns all messages of the first chat: from system, agent and visitor;
3. End the first chat;
4. Agent don't fill survey questions for the first chat;

5. Create the second resuming chat conversation with several messages exchanged;
6. End the second chat;
7. Agent don't fill survey questions for the second chat;

8. Create the third resuming  chat conversation with several messages exchanged: 
![third chat](https://user-images.githubusercontent.com/22812746/38015568-d83e522e-3274-11e8-95e1-d072be35876d.png)
In this case **lpTag.agentSDK.get("chatTranscript.lines", onSuccess, onError);** returns only 2 messages of the third chat: from agent and visitor, but the third chat contains 4 messages;
9. End the third chat;
10. Agent don't fill survey questions for the third chat;

11. Create the 4th resuming  chat conversation with several messages exchanged:  
![4th chat](https://user-images.githubusercontent.com/22812746/38015786-8a2d195c-3275-11e8-855f-58992235c370.png)
For this chat **lpTag.agentSDK.get("chatTranscript.lines", onSuccess, onError);** returns 7 messages, but the 4th chat contains only 4 messages. Returned array contains messages from third chat and 4th chat;

Can you check this issue, because API provide different approaches for get **chatTranscript.lines** inside of the custom agent widget.

**Comment by orenkatz** [comment]
Hey @dualbr,
We've checked this scenario and we are seeing the same behavior as you are seeing.
We will consult with our R&D team and will provide you with a feedback on possible solutions.
Meanwhile, if you are looking to track events specifically for the current chat, I suggest to check the timestamp of the line and compare it to the chat start time, that way you will be sure it's part of the current chat

**Comment by orenkatz** [comment]
I understand that there is a support ticket opened for this issue (#00645684), Support will continue working on this case via the ticket.
Closing this issue.
