### ISSUE TITLE
Including user data and referral url in reports

### ISSUE THREAD

**Issue by rsmohammed** [LivePersonInc/developers-community#195]
Hi... we are using the Javascript Chat SDK for our chat UI with live engage agents. We want to be able to include user data in the reports that we pull from Liveperson. We see the data showing in the agent ui, but it doesn't get saved for the reports. What else do we need to get this data to save in the reports?
<img width="346" alt="screen shot 2018-03-28 at 2 47 45 pm" src="https://user-images.githubusercontent.com/37849938/38050319-8f5ab75e-3298-11e8-9681-fa911d0db760.png">

Also, we are trying to pass the referral url using "referrer" property in the requestChat method. It doesn't seem to be working. We don't see it appear in the agent UI.

**Comment by WildYorkies** [comment]
If you want to download all chat transcripts (with meta data), I suggest starting with the Engagement History API. Here is an example of the typical response you can get from that:

https://developers.liveperson.com/data-engagement-history-methods.html#response
![image](https://user-images.githubusercontent.com/1299322/38090342-1dfade20-3317-11e8-8728-23ab7b52f709.png)


Browser detail and other things are included. I'm not sure about Referrer, but perhaps `chatStartURL` would be helpful?

![image](https://user-images.githubusercontent.com/1299322/38090433-6a6379f2-3317-11e8-9f8f-3093ff355673.png)

In any case, I'd say start here.

**Comment by rsmohammed** [comment]
Thanks for the response. We are also using the Engagement history API already and no data shows for visitorInfo for the chats that are coming through our sdk chat. Even though we see in the agent UI as shown above. Also when a report is exported in csv format, those columns are empty.

The chatStartUrl also has no data, and we don't see it appearing in the agent UI. We don't know how to pass it correctly for it to appear in the agent UI and reporting.

When using the original LiveEngage javascript interface, we see this data coming in correctly into the UI and reports. But we are unable to see the same data in the reports when using the Javascript Chat SDK for a custom front end.

**Comment by rsmohammed** [comment]
Any ideas on why this data would not be showing in the reports? Would love to get this fix so we can have accurate reports. Perhaps there is some sample code for the chat sdk that we can review that logs this information correctly.

**Comment by rsmohammed** [comment]
We are using the unmonitored flow

**Comment by rsmohammed** [comment]
We have changed to monitored flow in our dev environment and are still getting the same problem.

**Comment by donmanguno** [comment]
Hi @rsmohammed,

Please confirm that you have the following configuration for monitored flow:

- You have a regular engagement created in the LE Engagement Studio which appears for visitors on your page.
- The engagement is associated with an API-based engagement window, which has a JS Method Name and optional JS Context specified.  In this example your method may be called `myMethodName`.
- On your page you have a global js method called `myMethodName`. It will be called with a `data` object as argument, which contains your `visitorId`, `sessionId`, and `contextId`.
- Now that you have this data you trigger a `requestChat` with the `visitorId`, `sessionId`, and `contextId` received above (as well as any of the other optional parameters).
- This chat will now be tied to the visitor's browsing session, and all of the data that our monitoring system collected about the visitor's browser before presenting the chat button.

**Comment by rsmohammed** [comment]
We have a developer now working with the LE dev team and I believe a ticket has been raised for this problem. So I think we can close this one and continue to work with the LE dev team on a fix.

**Comment by orenkatz** [comment]
OK, we will close this issue for now
