### ISSUE TITLE
MMS Viewer says to alter NODE_APP_DOMAIN in app.js, but this variable does not exist in app.js

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#196]
step 8 here https://developers.liveperson.com/products-channels-mms-deployment.html

**Comment by orenkatz** [comment]
@EdenKupe can you please check?

**Comment by EdenKupe** [comment]
Looking into it.

**Comment by cjames1224** [comment]
Hey @EdenKupe this is just a typo. Can you please update step 8 in the docs to read as follows: 
8. Update the NODE_APP_DOMAIN in the twilio function from step 4, to match the location where you've hosted your app.

**Comment by EdenKupe** [comment]
Update is building now, thank you both!
