### ISSUE TITLE
iOS LPMessagingSDK needs to be updated for Swift 4.1

### ISSUE THREAD

**Issue by jlgaustin** [LivePersonInc/developers-community#197]
Running LPMessagingSDK 3.1.0.21.1594

Getting this error after installing latest Xcode 9.3

Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1: /Users/user1/projects/myproj/MyProj/Pods/LPMessagingSDK/LPMessagingSDK/LPMessagingSDK.framework/Modules/LPMessagingSDK.swiftmodule/x86_64.swiftmodule

Can someone please compile with latest version?

**Comment by shaymLP** [comment]
Dear @jlgaustin, the development team will release a new XCODE compatible (3.1.1) version in the next following days. This will be released at our [IOS SDK Github Space](https://github.com/LP-Messaging/iOS-Messaging-SDK).  If you have any further questions please use our new [Support Forum ](https://support.liveperson.com/forum/).
