### ISSUE TITLE
Ended meaning?

### ISSUE THREAD

**Issue by chadwtkns** [LivePersonInc/developers-community#199]
In the [https://developers.liveperson.com/data-engagement-history-methods.html](examples) There is no documentation on what the "ended" property does. What does this do vs what would happen if it was omitted? Also in the same documentation when you say "start(to, from)" is that referring to the start of a chat window?

**Comment by donmanguno** [comment]
Hi @chadwtkns. 

`ended` is a deprecated parameter and we need to remove it from the examples.
`start(to, from)` refers to the time window you want to search. Your search will return conversations that started between the epoch timestamps you provide for `to` and `from`.

**Comment by chadwtkns** [comment]
How can I do a search with engagements that have ended?

**Comment by donmanguno** [comment]
By default the search will return engagements that have ended.

**Comment by dvillacis94** [comment]
Hi @chadwtkns,

We're closing this issue, if the problem persist feel free to reopen this case.

Best regards
