### ISSUE TITLE
Chat Agent API - Login Service API - As a User

### ISSUE THREAD

**Issue by ssamaga3** [LivePersonInc/developers-community#201]
Hi Team,

We are trying to get the session id by calling the Login Service API as a user. Please refer the screen shot below.
We get the "Failed to login to AppServer" error.
We are using oAuth 1.0 as authentication.

![m2](https://user-images.githubusercontent.com/35951704/38371609-855802ac-390a-11e8-829c-103b0758a693.png)

I login to the Live Engage site by: https://z1.le.liveperson.net/a/28084016/#wa!webagent
Here it points to http://solutions.liveperson.com/

Please let us know if we have missed anything.

Actually we want to call Login Service API as a Application user. As we are not Bot user, waiting for that to be enabled.

Thanks,
Swathi

**Comment by dvillacis94** [comment]
Hi @ssamaga3,

Could you share the whole request including the headers?

**Comment by ssamaga3** [comment]
Hi David,

Please find the details below:
[RequestChatLogin As a user.docx](https://github.com/LivePersonInc/developers-community/files/1883323/RequestChatLogin.As.a.user.docx)

Let me know if you need more information.

Thanks,
Swathi

**Comment by dvillacis94** [comment]
Hi @ssamaga3,

I'm setting the Authorization type to OAuth 1.0 on Postman an setting the Key, Secret, Token, and Token Secret, and I get the correct response from the API:

![screen shot 2018-04-06 at 10 28 54 am](https://user-images.githubusercontent.com/11651229/38427953-a1d9149c-3988-11e8-82f5-628872c55460.png)

**Comment by ssamaga3** [comment]
Hi David,

Same here , i too am setting Authorization type to oAuth 1.0 and passing all the keys.
Setting Accept and Content-Type headers to Application-json
Providing the Login credentials in the Body as Raw data.

The error i get is 500 internal server error. Both in RestClient[Firefox] and Postman[Chrome]

"error":"Failed to login to AppServer http://solutions.liveperson.com/?goto=home.jsp&servicepath=a%2f%7e%7eaccountid%7e%7e%2f%23%2c%7e%7essokey%7e%7e&lnf=2&lpservice=liveEngage&stId=28084016&lang=en%2dUS&error=17","internalCode":"17"}

Can you please let me know the missing step?
I am able to ping to the server successfully.

Thanks,
Swathi

**Comment by dvillacis94** [comment]
Hi @ssamaga3,

I'm only setting the content-type:

![screen shot 2018-04-06 at 4 37 41 pm](https://user-images.githubusercontent.com/11651229/38443209-f0eb2504-39b8-11e8-952b-f9433012251c.png)

And username & password on the body:

![screen shot 2018-04-06 at 4 38 52 pm](https://user-images.githubusercontent.com/11651229/38443294-3dafbf62-39b9-11e8-94ec-e78faff0cac6.png)

**Comment by orenkatz** [comment]
Hey @ssamaga3,
Are you able to login to LiveEnage UI with this user and password?

**Comment by ssamaga3** [comment]
Hi David,

Yes, same here. Now after you mentioned tried with Only Content type header, and i get the following message:

SyntaxError: Unexpected string in JSON at position 33
    at Object.parse (native)
    at parse (/liveperson/code/agentvep/node_modules/body-parser/lib/types/json.js:88:17)
    at /liveperson/code/agentvep/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/liveperson/code/agentvep/node_modules/raw-body/index.js:262:16)
    at done (/liveperson/code/agentvep/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/liveperson/code/agentvep/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I enter domain name and Account in the URL itself and oAuth 1.0 set as below:
https://va.agentvep.liveperson.net/api/account/28084016/login?v=1.3

![image](https://user-images.githubusercontent.com/35951704/38478936-af768d16-3bd9-11e8-8c33-bb694aa4e88a.png)

Hi @orenkatz ,

Yes, I access Live Engage by clicking of the link:
https://sso3-prod.te.com/adfs/ls/IdpInitiatedSignon.aspx?LoginToRP=LiveEngage

It logins without asking credentials, -Windows authentication! I can do so from my TE account and network only.

Thanks,
Swathi

**Comment by dvillacis94** [comment]
Hi @ssamaga3,

This is related to the SSO, in this cases we recommend to have a User-Type Bot, this ones override the SSO.

As this can be treated as an [Application Login](https://developers.liveperson.com/login-getting-started.html#introduction), also try to see that the Password set on LiveEngage matches the one your trying to use but is accurate to say that I may not work.

**Comment by ssamaga3** [comment]
Hi David,

Yes, that might be the problem here. We actually pointed this point out yesterday to LiveEngage team.
It is mentioned that" Using the User Login Method, if your account has SSO enabled, this method will not be standalone and you will have to register the relevant user through your hub to provide LiveEngage with an SSO SAML Assertion.

We are actually interested in Application Login only. But as we are not BOT user, we are not able to proceed there. Have asked the team to enable us as BOT User.

Thanks for the support, once our account's are enabled with required user types will get back with queries if any.

Thanks,
Swathi
