### ISSUE TITLE
Invalid link in logout method description

### ISSUE THREAD

**Issue by lp-adevakrupakar** [LivePersonInc/developers-community#202]
https://developers.liveperson.com/consumer-experience-ios-sdk-messaging-methods.html#logout

This method conducts the following:

Unregisters from the push notification service.
Clears all SDK persistent data.
Cleans running operations (see **destruct**).  

destruct link point to a 404 page.: https://developers.liveperson.com/consumer-experience-ios-sdk-methods.html#destruct

**Comment by dvillacis94** [comment]
Hi @lp-adevakrupakar,

Thanks for pointing this out, we'll fix this broken link.
