### ISSUE TITLE
Im working on an app which is using LivePerson android sdk and in there i want to change the default Brand name.

### ISSUE THREAD

**Issue by panchalrishikesh** [LivePersonInc/developers-community#205]
As per the Customization and Branding guidelines I created branding.xml file in values folder and added brand_name string element to it but the default brand name doesn't change.

please help me out with this.

Thank you in advance.

**Comment by dvillacis94** [comment]
Hi @panchalrishikesh,

The brand_name is a String Localization, is not part of the branding.xml

https://developers.liveperson.com/android-modifying-string.html

Best regards.

**Comment by panchalrishikesh** [comment]
String localization if refering to language support. How do i change Default brand name value from My Brand to my value?

**Comment by panchalrishikesh** [comment]
Hi @dvillacis94 

Thank you for you help issue resolved

**Comment by bramley-stride** [comment]
It's the string resource `brand_name`. Unfortunately, the SDK provides this value for _every_ language, so if you don't want users with a device set to eg German to see 'Meine Marke', you have to either:
-Provide a strings.xml for _every_ language LP supports, and override that value with your brand name (which for most people would be exactly the same in every language anyway)
-If your app only has one language, you can strip all of LP's translations and keep the default only, with this in build.gradle:
```
defaultConfig {
        ...
        resConfigs 'xx'
}
```
