### ISSUE TITLE
Start Session Agent- Application Login

### ISSUE THREAD

**Issue by ssamaga3** [LivePersonInc/developers-community#206]
Hi Team,

I am trying to Post request 
https://va.agentvep.liveperson.net/api/account/28084016/agentSession?v=1&NC=true

But i do get the response:
"oauth_problem=signature_invalid&oauth_problem_advice=the oauth_signature is invalid"

I have created a Bot user, applied the API keys generated from them.
As new to this, can you please guide me the steps to call this Application Login API and Start Session Agent.

In the body , should it be pasted as it is or need to provide Bot user Login Data. If yes how?
{
  "loginData": ""
}

Thanks,
Swathi

**Comment by orenkatz** [comment]
Hey @ssamaga3,
You can check out the example we have on Github  - https://github.com/LivePersonInc/agent-sample-app

**Comment by ssamaga3** [comment]
Hi Team,

We actually want to hit the Retrieve Available Agents API and get the number of logged on agents at any point of time. 
https://developers.liveperson.com/agent-retrieve-available-agents.html

We need to call this API: 
https://{domain}/api/account/{accountId}/agentSession/{agentSessionId}/availableAgents?v=1&NC=true

Here we need to pass AccountID ,AgentSessionId and Authorization Bearer {bearer-from-login}

Can you please tell us how to fetch 
 1. AgentSessionID [Can be got by calling the Start Agent Session API -  Stuck here]
 2. Authorization Bearer {bearer-from-login}  - More clarity needed

Thanks,
Swathi

**Comment by donmanguno** [comment]
Hi @ssamaga3,

This request is part of the Agent API, which exposes the various functions of the LiveEngage agent workspace. 

As described [here](https://developers.liveperson.com/chat-agent-getting-started.html), to begin using the API you need to create an Agent Session by logging in as an agent using the [Login Service API](https://developers.liveperson.com/login-getting-started.html).  Once you have done this you will be "logged in" as an agent and can use the various methods of the Agent API.

**Comment by ssamaga3** [comment]
Hi @donmanguno Mark,

I choose the application login method. Created a Bot user and got the required API keys.Please refer the screenshot below:

![image](https://user-images.githubusercontent.com/35951704/38986433-04083e2a-43ea-11e8-8096-e145105cc200.png)

![image](https://user-images.githubusercontent.com/35951704/38986379-e4baa134-43e9-11e8-8c65-6fc79ebdbd01.png)

After this i am trying to call the Start Agent Session API:
https://va.agentvep.liveperson.net/api/account/28084016/agentSession?v=1&NC=true

Setting the required headers : Accept and Content-Type to "Application-json".
Setting the Authorization to oAuth 1.0 and filling the values as in Bot user.
In the body: 
{
  "loginData": ""
}

The error i get is 
"oauth_problem=signature_invalid&oauth_problem_advice=the oauth_signature is invalid"

We want the count of Available - Online agents at any point of time. For this we need to call the Retrieve Available Agents API - This API needs AgentSessionID, which can be got by calling the Start Session API.

Please guide.

Thanks,
Swathi

**Comment by donmanguno** [comment]
HI @ssamaga3 

In the response to the initial "Login" request you'll receive a `bearer`.

In all subsequent Agent API requests, including Create Agent Session, do not use oAuth to authenticate: rather, set the `Authorization` header to `Bearer {{yourBearer}}`

**Comment by ssamaga3** [comment]
Hi @donmanguno ,

When i try for User Login method, With oAuth authorization or not , i get the following error:

Failed to login to AppServer http://solutions.liveperson.com/?goto=home.jsp&servicepath=a%2f%7e%7eaccountid%7e%7e%2f%23%2c%7e%7essokey%7e%7e&lnf=2&lpservice=liveEngage&stId=28084016&lang=en%2dUS&error=17

I can ping the server but i cannot browse the link http://solutions.liveperson.com/
I get timeout error:
![image](https://user-images.githubusercontent.com/35951704/39035311-2bf3bf38-4497-11e8-86b3-0600bce76778.png)

Now i try the Application Login method. Not sure what to expect here. Here i will be generating API Keys as a Bot User. This Key generated will be used to start Session API. 

Where will i get the Bearer information in Application Login?

**Comment by scottwestover** [comment]
Hi @ssamaga3,

When you call the Application Login method, and provide your bot user API keys, you should get a response back that has a field called `bearer`, and this is the token you will need to use. You can see an example of the response at the bottom of the page here: [Application Login](https://developers.liveperson.com/agent-app-login.html)

Are you using the following URL to call the api: `https://va.agentvep.liveperson.net/api/account/28084016/login?v=1.3`?

**Comment by donmanguno** [comment]
Hi @ssamaga3. We are decommissioning this issues space, and therefore I am going to close this issue due to the lack of response to Scott's question.

If you are still having issues with the login service API please post your question on our new forum at https://support.liveperson.com/forum/.
