### ISSUE TITLE
【iOS】New iOS SDK Not run Xcode9.1

### ISSUE THREAD

**Issue by josercc** [LivePersonInc/developers-community#207]
The latest one of our team upgrades Xcode version 9.3 and found that your library does not compile and run properly
Finally found that you need to update your latest library, but the Xcode version of our other people is still 9.1 version.
Update the latest version we can not compile
How can this problem be solved?

**Comment by dvillacis94** [comment]
Hi @josercc,

If you’re using Xcode 9.3, you need to target the following pod ‘3.1.0.21.1601-xcode93’

**Comment by josercc** [comment]
@dvillacis94 but I'm using code not using cocoapods

**Comment by dvillacis94** [comment]
Let me see if we have the framework for that version.

**Comment by josercc** [comment]
@dvillacis94  ![image](https://user-images.githubusercontent.com/4713847/38713489-0997fb40-3f04-11e8-862a-95b554526d3b.png)

**Comment by dvillacis94** [comment]
Hi @josercc,

You can use [3.1.0](https://github.com/LP-Messaging/iOS-Messaging-SDK/releases/tag/3.1.0), 3.1.1 and 3.1.0 are the same, the only difference is 3.1.1 is compile with the new version of Swift for Xcode 9.3

**Comment by shaymLP** [comment]
@josercc, as it seems like your questions has been answered. This issue will be closed now, Please do not hesitate to open a new post if you have any further questions.
