### ISSUE TITLE
Request for documentation stating all permutations of response bodies from Messaging Window API

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/developers-community#209]
This is an enhancement request to our documentation around the Messaging Window API requested by many of our customers. They appreciate the Response and Notification Builders (e.g. https://developers.liveperson.com/consumer-int-msg-notifications.html) but they request that the information be displayed in a quickly readable way. As in, a spreadsheet or PDF documentation of the responses and what actions they are tied to (e.g. "ChatStateEvent COMPOSING: 'Indicates the Agent is typing a response'")

**Comment by EdenKupe** [comment]
Hey Chris,

Thanks for letting us know. We're aware of this request; the entire document needs an overhaul. We're working on it! There's a new PM taking over documentation for this section of the documentation and you should start seeing improvements soon. We'll take this feedback to heart when making them. I'll keep this issue open so we have it for quick reference.

Thanks again!

**Comment by donmanguno** [comment]
@cjames1224 I'm closing this issue now.

**Comment by cjames1224** [comment]
:thumbsup:

**Comment by WildYorkies** [comment]
@EdenKupe Is the new documentation also going to include what functionality you will _lose_ by using the Messaging Window API vs the built in window?

**Comment by EdenKupe** [comment]
Hey,

I'll add that into the requirements for it!
