### ISSUE TITLE
Visit Info API - Documentation unclear

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/developers-community#21]
Issue found in documentation for Visit Information API: https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html

It should be made clear that the sharkSessionId and sharkVisitorId are required for use of this API. Most notably found using the Chat Agent API https://developers.liveperson.com/agent-retrieve-chat-info.html
Not using the proper values results in a misleading error internalCode: 6 "Invalid Account id"

**Comment by EdenKupe** [comment]
Hey,

Thanks for the opening this issue. I'm assigning @lpbarber to it as he owns both of these APIs. Barber, can you please take a look?

Thanks!

**Comment by EdenKupe** [comment]
Sending this to further research at R&D.

**Comment by cjames1224** [comment]
Looking forward to the documentation update.

**Comment by EdenKupe** [comment]
Hey Chris,

Could you remind me if we resolved this in a different channel? If not, I'll copy paste the response I got from R&D here for your review :)

Thanks!

**Comment by cjames1224** [comment]
Hello Eden can you please paste the response into here? I still don't see the docu update on Internal Code "6" resulting in "Invalid Account ID" when the account is valid.
Thanks!

**Comment by EdenKupe** [comment]
Sure, here it is:

"Maybe the delicate nuance here is the use of the phrase "those parameters"... there is no relation between the "shark" prefix and the required parameters.... 

I think that the simplest way to describe it, is that the API expects 2 parameters:
- one parameter that identifies the visitor ==> visitorId
- one parameter that identifies the session ==> sessionId

There's no reason (nor there should be one) to mention the "shark" prefix in external documentation when describing the parameters required for this API.  "

Could you further elaborate on the Internal Code issue? I missed it first time around.

**Comment by cjames1224** [comment]
Hey Eden,

While dealing with a bot partner, they needed assistance with using the Visit Info API (https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html) to have the bot retrieve visit info about the visitor. At first try they did not know "what kind of session ID is required and where they could get it". 

My first guess was **rtSessionId** from here (https://developers.liveperson.com/agent-retrieve-chat-info.html) which was wrong. There are multiple session Ids in our APIs and so specifying would be helpful as to not repeat the confusion my client had.

When you make a call to Retrieve Chat Info using the Chat Agent API https://developers.liveperson.com/agent-retrieve-chat-info.html you receive an output that has **BOTH** **rtSessionId** and **sharkSessionId**. The key to making the visit info api call successfully is to use the **sharkSessionId**. It is an important distinction for using the visit info api. Example output:

`{
  "info": {
    "link": [
      {
        "href": "https://lo.convep.liveperson.net/api/account/56363214/chat/H291897854714145071-e18000ffa1ef4cc482848918da290ae1K8389091/info",
        "rel": "self"
      },
      {
        "href": "https://lo.convep.liveperson.net/api/account/56363214/chat/H291897854714145071-e18000ffa1ef4cc482848918da290ae1K8389091/info/visitorName",
        "rel": "visitor-name"
      },
      {
        "href": "https://lo.convep.liveperson.net/api/account/56363214/chat/H291897854714145071-e18000ffa1ef4cc482848918da290ae1K8389091/info/visitorTyping",
        "rel": "visitor-typing"
      },
      {
        "href": "https://lo.convep.liveperson.net/api/account/56363214/chat/H291897854714145071-e18000ffa1ef4cc482848918da290ae1K8389091/info/agentTyping",
        "rel": "agent-typing"
      }
    ],
    "state": "chatting",
    "chatSessionKey": "H291897854714145071-e18000ffa1ef4cc482848918da290ae1K8389091",
    "skillName": "BotSkill",
    "skillId": 923856932,
    "agentName": "BotHelper",
    "agentId": 923018132,
    "startTime": "2017-07-20T11:14:43.546-04:00",
    "duration": 0,
    "lastUpdate": "2017-07-20T11:14:44.891-04:00",
    "chatTimeout": 40,
    "visitorId": 1721502514630566,
    "agentTyping": "not-typing",
    "visitorTyping": "not-typing",
    "visitorName": "You",
    "rtSessionId": 4294967779,
    "sharkVisitorId": "Q4YTlmMWU2MDFlYjNmZjA4",
    "sharkSessionId": "RR4JT64HTfK_eExma4HWXg",
    "sharkContextId": "4",
    "engagementId": "922791732",
    "campaignId": "922791632",
    "language": "en-US"
  }
}`

Furthermore, when you use the rtSessionId in place of sharkSessionId for the Visit Info API call, you get Internal Code Error "6" which states "Invalid Account ID"... this does not add up as the account ID is valid and the only issue seen by my client is the wrong session id. I simply want the documentation to be more clear about this.

Hope this helps.
Chris

**Comment by orenkatz** [comment]
@EdenKupe Can you please check the documentation?

**Comment by cjames1224** [comment]
So ..... was an _update to the documentation_ to reflect my request?

**Comment by orenkatz** [comment]
We will review the changes and will add the necessary content, thank you for your input.
