### ISSUE TITLE
Support Xcode 9.3

### ISSUE THREAD

**Issue by rplankenhorn** [LivePersonInc/developers-community#211]
Any plans to support Xcode 9.3 sometime soon?

**Comment by orenkatz** [comment]
Hey @rplankenhorn 
Our latest SDK (v3.1.1) supports Xcode 9.3 
https://github.com/LP-Messaging/iOS-Messaging-SDK

**Comment by rplankenhorn** [comment]
@orenkatz Oh ok.  The release notes for that version say Xcode 9.2.  Is that a typo?

**Comment by orenkatz** [comment]
Yes, it should be 9.3, we will fix it
