### ISSUE TITLE
Extra character in Application Login url in the Login Service API

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#212]
In the POST request URL for the Application Login method, there is an extra `]`.

Reference: `https://{domain}/api/account/{accountId}]/login?v=1.3`

should be: `https://{domain}/api/account/{accountId}/login?v=1.3`

Documentation page: https://developers.liveperson.com/agent-app-login.html

**Comment by orenkatz** [comment]
@EdenKupe

**Comment by EdenKupe** [comment]
Thanks for reporting, fixed.
