### ISSUE TITLE
Extra space between keyboard and text input

### ISSUE THREAD

**Issue by rplankenhorn** [LivePersonInc/developers-community#214]
I am seeing extra space (see screenshot) between the keyboard and the text input for both 3.0.0.17.1448 and 3.1.2.0.1656.  Any ideas?

![screen shot 2018-04-30 at 11 26 02 am](https://user-images.githubusercontent.com/228338/39438363-889f5a24-4c69-11e8-9907-807c418dda59.jpg)

**Comment by rplankenhorn** [comment]
It looks to be the same issue as in this release:  https://github.com/LP-Messaging/iOS-Messaging-SDK/releases/tag/2.1.2

**Comment by rplankenhorn** [comment]
It's worse on the iPhone X.

![screen shot 2018-04-30 at 1 35 50 pm](https://user-images.githubusercontent.com/228338/39443847-6cf6708e-4c7b-11e8-90c9-c4e3bb8f1bf7.jpg)

**Comment by hpur** [comment]
Hi @rplankenhorn 
There is not v3.1.2.* yet, but I'll check it on v3.0.0 and v3.1.1 as well, on which device the issue occurs?

**Comment by rplankenhorn** [comment]
@hpur Thanks!  It happens when I tap on the text field and the keyboard shifts up.

**Comment by hpur** [comment]
Hi @rplankenhorn 
In your screenshots, you add to the keyboard toolbar with a done button that seems it is a cause the issue.
The reason is that you override our SDK's keyboard, try to use with our default SDK's keyboard.
The done button is not necessary if you will touch on the conversation screen the keyboard will disappear.

**Comment by rplankenhorn** [comment]
Hi @hpur.  I don't think that's the issue.  I still see the grey gap when I remove the done button.

![screen shot 2018-05-02 at 10 56 54 am](https://user-images.githubusercontent.com/228338/39534606-90d02220-4df7-11e8-8657-feaac5aa773a.jpg)

**Comment by hpur** [comment]
Hi @rplankenhorn 
I tried to reproduce it with no success.
Can you share with me the delegate implementation + the view controllers you implement our SDK?

**Comment by rplankenhorn** [comment]
@hpur I'm trying to create a sample app but as of right now, we can reproduce it on both a React Native implementation and a pure native implementation.

**Comment by shaymLP** [comment]
Hi @rplankenhorn ,
First of all, we do not support React Native integrations. You can use cross-platform integrations, but we can't support the outcome of such usage. As for the Pure Implementation, i wasn't able to recreate the issue on any of the versions you mentioned. Storyboard constraints might got broken using the "custom button" you added, please try and recreate the container you are using to display the conversation. We can look into it, but you'll have to share a little bit more regarding your UI configurations (Code, Storyboard, etc.).

**Comment by rplankenhorn** [comment]
Would really like @dvillacis94's help here.  He's worked with me before on my project and is well aware of our React Native implementation and your support.

@shaymLP Not sure what custom button you are referring to.  I've removed the input accessory view from the page but there still exists a 50 pixel view right below where text is entered if I run the SDK on iPhone X.

I am able to reproduce it every time when I wrap the Live Person view controller inside a tab bar.  See the sample project here:
https://github.com/rplankenhorn/LivePerson/tree/whiteSpaceTabBarIssue.

You'll notice that it is a fork from a project @dvillacis94 setup:  https://github.com/dvillacis94/LivePerson 

See the video below:
![livepersonissue](https://user-images.githubusercontent.com/228338/40022052-77967932-578c-11e8-8fc4-c4b6f9ecd738.gif)

**Comment by orenkatz** [comment]
Hey @rplankenhorn,
I'm sorry but we do not support React-Native implementation, the sample David shared with you was just an example of using our SDK with React-Native but it is not supported by LivePerson.
Oren.

**Comment by rplankenhorn** [comment]
Having some internet issues.  Will upload shortly.

**Comment by rplankenhorn** [comment]
Should be uploaded now.

**Comment by rplankenhorn** [comment]
![livepersonissuenative](https://user-images.githubusercontent.com/228338/40064535-580b92d4-5825-11e8-9431-924052cc313a.gif)

**Comment by hpur** [comment]
Hi @rplankenhorn 
I will look into it and get back to you as soon as possible.

Regards,
Hadar

**Comment by hpur** [comment]
Hi @rplankenhorn 
Line #19 in your MessagingViewController.swift file: 

<img width="638" alt="screen shot 2018-05-16 at 11 34 04 pm" src="https://user-images.githubusercontent.com/37905019/40142574-ad88d77a-5961-11e8-8395-e7256d53b194.png">

is the reason for the space issue, if you'll remove this line, the space will disappear: 

![gif](https://user-images.githubusercontent.com/37905019/40143399-06b2e406-5964-11e8-902f-ffb46d40f80a.gif)

To avoid future problems, I saw you call to removeConversation from viewDidDisappear func, this implementation can cause some problems, documentation to that you can find [here](https://developers.liveperson.com/consumer-experience-ios-sdk-messaging-methods.html#removeconversation) 

Regards,
Hadar.

**Comment by hpur** [comment]
Hi @rplankenhorn 
I'm sorry but we do not support React-Native implementation, on the Pure iOS implementation the issue has been resolved.

Regards,
Hadar.
