### ISSUE TITLE
CoApp issue - iOS SDK - On production 

### ISSUE THREAD

**Issue by refnandor** [LivePersonInc/developers-community#215]
Hi

We have been facing issues with the coApp SDK, the calls are not arriving, we have checked twice the step by step guide but it is not working anymore. We need urgent support due is on production now. Can we have a quick call or skype session? 
They are using Messaging SDK V 3.0.0  and the same coapp version from the beginning
Xcode v 9.3
Target 10.1
iOS version 11.3.1
LP account: 79415415
customer name: IATAI 
Project name: VISA rewards

Here is the test app:

https://my.testfairy.com/download/6MT30D9N68S2TCHK64WK0C1G5QT44FY3FVG75QFDB2105GQQF47PWZ49VM/getapp
You need to go to the support "I have a question" then "I want to talk with someone" then the agent will initiate the coapp session (a real agent will be in a session with you) ask for the video call.

the user is: usertest2@iatai.com
pass: Iatai2018#

Thank you in advance
Regards

**Comment by refnandor** [comment]
Some screencaptures:

![captura de pantalla 2018-04-30 a la s 5 39 48 p m](https://user-images.githubusercontent.com/32464396/39534042-4027d544-4df6-11e8-8649-ec0567538f2d.png)
![captura de pantalla 2018-04-30 a la s 5 40 16 p m](https://user-images.githubusercontent.com/32464396/39534055-4b6ff0b2-4df6-11e8-9832-3a491dcbcd89.png)

**Comment by refnandor** [comment]
Some can help us?

**Comment by manzalyshay** [comment]
@refnandor @EdenKupe , We are looking into it.

**Comment by shaymLP** [comment]
@refnandor @EdenKupe , We are looking into it.

**Comment by dvillacis94** [comment]
@refnandor,

The CoApp SDK doesn't support BitCode, do you have that **Build Option** - disable?

**Comment by refnandor** [comment]
Yes, it is disabled

The problem has started after the xcode update for the new devices and the
new iOS

Regards


On Mon, May 7, 2018 at 10:03 AM, David Villacis <notifications@github.com>
wrote:

> @refnandor [github.com]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=oX0MslGJ7EjY4rLjpsL7Yc6W9JhvveRng69I62SjrsI&s=P_6q8wGCVecrEx3vnRenJJK_vgtFFpWoJQTMFJ4DPMk&e=>
> ,
>
> The CoApp SDK doesn't support BitCode, do you have that *Build Option* -
> disable?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [github.com]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D387094537&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=oX0MslGJ7EjY4rLjpsL7Yc6W9JhvveRng69I62SjrsI&s=8oShKVV6dyUZW0zq8gEDcS_yyHI0rY3NkQn-zYVMw-4&e=>,
> or mute the thread [github.com]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDKJBa1P3J6wm4Xii-5F6Gr5QygvHJDks5twGJEgaJpZM4TvtAd&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=oX0MslGJ7EjY4rLjpsL7Yc6W9JhvveRng69I62SjrsI&s=qNf2Xzg553rwnk0ZMpw38x_4xMD38tD_kDOIIUEhHnQ&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by dvillacis94** [comment]
Ok, I'm currently checking this with the R&D team.

**Comment by refnandor** [comment]
+ Kyle


On Mon, May 7, 2018 at 12:28 PM, David Villacis <notifications@github.com>
wrote:

> Ok, I'm currently checking this with the R&D team.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [github.com]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D387140243&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Japl8StLCF8G9cf0NA869xGDyFertymg0OimITs1IZg&s=ELlPxFpEHNv6lzTfZEhkBnv_JTAHRolvfaov8_lhAqw&e=>,
> or mute the thread [github.com]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDGZIUvMVLqJC0T3pJeW2QVIJksFSks5twIQ4gaJpZM4TvtAd&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Japl8StLCF8G9cf0NA869xGDyFertymg0OimITs1IZg&s=vPqQgAq4U5KZqLAQ_WUXGRkuskyfhBVVGGJSRDm6QEY&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by dvillacis94** [comment]
@refnandor,

I was able to run the CoApp SDK using the following Configurations:

```ruby
pod 'LPMessagingSDK','3.0.0.17.1448'
pod 'LPCoAppSDK','0.1.0.170'
```
**Bitcode Disable:**

![screen shot 2018-05-08 at 12 09 16 pm](https://user-images.githubusercontent.com/11651229/39768968-c9accda8-52b8-11e8-8c82-8df3544bce59.png)

**Library Search Paths:**

> Note: debug & release mirror each other.

![screen shot 2018-05-08 at 12 11 05 pm](https://user-images.githubusercontent.com/11651229/39769026-f8c461fa-52b8-11e8-8f4c-736af27ca584.png)

**Framework Search Path:**

> Note: debug & release mirror each other.

![screen shot 2018-05-08 at 12 12 41 pm](https://user-images.githubusercontent.com/11651229/39769103-3ad7771c-52b9-11e8-9834-f9a8c8e19641.png)

**Comment by refnandor** [comment]
Hi David

Thanks for your reply, we will validate this procedure and let you know the
output

Regards


On Tue, May 8, 2018 at 11:15 AM, David Villacis <notifications@github.com>
wrote:

> @refnandor
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=8pj9_7tujdoKYpvp7lkaPhWWC2B4GGzZTiOo-LuTOmo&e=>
> ,
>
> I was able to run the CoApp SDK using the following Configurations:
>
> pod 'LPMessagingSDK','3.0.0.17.1448'
> pod 'LPCoAppSDK','0.1.0.170'
>
> *Bitcode Disable:*
>
> [image: screen shot 2018-05-08 at 12 09 16 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_11651229_39768968-2Dc9accda8-2D52b8-2D11e8-2D8c82-2D8df3544bce59.png&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=4AFCdCwaKip5Uh7mFgsZbOSLeEtAIhARNJxn6EU1HsE&e=>
>
> *Library Search Paths:*
>
> Note: debug & release mirror each other.
>
> [image: screen shot 2018-05-08 at 12 11 05 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_11651229_39769026-2Df8c461fa-2D52b8-2D11e8-2D8f4c-2D736af27ca584.png&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=qnek5zF5-ca_FW_ATlln7t0XO1CRHDmWMLfs76VmdyU&e=>
>
> *Framework Search Path:*
>
> Note: debug & release mirror each other.
>
> [image: screen shot 2018-05-08 at 12 12 41 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_11651229_39769103-2D3ad7771c-2D52b9-2D11e8-2D9834-2Df9a8c8e19641.png&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=UQRwVTU4nXXc-lVL-rykRURuOnfAsHQdZbxTuev-AIg&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D387457737&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=Z8ZpWtMtpEULInZQUHws_QKkclSRri5plHNP0w1f_Iw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDPBpcVSFeTXvbZZe08-5FN0IROsyquks5twcSJgaJpZM4TvtAd&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=3t_JPbm9DJUPCo9ifyIFy1r8VHfwN7RvWgkksLoAHf4&s=kngRLZ0oK5DYZ3fMNOFqw7LAAhqNJMSqrZwbASRLG5k&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by refnandor** [comment]
There is an error when they try to install the pod ‘LPCoAppSDK’ : 
[!] Unable to find a specification for 'LPCoAppSDK'.

![captura de pantalla 2018-05-09 a la s 4 04 29 p m](https://user-images.githubusercontent.com/32464396/39842424-fd68c810-53ab-11e8-8c49-1c024dea63f6.png)
The pod file of the test

![captura de pantalla 2018-05-09 a la s 4 06 00 p m](https://user-images.githubusercontent.com/32464396/39842430-ff93e994-53ab-11e8-9b74-7cf68707a15f.png)
The error to execute the pod install

Thanks

**Comment by dvillacis94** [comment]
@refnandor,

Can you confirm the version of the LPCoApp SDK you're using?

Meanwhile I'll get the framework file for '0.1.0.170'.

**Comment by dvillacis94** [comment]
@refnandor,

You can find the link to the CoApp SDK '0.1.0.170', [here](https://send.firefox.com/download/1443fa58bc/#SdS3HyesmO7g4TWJlQSW-Q),

This link will be available for 24hrs or one download.

**Comment by refnandor** [comment]
Hi David

The link is expired, can you please send it again please?



Regards


On Thu, May 10, 2018 at 4:54 PM, David Villacis <notifications@github.com>
wrote:

> @refnandor
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Ew6kEwVZgsJBsm45XKN54Bs-0-81VqvcAoPxvA56AH4&s=WbHNt10qAHKjQkwUBYqrlwPGTEqt5HQzubSszPzbaE8&e=>
> ,
>
> You can find the link to the CoApp SDK '0.1.0.170', here
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__send.firefox.com_download_1443fa58bc_-23SdS3HyesmO7g4TWJlQSW-2DQ&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Ew6kEwVZgsJBsm45XKN54Bs-0-81VqvcAoPxvA56AH4&s=U4P9jteGoIkQlYKTsBtDxVLeGe0ziOYWpFwYIHk9ibo&e=>
> ,
>
> This link will be available for 24hrs or one download.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D388197906&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Ew6kEwVZgsJBsm45XKN54Bs-0-81VqvcAoPxvA56AH4&s=98Rul50NFr9xqthhKcylHnqF-w_JtEhqi1jj744k08c&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDI77HYgsSqGWQY5YNhzFg4259Angks5txLcSgaJpZM4TvtAd&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=Ew6kEwVZgsJBsm45XKN54Bs-0-81VqvcAoPxvA56AH4&s=qljcJtWn6wzTNLpH8k312FRVUgeYRD74kBQClUfHVxY&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by dvillacis94** [comment]
@refnandor,

[here](https://send.firefox.com/download/c1eee6ce82/#qsNLrFY9pbl4FEmSpWqY-g)

let me know if this works.

**Comment by refnandor** [comment]
Hi David

Many thanks, it did work
We will try with this new version

Regards


On Fri, May 11, 2018 at 11:17 AM, David Villacis <notifications@github.com>
wrote:

> @refnandor
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=NkhQzvQtHNP7AsnWYo1HeXKADoSPWIOlYRU_o-KKpqA&s=HWcM8wxJuGq9W2H7ZvMkJbmHmkzAjqdISX1LtNJZWME&e=>
> ,
>
> here
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__send.firefox.com_download_c1eee6ce82_-23qsNLrFY9pbl4FEmSpWqY-2Dg&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=NkhQzvQtHNP7AsnWYo1HeXKADoSPWIOlYRU_o-KKpqA&s=cz7KjH3BxpLgK7g9ysweM9ePdwLfsjT4AeoNwHL-pRk&e=>
>
> let me know if this works.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D388412007&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=NkhQzvQtHNP7AsnWYo1HeXKADoSPWIOlYRU_o-KKpqA&s=krPM56sqVORC_xOJg1UpEb3OpMegycb7W62oEfsDnfQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDONe6KhMDvxqohefdcq-5Fa90PR1ECks5txbmkgaJpZM4TvtAd&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=NkhQzvQtHNP7AsnWYo1HeXKADoSPWIOlYRU_o-KKpqA&s=q2MqhgjjqALbDrsVlgHb72HtxFaxh_9EJNwEM14DeKs&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by refnandor** [comment]
Hi David. They still working on this, today is holiday in Colombia, so we will have some news tomorrow.
Thanks

**Comment by dvillacis94** [comment]
No worries,

Let us know, enjoy.

**Comment by refnandor** [comment]
Hi David

It didn't work, I'm collecting all the relevant information about this error ...

**Comment by dvillacis94** [comment]
Ok,

I'll be waiting for the Information.

**Comment by refnandor** [comment]
Hi David

The developer just sent me an example where you can find the current error with the latest version of the COAPP SDK: https://we.tl/YMxhPwYXyx
Please help us to fix this. 

Thank you

**Comment by dvillacis94** [comment]
@refnandor,

I'm checking this.

**Comment by refnandor** [comment]
Hi David. 

According with Carlos, the video call is not working at all, so you can see the errors after compile. 
Please help us to find a solution for this.

Regards

**Comment by dvillacis94** [comment]
I'm not even able to compile it, I got errors from other Frameworks.

**Comment by dvillacis94** [comment]
Yeah that would be better, I think.

**Comment by refnandor** [comment]
Hi David 

Let's have this call 15:00 h EST. Sending you the invite...

Thanks

**Comment by dvillacis94** [comment]
Hi @refnandor,

Because of Memorial Day, the office USA office is closing at 2:00pm EST, and we're back until Tuesday.

We'll not be able to join this call.

**Comment by refnandor** [comment]
David, so let's make it now, what do you think?

Regards


On Fri, May 25, 2018 at 12:22 PM, David Villacis <notifications@github.com>
wrote:

> Hi @refnandor
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=HfltPD2pxdkZb48i_CaiThcvkLLk0nkSDD_sz2WmC1c&e=>
> ,
>
> Because of Memorial Day, the office USA office is closing at 2:00pm EST,
> and we're back until Tuesday.
>
> We'll not be able to join this call.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D392125398&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=TBB0LIv64mfgHfm9IhIWZlvEHecoNHmz_6sdaKxN2cY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDAeUsYW3Az-5FDZGNX4Sh9eqyyCq1Jks5t2D28gaJpZM4TvtAd&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=kL08ZqZZQfAE8qfZx4ugTS7dYnyCTnt0GmcfVMlW9uw&e=>
> .
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by dvillacis94** [comment]
We can do that, so I can get any errors if we need to communicate with other teams.

**Comment by refnandor** [comment]
David, Barry.

Unfortunately they only can attend this until 3:00 pm EST. If you can't
join us, please help us to assign us some else that can help with the
error. They need to solve these issues today (upload to appstore and solve
the coapp error).

PS. IATAI just hire the enhancement support (Gold)
Thank you

Regards


On Fri, May 25, 2018 at 12:25 PM, Fernando Ramirez <framirez@liveperson.com>
wrote:

> David, so let's make it now, what do you think?
>
> Regards
>
>
> On Fri, May 25, 2018 at 12:22 PM, David Villacis <notifications@github.com
> > wrote:
>
>> Hi @refnandor
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refnandor&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=HfltPD2pxdkZb48i_CaiThcvkLLk0nkSDD_sz2WmC1c&e=>
>> ,
>>
>> Because of Memorial Day, the office USA office is closing at 2:00pm EST,
>> and we're back until Tuesday.
>>
>> We'll not be able to join this call.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_215-23issuecomment-2D392125398&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=TBB0LIv64mfgHfm9IhIWZlvEHecoNHmz_6sdaKxN2cY&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ae9eDAeUsYW3Az-5FDZGNX4Sh9eqyyCq1Jks5t2D28gaJpZM4TvtAd&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=__ObA-llf_yGyXdR0nt6K9SYd5OcUEfouzSHUbXj-dg&m=i2GyHL8jhdtfSWWWV_iZnfo1K_wwuWcneKEfBvSaqW8&s=kL08ZqZZQfAE8qfZx4ugTS7dYnyCTnt0GmcfVMlW9uw&e=>
>> .
>>
>
>
>
> --
> *Fernando Ramirez*
> O. +525557220252
> M. +5215536472920
>



-- 
*Fernando Ramirez*
O. +525557220252
M. +5215536472920

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
