### ISSUE TITLE
Background Color - Structured Content

### ISSUE THREAD

**Issue by Manegoldsr21** [LivePersonInc/developers-community#219]
Hi,

I am working on sending structured content through the chat agent API. Everything is working as expected except that I get an error whenever I add the "background-color" style. I am not sure if this attribute is just documented incorrectly or if it is actually a bug in the API. The rest of the style attributes are working successfully for me though.

https://developers.liveperson.com/structured-content-templates.html#metadata

Thanks

**Comment by hpur** [comment]
Hi @Manegoldsr21 ,  
I will look into it and get back to you as soon as possible.

**Comment by hpur** [comment]
Hi @Manegoldsr21 
I have fully investigated the issue with "background-color" style that you reported. 
The issue has been assigned to our Research and Development Team and our developers are now working to resolve the issue. 
Although we do not have an exact date for remedial actions, we do intend to have this deployed in a future release.

Regards,
Hadar.
