### ISSUE TITLE
Messaging Window API - Error 4407 Resolution?

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/developers-community#22]
I am receiving Error 4407 on the Messaging Window API 
https://developers.liveperson.com/consumer-int-protocol-overview.html

There is no suggestion for how to resolve 4407 that I can find. Please provide resolution steps for this error. Thank you.

**Comment by EdenKupe** [comment]
Hey,

Thanks for opening this issue. Forwarding to the relevant product manager for more information.

Thanks!

**Comment by cjames1224** [comment]
Thank you. Should I expect updates on this thread, or somewhere else?

**Comment by EdenKupe** [comment]
Hey!

Best to answer here, for future generations :) Here's the reply I got from RnD:

"The error code indicates that there is a problem with the JWT (expired, wrong account etc...), You should trying getting a fresh JWT and return to the API with it.

What is the flow? Who issued the original JWT?"

If you can provide me the answer to the last question, I'll make sure to pass it over to them.

Thanks!

**Comment by cjames1224** [comment]
Thank you for your reply - I resolved the issue. I did not call the POST to
authenticate
https://lpgithub.dev.lprnd.net/pages/SENTINEL/idp/docs/#operation/authenticate

It was unclear because the documentation was misleading regarding a 4407
error.

**Comment by EdenKupe** [comment]
Got it, thanks! I'm planning on refreshing this documentation in any case; I'll add this to the list of issues.

Closing the issue for now!
