### ISSUE TITLE
Consumer Messaging History API

### ISSUE THREAD

**Issue by ksatoLP** [LivePersonInc/developers-community#222]
Hi team,

Our client is curious when the full transcript data for messaging until a certain time can be available on MCS dashboard. (We are guessing "it depends", and there is no solid timeline like chat.)

We checked Consumer Messaging History API developer page but we are unable to find answer.
Would you know the answer for this question from client ?

https://developers.liveperson.com/consumer-experience-messaging-history-conversation-content.html

**Comment by orenkatz** [comment]
Already opened in the new forum 
https://support.liveperson.com/question/regarding-the-timing-which-we-can-see-the-conversation-history-for-messaging-consumer-messaging-history-api/
