### ISSUE TITLE
Pass email from the app and pass it as engagement attribute (Messaging SDK)

### ISSUE THREAD

**Issue by icruzh** [LivePersonInc/developers-community#224]
Hi!
How can I get the email from the app and pass it as engagement attribute to the agent console? (iOS and Android)

Regards

**Comment by dvillacis94** [comment]
Hi @icruzh,

You will need to either use Authenticated Chat and pass it with the JWT or use the Monitoring API inside the SDK.

**Comment by orenkatz** [comment]
Please note that we have moved to a new space - https://support.liveperson.com/forum
You can submit your question there.
Oren
