### ISSUE TITLE
Upload the app to the apple store

### ISSUE THREAD

**Issue by icruzh** [LivePersonInc/developers-community#225]
We can not upload the app to the apple store. We are using version 3.1.1 and xcode 9.3.
Attached you can find the logs.
Can you help us?
[IDEDistribution.standard.txt](https://github.com/LivePersonInc/developers-community/files/2033028/IDEDistribution.standard.txt)

**Comment by orenkatz** [comment]
Please note that we have moved to a new space - https://support.liveperson.com/forum
You can submit your question there.
Oren
