### ISSUE TITLE
inApp Messaging SDK - Bancomer app 85237869

### ISSUE THREAD

**Issue by refnandor** [LivePersonInc/developers-community#226]
We are presenting an issue when we are implementing the inApp Messaging SDK on a Bancomer app:

![image](https://user-images.githubusercontent.com/32464396/40454017-c4698584-5eac-11e8-8221-5d5395a9c6f3.png)

The project configuration:

![image](https://user-images.githubusercontent.com/32464396/40454092-07e4cf26-5ead-11e8-8d7d-1499f98f464d.png)

Can you please help us to understand this error and how to fix them?

[Log error multipagos.txt](https://github.com/LivePersonInc/developers-community/files/2033208/Log.error.multipagos.txt)

Thanks

**Comment by dvillacis94** [comment]
Hi @refnandor,

That Project configuration is from the SDK?

**Comment by orenkatz** [comment]
Please note that we have moved to a new space - https://support.liveperson.com/forum
You can submit your question there.
Oren
