### ISSUE TITLE
Update steps mobile application keys for inApp Messaging

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#23]
The steps and screenshots to the **Mobile app management**:

1. display the old locations for both iOS and Android inApp Messaging documentation:
[In-App Messaging SDK for Android > Notifications](../blob/master/pages/documents/consumer%20experience/android-sdk/enable-push.md)
[In-App Messaging SDK for iOS > Notifications ](../blob/master/pages/documents/consumer%20experience/ios-sdk/pushnotifications.md)
![chrome_2017-08-09_16-40-07](https://user-images.githubusercontent.com/29775347/29127493-85a1eade-7d21-11e7-9e7b-728d2099b12e.png)

2. are described and numbered differently, although basically the same until the last step.

**Comment by EdenKupe** [comment]
Hey,

Sorry for the delay here. I've forwarded this to the In App team and they'll update the screenshots + steps.

Thanks!

**Comment by nirlachman-liveperson** [comment]
Hi,
Updated screenshot for iOS. Will be deployed within the release of SDK 2.7 in the beginning of September 2017.
Thanks

**Comment by chickpin** [comment]
Screenshot updated of Android. Will be deployed in SDK release 2.7

**Comment by pmolensky** [comment]
Thanks both, looking forward to the documentation update.

**Comment by pmolensky** [comment]
Thanks for updating the images. I took the liberty of updating the descriptions for both platforms to give the documentation a more consistent look.
