### ISSUE TITLE
Hello Conversation Builder: Change/link User Says Interaction

### ISSUE THREAD

**Issue by jaltschuler** [LivePersonInc/developers-community#251]
When indicating the User Says interaction, we're only saying "User Interaction". Can we change to "User Says Interaction" and can we link it to the Component Breakdown which does a nice description?

**Comment by jaltschuler** [comment]
Also, we're not renaming it to say "Hello" we are providing a sample intent or phrase that might trigger it.

**Comment by EdenKupe** [comment]
Done.
