### ISSUE TITLE
Hello Conversation Builder: For Welcome add look at Patterns

### ISSUE THREAD

**Issue by jaltschuler** [LivePersonInc/developers-community#252]
Before we go to the Preview to see the Hello world work, we should take a brief look at the Interaction settings to see the patterns that trigger it. This way when you go to the previewer and type "hi" you'll understand why / what its matching.

**Comment by EdenKupe** [comment]
The pattern match is mentioned in the doc and links to pattern matching. Not sure that directing the user's attention to the settings panel is a good idea in this hello world context. However, @trosel wrote this one so I'll let him decide. Can easily be added.

**Comment by EdenKupe** [comment]
@trosel can we close this one?
