### ISSUE TITLE
OAUTH / Token not available on visit information API

### ISSUE THREAD

**Issue by devin-liu** [LivePersonInc/developers-community#28]
https://developers.liveperson.com/rt-interactions-visit-information-visit-information.html

I always get this error when I try to hit that endpoint with oauth1 - 
oauth_problem=signature_invalid&oauth_problem_advice=the oauth_signature is invalid

I always get this error when I try to hit that endpoint with bearer tokens - 
{'time': 1503028861116, 'message': 'Invalid Account id: XXXXXX(blanked out on purpose)', 'internalCode': 6}

What is going on? Is this API still working?

Here is the route I am trying - trying to get access to visitors on my agent chats

https://va.agentvep.liveperson.net/api/account/{accountID}/monitoring/visitors/{visitorId}/visits/current/state?v=1&filter=agent&sid=' + {sid}

Also what are valid subdomains for this service? In the example provided -
https://lo.v.liveperson.net/api/account/12345678/monitoring/visitors/222/visits/current/state?v=1&filter=agent&sid=123.567

That subdomain does not seem to be OK.

**Comment by pmolensky** [comment]
Hi Devin-Liu,

The correct domain for the Visit Information API (for UK-based accounts) is [lo.v.liveperson.net](https://lo.v.liveperson.net), which you can check for your own account by retrieving the domain using the service name [smt](https://developers.liveperson.com/rt-interactions-visit-information-overview.html#getting-started) https://api.liveperson.net/csdr/account/{AccountId}/service/smt/baseURI.json?version=1.0
If your account is not hosted on UK-servers, you'll get the "Invalid Account id"-error.

The domain [*.agentvep.liveperson.net](https://va.agentvep.liveperson.net) is for the [Login Service API (_service name = agentVep_)](https://developers.liveperson.com/login-getting-started.html#getting-started) for US-based accounts.

**Comment by EdenKupe** [comment]
Hey Devin,

Did the suggested solution above work for you? If so, let me know and I'll close the issue.
