### ISSUE TITLE
Incorrect properties for engagementData event

### ISSUE THREAD

**Issue by kstrickland09** [LivePersonInc/developers-community#29]
According to the [documentation on the developers community](https://developers.liveperson.com/lp-tag-engagement-window.html#engagementdata), the properties of the engagementData event of lpUnifiedWindow are **engagementId** and **state**. However, **engagementId** is not available and **engagementName** is instead.

**Comment by EdenKupe** [comment]
@lpbarber can you confirm this is the case so that I can update the documentation?

**Comment by barbarber** [comment]
@miki2826

**Comment by EdenKupe** [comment]
Hey @miki2826, can you advise on this?

**Comment by miki2826** [comment]
Hi @kstrickland09 ,
You are right, we will fix the docs to show **engagementName** instead.

Thanks,
Miki.
