### ISSUE TITLE
Domain = smt?

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#3]
I don't think smt is the right domain to use for this API?

**Comment by EdenKupe** [comment]
Hey @lp-wodell, which API are you referring to?

**Comment by lp-wodell** [comment]
Yes, I think it was the EA API.

**Comment by lp-wodell** [comment]
@EdenKupe: A client is about to use this API themselves and because I am away in training this week I have pointed them at this URL, so a quick turnaround on this would be good.

**Comment by EdenKupe** [comment]
Hey,

I'm told that 'smt' is indeed the right domain for this API. Are you seeing an error related to the domain?

**Comment by lp-wodell** [comment]
No, I'm not - I cannot remember why I raised this now. Consider it closed.
