### ISSUE TITLE
.GetClock not working or Documentation unclear

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/developers-community#30]
Issue found with the Messaging Window API documentation:
https://developers.liveperson.com/consumer-int-protocol-overview.html

> For clients that cannot send Ping messages (such as browsers): Utilize the applicative .GetClock request: {"kind":"req","id":"1","type":".GetClock"}.

This does not seem to work or there is not enough information in the documentation to implement .GetClock. Using the example Consumer UMS example this request does not work.

**Comment by cjames1224** [comment]
Bump

**Comment by EdenKupe** [comment]
@eitan101 any insight you can provide here?

**Comment by kstrickland09** [comment]
I just noticed this is the same issue as I reported in [Issue #51](https://github.com/LivePersonInc/developers-community/issues/51). We found that removing the "." before "GetClock" resolved the issue.

**Comment by EdenKupe** [comment]
Let me know if this works and I'll close this issue. The documentation has been updated.

**Comment by cjames1224** [comment]
Thank you! I will close this.
