### ISSUE TITLE
getNumUnreadMessages on iOS inApp messaging?

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#31]
On Android it's possible to retrieve the number of unread messages using
`public static int getNumUnreadMessages(String brandId)` [documentation](https://developers.liveperson.com/android-methods.html#getnumunreadmessages)
Is there a similar function call on iOS available?

**Comment by nirlachman-liveperson** [comment]
Hi,
No such API currently. 

Nir

**Comment by pmolensky** [comment]
Hi Nir, any plans to release such function on iOS?

**Comment by nirlachman-liveperson** [comment]
Hi,
Can you please contact one of our product managers regarding this?

Thanks!

**Comment by pmolensky** [comment]
Ok
