### ISSUE TITLE
Rich Message Channel Capabilities Search Field does not work

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#312]
Page: https://developers.liveperson.com/getting-started-with-rich-messaging-rich-messaging-channel-capabilities.html

Bug: Search field does not work

Detail: There is a search field above the `Rich Messaging Channel Capabilities` table that looks like it should filter the table when you type a term into the input field. However, nothing happens when I type anything into the box.

Tested on: Mac - Chrome Version 74.0.3729.131, Mac - Safari Version 12.0.1

Screenshot:
![Screen Shot 2019-05-10 at 9 46 07 AM](https://user-images.githubusercontent.com/9931822/57531864-787e8180-7308-11e9-8d3e-e08504a825c5.png)

**Comment by EdenKupe** [comment]
Thank you Scott,

This should work now. Feel free to re-open if needed.
