### ISSUE TITLE
Custom Third Party Bots - Link not rendering correctly

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#313]
Page: https://developers.liveperson.com/bot-connectors-custom-third-party-bots.html

Bug: Link not rendering correctly

Detail: In the [Integrating Custom Bots Section](https://developers.liveperson.com/bot-connectors-custom-third-party-bots.html#integrating-custom-bots-via-messaging), there is a link to the Messaging Agent SDK that is not rendering correctly.

Image: 
![Screen Shot 2019-05-10 at 9 55 35 AM](https://user-images.githubusercontent.com/9931822/57532595-ef684a00-7309-11e9-8046-09573485457b.png)

**Comment by EdenKupe** [comment]
Fixed, thank you!
