### ISSUE TITLE
&para will inject a special character

### ISSUE THREAD

**Issue by jwang84** [LivePersonInc/developers-community#32]
If you use "&para" in the data text, the command method will inject a special character instead:

cmdName = lpTag.agentSDK.cmdNames.write; // = "Write stuff"
data = {text: '&para test &param test & param'};
lpTag.agentSDK.command(cmdName, data, notifyWhenDone);

If you simply use "&" symbol or the "&amp;" code, that will work. No problems there. It's only if you use "&para" that will inject the "¶" symbol. I've attached a screenshot.
![para test bug](https://user-images.githubusercontent.com/944876/29832838-81815886-8cb7-11e7-8034-2574c35ed547.png)

**Comment by jwang84** [comment]
Current work around is to change all your code that contain the line "&para" and replace it with "&amp;para"

**Comment by EdenKupe** [comment]
Thanks for reporting this, I'll forward this to the right people as a bug report. Feel free to reopen the issue if you have any more questions.
