### ISSUE TITLE
Several typos in "Agent Messaging API"

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/developers-community#320]
https://developers.liveperson.com/agent-int-api-reference.html#section/Happy-Flow
"username and password"
https://developers.liveperson.com/agent-int-api-reference.html#tag/Conversation%2Fpaths%2F~1subscribeExConversations%2Fjs
"in the metadata"
https://developers.liveperson.com/agent-int-api-reference.html#tag/Conversation%2Fpaths%2F~1updateConversationField%23participants%2Fjs
"in a conversation"
https://developers.liveperson.com/agent-int-api-reference.html#tag/Conversation%2Fpaths%2F~1updateConversationField%23participants%2Fjs
"when the newly assigned"
https://developers.liveperson.com/agent-int-api-reference.html#tag/infra%2Fpaths%2F~1getClock%2Fjs
"cannot use"

**Comment by EdenKupe** [comment]
Fixed, thanks.
