### ISSUE TITLE
Conversation Builder functionality documentation

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#327]
1)
https://developers.liveperson.com/conversation-builder-conversation-builder-conditions.html

The document lists 4 ways to match a phrase in conversation builder but there is a new 5th way called "Evaluate Options". I don't know how it works since it is not in the docs.

![image](https://user-images.githubusercontent.com/25583661/59022420-a393bc80-8845-11e9-9497-88ff925277cf.png)

2)
https://developers.liveperson.com/conversation-builder-getting-started-2-intents.html

There is a list of words (called stop words) that are ignored by CB when testing phrases agains intents. It is critical that brands understand this as it completely changes how training phrases are understood. The CB team should be able to provide this list.

**Comment by EdenKupe** [comment]
Hey @trosel can you take a look at this please?

**Comment by trosel** [comment]
@lp-tattwell 

what its supposed to do is handle if you have options like 

* A) One
* B) Two

If the user says "a" or "one" or "A one" it will return the original option "A) One"

We are investigating if this works as intended at this moment though.

**Comment by lp-tattwell** [comment]
That's how I think it works but i'm not 100% sure of the exact details. i would love to know your findings from your tests.

**Comment by trosel** [comment]
@peterswimm @mferreira-lp can you find any info on this?

**Comment by peterswimm** [comment]
Just got confirmation from the product team that you folks have it correct, the one trick is that you should set it to evaluate options and then don't put anything in the box for it to work.

**Comment by mferreira-lp** [comment]
Evaluate Options is documented here: https://developers.liveperson.com/conversation-builder-interactions-configuration-next-action.html#conditions

Stop words are documented here: https://developers.liveperson.com/conversation-builder-best-practices-train-tune-nlu.html#nlu-stop-words
