### ISSUE TITLE
Update documentation to reflect deprecated botcentralai.com

### ISSUE THREAD

**Issue by kohcheek** [LivePersonInc/developers-community#333]
Since botcentralai.com will be deprecated and we're pointing to developers/users to our sites to get tutorial on how to use Conversation Builder, will need to replace with updated domain name.
eg.
In tutorials and guides on the Conversation Builder" from :
https://developers.liveperson.com/conversation-builder-getting-started-1-dialogs-and-patterns.html
there is "....navigate to https://platform.botcentralai.com, enter your credentials, select your region, and log in."

There are other places which mention botcentralai.com
eg
https://developers.liveperson.com/conversation-builder-getting-started-3-integrations.html
https://developers.liveperson.com/custom-third-party-bots.html

**Comment by EdenKupe** [comment]
@trosel let me know if you have capacity to handle this. Otherwise, I'll pick it up myself.

**Comment by EdenKupe** [comment]
@trosel did we fix this?

**Comment by EdenKupe** [comment]
We're checking with the Mountain View team on which links need to be updated. It's not all of them.

**Comment by mferreira-lp** [comment]
References have been updated. A search on "botcentralai" no yields no hits.
