### ISSUE TITLE
Agent Handoff documentation outdated

### ISSUE THREAD

**Issue by davidres17** [LivePersonInc/developers-community#335]
https://developers.liveperson.com/conversation-builder-getting-started-4-connect-to-liveengage.html#step-12-transfer-from-bot-to-human

This guide details the "old" method for transferring a conversation to a human agent in CB.
There is a not integration function for LivePerson Agent Handoff that is not documented yet - please update ASAP.

**Comment by EdenKupe** [comment]
@trosel can you take a look?

**Comment by EdenKupe** [comment]
@trosel are we on top of this?

**Comment by trosel** [comment]
This is done
