### ISSUE TITLE
iOS docs outdated

### ISSUE THREAD

**Issue by fgifford-liveperson** [LivePersonInc/developers-community#339]
1. In https://developers.liveperson.com/mobile-app-messaging-sdk-for-ios-quick-start.html
> let conversationViewParams = LPConversationViewParams(conversationQuery: conversationQuery, isViewOnly: false)

But according to XCode: 

>'init(conversationQuery:containerViewController:isViewOnly:conversationHistoryControlParam:)' was deprecated in iOS 3.8.0: Use public init(conversationQuery: ConversationParamProtocol, containerViewController: UIViewController? = nil, isViewOnly: Bool = false, conversationHistoryControlParam: LPConversationHistoryControlParam = LPConversationHistoryControlParam(historyConversationsStateToDisplay: .none), welcomeMessage: LPWelcomeMessage = LPWelcomeMessage(message: nil)) instead

2. In https://developers.liveperson.com/mobile-app-messaging-sdk-for-ios-sdk-apis-monitoring-api.html#getengagement the parameter documentation is wrong: it's a copy/paste of the parameters for sendSDE.

**Comment by EdenKupe** [comment]
@randymclainLP can you take a look at this please?

**Comment by EdenKupe** [comment]
1. Is being worked on internally, a fix is coming.

2. I've been informed by Randy that these two methods are almost exactly the same and that there's no error.

**Comment by fgifford-liveperson** [comment]
>     2\. I've been informed by Randy that these two methods are almost exactly the same and that there's no error.

This line is wrong: https://github.com/LivePersonInc/developers-community/blame/master/pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/Methods/monitoring%20methods.md#L43 it is a copy/paste of this line: https://github.com/LivePersonInc/developers-community/blame/master/pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/Methods/monitoring%20methods.md#L80.

The non-deprecated version of getEngagement is not identical to the deprecated version; it takes an identities parameter and not a consumerId parameter.

**Comment by EdenKupe** [comment]
Will relay this to Randy.

**Comment by randymclainLP** [comment]
This is helpful.. I'll add this to my pull request.  Thanks for the clarification.  Cheers.

**Comment by randymclainLP** [comment]
@EdenKupe  can we close this issue?

**Comment by EdenKupe** [comment]
Certainly
