### ISSUE TITLE
Error response when attempting to call Summary method in Agent Metrics API

### ISSUE THREAD

**Issue by MikeTMO** [LivePersonInc/developers-community#34]
I'm receiving an error response when attempting to call Summary method in the Agent Metrics API. I'm am making the call via Postman.

**Response:**
{
    "code": "0013",
    "debugMessage": "Invalid json format"
}

**Request:**
POST /messaging_history/api/account/62258097/agent-view/summary?oauth_consumer_key=7b8d42389f714d878b0a169120b90527&amp;oauth_token=06166f21a18649719666e1ed862cdc82&amp;oauth_signature_method=HMAC-SHA1&amp;oauth_timestamp=1504033528&amp;oauth_nonce=c73KBU&amp;oauth_version=1.0&amp;oauth_signature=8Fr4DI1t0zK4Ovq6H43M17Sg8G4= HTTP/1.1
Host: va.msghist.liveperson.net
Content-Type: application/json
Authorization: OAuth oauth_consumer_key="7b8d42389f714d878b0a169120b90527",oauth_token="06166f21a18649719666e1ed862cdc82",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1504109758",oauth_nonce="8TNwnT",oauth_version="1.0",oauth_signature="pIXjyOoyP9vypApTOdQbYwY3QUI%3D"
Cache-Control: no-cache
Postman-Token: 9c4e5b40-4042-bfc3-7b4c-3d107d8b9dd9

**Comment by EdenKupe** [comment]
Thanks Mike!

I'll make sure to send this to the right Product Manager for review.

**Comment by orenkatz** [comment]
@MikeTMO try adding an empty JSON object to the body, for example: `{ }`

**Comment by MikeTMO** [comment]
@orenkatz That worked! Thank you

**Comment by EdenKupe** [comment]
Closing the issue, thaks for your time Mike!
