### ISSUE TITLE
Conversation Builder - Knowledge base docs don't tell you how to integrate into bot

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#371]
https://github.com/LivePersonInc/developers-community/blob/master/pages/documents/BotsAndAutomation/ConversationBuilder/KnowledgeBase/knowledgecenteroverview.md

The document covers how to create a knowledge base, however, doesn't say how to actually use it in a bot. The documentation doesn't cover how to create a KB integration. It is straight forward but a picture or two would really help.

**Comment by EdenKupe** [comment]
@trosel did you see this?

**Comment by trosel** [comment]
We intend on beefing this section up, yes! I'll leave this open until we do.

**Comment by EdenKupe** [comment]
@mferreira-lp can you look into creating this new document/enhancing the existing one?

**Comment by mferreira-lp** [comment]
Hi! A draft of this is in the works; I will see if I can expedite its release based on this inquiry.

**Comment by trosel** [comment]
>FWIW You can see this covered here: https://developers.liveperson.com/conversation-builder-templates-simple-faq.html

As a start, this could be linked in the KB doc

**Comment by mferreira-lp** [comment]
This documentation has been published; see here: https://developers.liveperson.com/conversation-builder-integrations-knowledge-base-integrations.html
