### ISSUE TITLE
CB broken image links

### ISSUE THREAD

**Issue by fgifford-liveperson** [LivePersonInc/developers-community#372]
The images on https://developers.liveperson.com/pages/documents/BotsAndAutomation/Tips_and_Tricks_v2.2.html#how-do-i-get-the-bot-to-close-the-conversation come from broken links, i.e. I get 404 for this and all images on this page: https://developers.liveperson.com/pages/documents/BotsAndAutomation/img/ConvoBuilder/BestPractices/image_0.png.

**Comment by trosel** [comment]
That document is not complete and not ready to view on the website.

**Comment by trosel** [comment]
@fgifford-liveperson was wondering where the  words `LP_CLOSECONVERSATION` came from, searched the website and found this unfinished doc

https://developers.liveperson.com/pages/documents/BotsAndAutomation/Tips_and_Tricks_v2.2.html#how-do-i-get-the-bot-to-close-the-conversation

We should either fix up this document or explain this elsewhere:

* Create text interaction with the special string `LP_CLOSECONVERSATION`

@jaltschuler

**Comment by jaltschuler** [comment]
That tips and tricks document should be removed from the website and replaced with actual documentation.

**Comment by trosel** [comment]
deleted.
