### ISSUE TITLE
Conversation Builder Stop words have been updated

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#379]
The CB team has updated the stop words for all accounts, here are the updated lists.

**Current Stop:**
"a","about","again","against","all","am",
"an","and","any","are","aren't","as","at","be","because","been","being","both","but","by","can't",
"can", "cannot","could","couldn't","did","didn't","do","does","doing","don't","during","each","for","from","further",
"had","hadn't","has","hasn't","have","haven't","having","he","he'd","he'll","he's","her","here","here's","hers","herself","him",
"himself","his","how","how's","i","i'd","i'll","i'm","i've","if","in","into","is","isn't","it","it's","its","itself","let's","me",
"more","most","mustn't","my","myself","no","nor","of","on","once","only","or","other","ought","our","ours","ourselves",
"shan't","she","she'd","she'll","she's","should","shouldn't","so","some","such","than","that","that's","the",
"their","theirs","them","themselves","then","there","there's","these","they","they'd","they'll","they're","they've","this","those",
"through","to","too","very","was","wasn't","we","we'd","we'll","we're","we've","were","weren't","what","what's",
"when","when's","where","where's","which","while","who","who's","whom","why","why's",
"with","won't","would","wouldn't","you","you'd","you'll","you're","you've","your","yours","yourself","yourselves”,

**Stop words that have been removed:**
"above","after","before","below","between","down","few","off","out","over","own","same","under","until","up”,

**Comment by trosel** [comment]
Where should this be documented? @jaltschuler

**Comment by trosel** [comment]
@lp-tattwell  @jaltschuler  Update: just found these listed here https://developers.liveperson.com/conversation-builder-best-practices-training-and-tuning-your-intents-and-faqs.html#nlu-stop-words

@lp-tattwell should I change this to be formatted like you have it? Is it easier if they have commas and such?

**Comment by lp-tattwell** [comment]
Nah, keep the format as it currently is in developers.

**Comment by trosel** [comment]
Done. This will be pushed at the end of the week with other changes from tips and tricks doc.

**Comment by EdenKupe** [comment]
@trosel was this pushed?

**Comment by trosel** [comment]
@EdenKupe yep! https://developers.liveperson.com/conversation-builder-best-practices-training-and-tuning-your-intents-and-faqs.html#nlu-stop-words
