### ISSUE TITLE
Zendesk Integration guide incorrect

### ISSUE THREAD

**Issue by tblevins** [LivePersonInc/developers-community#393]
The document  https://s3-eu-west-1.amazonaws.com/ce-sr/CA/CRM+Integration+Guides/Zendesk+Integration+Guide.pdf   is incorrect on page 15 it says that you can't create a new ticket.  You can create a new ticket when you link the conversation to the found customer within Zendesk -- please see the following video to see how it's done:::  https://drive.google.com/file/d/1McyMC8iA6n7RyH3J5QoS1WdyWaVgtP-e/view?usp=sharing

**Comment by EdenKupe** [comment]
We're working on updating all of these documents. More info soon.
