### ISSUE TITLE
Suggestion to include date in request example in Audit Trail API

### ISSUE THREAD

**Issue by Sergeyp52** [LivePersonInc/developers-community#398]
Customers who are not familiar with graphQL might have issues running the API call since it's a bit different from the regular format we're using for API calls.

Suggest replacing the current request example with the one below which contains date:

{"query" : "{auditData (fromDate:"2019-07-16" toDate:"2019-07-17")
{accountId
objectType
objectName
actionType
element
oldValue
newValue
changeDate
originator
originatorLoginName
originatorUserId
originatorUserAgent
originatorAuthType
originatorIsLpa}}"}

The current example exists in https://developers.liveperson.com/audit-trail-api-methods-retrieve-audit-trail-records.html under "Request body"

**Comment by EdenKupe** [comment]
Thanks! I've updated the example.
