### ISSUE TITLE
Literary quotes in MI API documentation break JSON

### ISSUE THREAD

**Issue by Sergeyp52** [LivePersonInc/developers-community#399]
In the document about Messaging Interactions API, there are examples for requests where the quotation marks in the filters examples are curly (literary) and not straight, which breaks JSON if someone tries to copy them as an example.

Look under "Filters examples" on https://developers.liveperson.com/messaging-interactions-api-methods-conversations.html.

Copy one of the examples into Postman and you'll see that the quotes are curly. This might not be the only API where there is this issue.

**Comment by EdenKupe** [comment]
Fixed
