### ISSUE TITLE
Retrieve mistyped in documents.html

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#40]
![chrome_2017-09-12_15-51-01](https://user-images.githubusercontent.com/29775347/30329332-487fd7ee-97d2-11e7-8f2c-5dac20a083ee.png)
source: https://developers.liveperson.com/documents.html
(_could not find the source to create a pull request_)

**Comment by EdenKupe** [comment]
Fixed, thank you!
