### ISSUE TITLE
LiveDeflect API documentation doesn't appear in the table to contents

### ISSUE THREAD

**Issue by Sergeyp52** [LivePersonInc/developers-community#400]
We have documents on LiveDeflect on the website but you can't actually find them using the table of contents. The only way to find them is via search one by one.
Example: https://developers.liveperson.com/livedeflect-api-getlivedeflectdata.html#request
At the top, the path to the documentation is shown as
Messaging Channels>LiveDeflect>APIgetLiveDeflectData
In reality, we don't have the LiveDeflect subsection in Messaging Channels

**Comment by EdenKupe** [comment]
These are not officially live yet. I've been trying to chase down their owners for a while now but received no response.
