### ISSUE TITLE
Visitor chat ends unexpectedly

### ISSUE THREAD

**Issue by devin-liu** [LivePersonInc/developers-community#43]
I have a logged in session with an agent through my custom client  `www.<myagentportal>.com` I refresh the agent login with the correct CSRF and get empty body responses back (OK for refresh). However when visitors talk for about 16 minutes, they get dropped randomly. I opened up a test visitor window in this url
`https://livepersoninc.github.io/visitor-page/?siteid=<siteid>`
I chatted for 16 minutes with my logged in session. The window all of a sudden loses ability to move. I can type in the chat, but cannot send the message. This is an error code I found in the browser window.
```
{
"error": {
"time": "2017-09-13T15:13:38.938-04:00",
"message": "Bad authorization request. general_problem=unknown_authorization_type&general_problem_advice=unknown authorization type received",
"internalCode": 5
}
}

```

Just to be clear, this is on the visitor side, not the agent side. How can the visitor lose OAUTH access randomly? Is it something that the agent portal client needs to manage or can break?

**Comment by EdenKupe** [comment]
Hey Devin,

This seems like an issue for Support first and foremost and only then for us. It doesn't seem like there's an issue with the documentation or the API itself but rather something wrong with the implementation. Could you speak with them and see if there's any insight on their end? If this is indeed an issue with the methods themselves, they can roll this back to me.

Thanks! Closing the issue for now, feel free to reopen.

**Comment by devin-liu** [comment]
I have the agent refresh running every 5 minutes and it never fails. When a new visitor comes in, the chat session is opened fine. However, chat sessions cannot seem to persist longer than a certain time period. Is there any way to force a visitor session to stay open?
