### ISSUE TITLE
resolveConversation completion callback

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#434]
https://developers.liveperson.com/mobile-app-messaging-sdk-for-ios-sdk-apis-messaging-api.html#resolveconversation

The docs suggest that resolve conversation has a completion callback but that doesn't seem to be the case. Is this here in error? Should the document show:

`func resolveConversation(_ conversationQuery: ConversationParamProtocol)`

**Comment by EdenKupe** [comment]
@zhaowenzhi-lp can someone from your team review this please?

**Comment by trosel** [comment]
@randymclainLP

**Comment by EdenKupe** [comment]
Does the documentation mention that it was deprecated? If not, we might want to add that.
