### ISSUE TITLE
Campaign Info Table is misaligned

### ISSUE THREAD

**Issue by mwashburn91** [LivePersonInc/developers-community#436]
If you go to the Campaign Info table, you will see that the first 2 columns were shifted to the right and the Type/Value information is missing.

The monitoring section is like that too.

**Comment by trosel** [comment]
It's this one https://github.com/LivePersonInc/developers-community/blob/master/pages/documents/HistoricalData/MessagingInteractionsAPI/methods/conversations.md

**Comment by EdenKupe** [comment]
Thanks, the formatting on those tables was all wrong. I've fixed it.
