### ISSUE TITLE
Agent Workspace Widget SDK / send notification example - what are the data payload options?

### ISSUE THREAD

**Issue by johnbeadle** [LivePersonInc/developers-community#44]
https://developers.liveperson.com/agent-workspace-sdk-methods.html#command

Example 3: 

```js
{
    var notifyWhenDone = function(err) {
        if (err) {
            // Do something with the error
        }
        // called when the command is completed successfully,
        // or when the action terminated with an error.
    };

    var cmdName = lpTag.agentSDK.cmdNames.notify; // = "Send Notification"
    var data = {};

    lpTag.agentSDK.command(cmdName, data, notifyWhenDone);
}
```

What are the possible values for `data {}` to construct the notification please?

**Comment by EdenKupe** [comment]
Thanks John, I've sent this query to the relevant product manager and will update as soon as I have a reply.

**Comment by EdenKupe** [comment]
Hey John,

Got this reply from R&D:

"The data field is for backward compatibility with the "lpTag.agentSDK.command" command.
It's not in use currently, and we will ignore whatever you will send there.
The notification will show automatically the text as documented. (user name, widget name and etc.)"

Let me know if you have any further questions or if we can close this issue. Thanks!

**Comment by johnbeadle** [comment]
@EdenKupe I don't understand - are you saying there is no way to configure the contents of notification sent by the widget?
In my tests so far I see a generic message when I raise a notification like this:

![screen shot 2017-09-20 at 17 48 13](https://user-images.githubusercontent.com/10999907/30818981-2ab5bff6-a215-11e7-8629-ca939673dba7.png)

it shows as

> new event in i2

is this not configurable?

**Comment by orenkatz** [comment]
@johnbeadle correct, it will show the name of the widget, in your case 'i2'
