### ISSUE TITLE
Question about how Jekyll handles embedded images

### ISSUE THREAD

**Issue by peterswimm** [LivePersonInc/developers-community#446]
I noticed that we are building the docs with HTML image tags, which Jekyll builds into the resulting docs website. Can I also use Markdown image embed syntax? This way it would render properly when reviewing a pr on the GitHub preview renderer.

**Comment by trosel** [comment]
The images only properly display after you build the site. So the images won't show on github

**Comment by peterswimm** [comment]
Right, but if we could do a markdown conversion in the build process, it would work everywhere? This is maybe a feature request?
