### ISSUE TITLE
Agent Workspace SDK / cmdNames.notify does not exist

### ISSUE THREAD

**Issue by johnbeadle** [LivePersonInc/developers-community#45]
https://developers.liveperson.com/agent-workspace-sdk-methods.html#command

```js
 var cmdName = lpTag.agentSDK.cmdNames.notify; // = "Send Notification"
```

![screen shot 2017-09-19 at 12 41 54](https://user-images.githubusercontent.com/10999907/30590778-05f95088-9d38-11e7-80b5-2ae3509bc5b0.png)

**Comment by orenkatz** [comment]
@johnbeadle we will check it, meanwhile, you can set cmdName to "Send Notification" instead
