### ISSUE TITLE
FB Rich Content - Doesn't say google maps doesn't work on browser messenger

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#450]
https://developers.liveperson.com/facebook-messenger-templates-introduction.html

The document says:

> Facebook Messenger desktop clients use an iframe to display the web links. Your brands website will need to support iframes in order for the consumer to be able to view it from FB desktop.

What it doesn't call out is that google **_doesn't_** support iframes so google maps etc will never work on desktop. We just need a sentence pointing this out as brands need to take this in to consideration when building out their content.

**Comment by trosel** [comment]
Thanks! Here's the actual doc that needs updating https://github.com/LivePersonInc/developers-community/blob/master/pages/documents/RichMessaging/FacebookMessengerTemplates/Introduction.md

Or maybe add it in Limitations https://github.com/LivePersonInc/developers-community/blob/master/pages/documents/RichMessaging/FacebookMessengerTemplates/Limitations.md

**Comment by trosel** [comment]
@lp-tattwell Thanks for reporting! This should solve it https://github.com/LivePersonInc/developers-community/commit/59d6161761060275991e0fdf987d78c69c9fbbc5
