### ISSUE TITLE
Chat Agent API - Agent Survey Issues

### ISSUE THREAD

**Issue by Manegoldsr21** [LivePersonInc/developers-community#47]
I have been having two issues with the Chat Agent API related to dealing with the Agent Survey.

1) It appears that when I retrieve the agent survey it is returned the default survey on the account not the survey assigned to the campaign that the chat is under.

https://developers.liveperson.com/agent-retrieve-survey-structure.html

2) When submitting the survey I need to use a data object that is different then the what is listed in the documentation. In the documentation it says that you just need to provide a question & answer but actually you need to wrap that in a survey object. 

Once I got around that I am still running into an issue where I am getting an error 'An unknown question id was posted: 0'. I am using a question.id that I got off the response from Retrieve Agent Survey Structure method though so I am not sure how it would be invalid.

https://developers.liveperson.com/agent-submit-survey.html

Object I am posting:

 {
     "survey" : {
        "question" : question.id,
        "answer" : answer
    }
 }
 
Let me know if you need anymore information about either of these issue. Thanks!

**Comment by EdenKupe** [comment]
Hey,

Thanks for opening this issue. 

1) Regarding your first question: is there anything that leads you to believe that that feature is supported? It might be that you can't retrieve a survey for a specific campaign but if you can point me to why you think that's possible, I can check.

2) Thanks. I'll work with the owner of the document to correct the documentation. 

As for the error, I'll send this over to Dev Support and see if they have any insight. I'll keep you updated on what they say.

Thanks!

**Comment by Manegoldsr21** [comment]
Nothing specifically stated that it would return the survey for the campaign/sessions but the fact that I have to pass in the chatId to the URL to get the survey, I assumed that it would return the correct agent survey for that chat.

https://{domain}/api/account/{accountId}/agentSession/{agentSessionId}/chat/{chatId}/survey?v=1&NC=true

**Comment by orenkatz** [comment]
@Manegoldsr21 to submit the agent survey, your JSON should look similar to this:
`
  "survey": {
                        "question": [
                            {
                                "id": "4550780",
                                "answer": "Tech Support"
                            },
                            {
                                "id": "4587702",
                                "answer": "No"
                            }
                        ]
                    }

`

**Comment by orenkatz** [comment]
@Manegoldsr21 We are closing this issue, please let us know if the solution did not work
