### ISSUE TITLE
JS Chat SDK not compatible with HTTP/2 or in Chrome 60

### ISSUE THREAD

**Issue by vkedwardli** [LivePersonInc/developers-community#48]
According to **RFC 7230** (HTTP/1.1):

> Each header field consists of a **case-insensitive** field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

Also, **RFC 7540** (HTTP/2):

> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion.

> However, **header field names MUST be converted to lowercase** prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6)

Since HTTP headers should be treated as case-insensitive, but the current V3 JS API 2.0.2. has hard-coded `c.headers.Location` with a capital letter L in the comparison statement `if (c && c.headers && c.headers.Location) {`

This breaks Google Chrome version >= 60 since it is the first browser to fully adapt to HTTP/2 (see [discussion](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/_oxlCPNsrck) and [changelog](https://chromium.googlesource.com/chromium/src/+/99c274ae8e7d366261dcfb89e0b98e733fb9d5f4)), all HTTP headers are in lowercase now.

**Comment by EdenKupe** [comment]
Hey,

@miki2826 can you take a look at this? Can we fix that capital letter to comply with HTTP/2? 

Thanks!

**Comment by miki2826** [comment]
Hi @EdenKupe @vkedwardli,
It was already fixed in the current version.

Thanks,
Miki.

**Comment by vkedwardli** [comment]
@miki2826 Oh, so there isn't a version bump for this release? The first thing I checked is the version number (still `2.0.2`) and the release notes (No new changes have been made to this SDK documentation recently)
