### ISSUE TITLE
Messaging interactions API example response issues

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developers-community#487]
https://developers.liveperson.com/messaging-interactions-api-methods-conversations.html#response
Two issues:
1) The example response does not include all possible fields. For example, skillchanges is missing from the example.
2) The document mentions the "consumerParticipants" array as the array of consumer participants however, the example response has it as "consumerParticipant" (singular instead of plural). This is confusing to clients.

Thanks

**Comment by EdenKupe** [comment]
Sending this to the owner of the API.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)

**Comment by amirmLP** [comment]
Hi @j9t ,
The typo issue ("consumerParticipant" instead of "consumerParticipants") is fixed.
The example response is still missing some of the possible content.
I believe the example data we give in the documentation should include all possible data points so that brands would know what to expect when calling the API.
