### ISSUE TITLE
Agent SDK greeting example can't connect (503 error)

### ISSUE THREAD

**Issue by jminuscula** [LivePersonInc/developers-community#49]
Hi there!

I'm trying to run the Greeting Bot example found in https://github.com/LivePersonInc/node-agent-sdk/blob/master/examples/greeting-bot.js

I've set up my account with an Agent and I'm running the example with its credentials, but I can't get it to connect. This error is thrown when instantiating the Agent:

```
Error: unexpected server response (503)
    at ClientRequest.response (/Users/jacobo/reply/liveperson-proxy/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
```

If I provide wrong credentials, it fails expectedly with `could not generate token`.

What am I missing? Thanks!

**Comment by orenkatz** [comment]
Hey @jminuscula,
How are you creating the new Agent? are you changing the csdsDomain? If so, you need to leave it blank so it will use the default one.
Oren.

**Comment by jminuscula** [comment]
I'm creating the Agent from the LiveEngage dashboard. I've assigned it the `Agent` role, and created a `Test` skill for it. I've also set the max number of chats to unlimited.

I'm not providing a value for `csdsDomain`.

thanks for the help @orenkatz!

**Comment by jminuscula** [comment]
Since the code is extremely simple, I'm guessing the problem might be with my account?

I'm not very familiar with the differences between Chat API and Messaging, but from the documentation and samples, it looks like Messaging is the way to go for bot automation. The usecase is simply building an Agent that can take care of a customer conversation.

Maybe my account needs to be enabled for this?

Thanks again!

**Comment by orenkatz** [comment]
@jminuscula  Can you email me your site number (orenk@liveperson.com)? it's possible that your site is not configured for messaging and only for Chat and the sample that you are trying to use is for messaging.
We have a different one for Chat

**Comment by jminuscula** [comment]
My account was not enabled for Messaging, only for Chat. Closing this issue.

thanks for the help @orenkatz 👍

**Comment by torloneg** [comment]
hello
I have the same problem, with a trial account that I'm using to evaluate the service
can I send my account to verify?

**Comment by donmanguno** [comment]
Sure, send it to mmanguno@liveperson.com

**Comment by komalkr** [comment]
Hi 
I am also getting that Error: unexpected server response (503). i also know that my account is not enable for async_messaging feature . So , How can i run this node-sdk-agent-manger main.js code ?
i am also using 'adminlogin.liveperson.net' as my csdsDomain . and it is fetching all baseUri. should i change my csdsDomain if yes then how can i get my csdsDomain ?

**Comment by donmanguno** [comment]
For anyone having this issue:

- You need a messaging-enabled account to use this code. If you don't have one, speak to your LivePerson account team, and if you don't have one of those, speak to our Sales department.

- Do not set any value for cdsDomain unless told otherwise by someone from LivePerson

**Comment by MengjiaoZhou** [comment]
where do I check if my account is messaging-enabled? I create a developer account and login, can't find anywhere to check account property.

**Comment by EdenKupe** [comment]
Hey @MengjiaoZhou!

Eden here, I manage the Developers' Community. The developer accounts are not enabled for messaging out of the box. Can you please share your account number with me so I can see if I can enable that for you?

Thanks!

**Comment by lpbarber** [comment]
Hi @MengjiaoZhou! 
I have activated Messaging on your account.

**Comment by b4ck3r** [comment]
Hey @EdenKupe and @donmanguno,

Would you mind, activating messaging in my account too, please?

Thanks in advance,

Regards,

Cleb

**Comment by EdenKupe** [comment]
Hey,

Can I ask for your account number?

**Comment by b4ck3r** [comment]
Hey @EdenKupe, 

My account number is: 14437938

Thank you.

**Comment by EdenKupe** [comment]
Hey,

Messaging is now enabled on your account. Let me know if you need anything else.

Thanks!

**Comment by b4ck3r** [comment]
Hey,

Thanks man, everything seems to run smoothly now.

Thanks again.

**Comment by kanchanmishra** [comment]
Hi.... I'm using com.liveperson.android:lp_messaging_sdk:3.2.0. and getting following error:

E/Liveperson **ConnectionStateMachine_ConnectingState**: Connection task OPEN_SOCKET failed Open Socket - CLOSED

Please can you check if my account is enabled for messaging?
33136087

Thanks in advance.

**Comment by orenkatz** [comment]
@kanchanmishra , We just enabled Messaging on your account, please check again.
Oren.

**Comment by kanchanmishra** [comment]
Thanks orenkatz. I can see more Connections and Messaging tabs in my account now. iOS sample App is connecting.

**Comment by joselllorente** [comment]
Hi @EdenKupe and @donmanguno,
Would you mind activating messaging in my account too, please?
My account number is: 47859597

Thanks in advance,
Regards,

Thank you.
