### ISSUE TITLE
Cluster example connects but agents don't come online

### ISSUE THREAD

**Issue by dennisnotojr** [LivePersonInc/developers-community#5]
Followed the cluster example from the node-agent-sdk-master, but I can't get the agents to appear online.

cluster comes up .....
app_1        | add 40683877-Watson
app_1        | add 40683877-Watson2
app_1        | connected... 40683877-Watson
app_1        | connected... 40683877-Watson2
app_1        | subscribed successfully 40683877-Watson
app_1        | subscribed successfully 40683877-Watson2

Check the online agents, User: Watson, Watson2 not online, don't show up in the online agent view.

Started a campaign with an engagement and a skill as "bot". Gave Watson,Watson2 agent the "bot" skill.

campaign button shows no agents available, "Leave a message" icon shows up on the live chat button.

Tried 10+ times. No Luck. Barring a configuration setting in LivePerson, I do not know what to do.

Followed the https://livepersoninc.github.io/node-agent-sdk/cluster.html to the letter, with no luck.

I have a developer's account, my account id is 40683877. I have opened several cases, but i can't see the case button to see the status.  

Thanks,

Den

**Comment by EdenKupe** [comment]
Hey Den,

Thanks for opening this issue. I'm forwarding this issue internally to the right people, will update you ASAP here when we have an answer/need more info.

Thanks again.

**Comment by dennisnotojr** [comment]
Please, 

Need to talk to some fast. I can't get your cluster demo working with my account. The agent never goes online even when the sdk connects and subscribes

Den

**Comment by eitan101** [comment]
Hi,

Does your campaign work for human messaging agents?
(The node-agent-sdk is messaging only).

Are you familiar with the differences between chat & messaging in LE?

**Comment by dennisnotojr** [comment]
Yes,

 

No 

 

The example does not work straight from the SDK. So I believe something is wrong in my account?  I need help

 

Den

**Comment by EdenKupe** [comment]
Hey Den,

If there's something wrong in your account, please contact our Support team via www.liveperson.com. I think they can assist you further on this issue. 

Thanks!

**Comment by dennisnotojr** [comment]
They have been no help. This example
Doesn't work. Need some to tell me
Why your get started instructions fail

Den

**Comment by dennisnotojr** [comment]
Tried different accounts no luck. Interesting that bots did connect a week ago, now receive the following errors to connect with no changes. Example of the new error

> docker-compose up -d && docker-compose logs -f app

Creating cluster_zookeeper_1
Creating cluster_app_1
Attaching to cluster_app_1
app_1        | add 40683877-Watson
app_1        | add 40683877-Watson2
app_1        | got an error Error: unexpected server response (503)
app_1        |     at ClientRequest.response (/code/node_modules/ws/lib/WebSocket.js:719:15)
app_1        |     at Object.onceWrapper (events.js:316:30)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at ClientRequest.emit (events.js:210:7)
app_1        |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
app_1        |     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
app_1        |     at TLSSocket.socketOnData (_http_client.js:453:20)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at TLSSocket.emit (events.js:210:7)
app_1        |     at addChunk (_stream_readable.js:252:12)
app_1        |     at readableAddChunk (_stream_readable.js:239:11)
app_1        |     at TLSSocket.Readable.push (_stream_readable.js:197:10)
app_1        |     at TLSWrap.onread (net.js:588:20)
app_1        | socket closed 1006
app_1        | got an error Error: unexpected server response (503)
app_1        |     at ClientRequest.response (/code/node_modules/ws/lib/WebSocket.js:719:15)
app_1        |     at Object.onceWrapper (events.js:316:30)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at ClientRequest.emit (events.js:210:7)
app_1        |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
app_1        |     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
app_1        |     at TLSSocket.socketOnData (_http_client.js:453:20)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at TLSSocket.emit (events.js:210:7)
app_1        |     at addChunk (_stream_readable.js:252:12)
app_1        |     at readableAddChunk (_stream_readable.js:239:11)
app_1        |     at TLSSocket.Readable.push (_stream_readable.js:197:10)
app_1        |     at TLSWrap.onread (net.js:588:20)
app_1        | socket closed 1006


Though it was an issue finding the domain, so I added
   "csdsDomain" : "va.agentvep.liveperson.net"

to the agents.json for a test and got this error
> docker-compose up -d && docker-compose logs -f app

Creating cluster_zookeeper_1
Creating cluster_app_1
Attaching to cluster_app_1
app_1        | add 40683877-Watson
app_1        | add 40683877-Watson2
app_1        | got an error Error: could not fetch domains
app_1        |     at MyCoolAgent._login (/code/lib/AgentSDK.js:81:22)
app_1        |     at SDK.async.waterfall (/code/lib/AgentSDK.js:39:41)
app_1        |     at nextTask (/code/node_modules/async/dist/async.js:5273:14)
app_1        |     at next (/code/node_modules/async/dist/async.js:5280:9)
app_1        |     at /code/node_modules/async/dist/async.js:906:16
app_1        |     at Request.request [as _callback] (/code/lib/ExternalServices.js:25:9)
app_1        |     at Request.self.callback (/code/node_modules/request/request.js:188:22)
app_1        |     at emitTwo (events.js:125:13)
app_1        |     at Request.emit (events.js:213:7)
app_1        |     at Request.<anonymous> (/code/node_modules/request/request.js:1171:10)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at Request.emit (events.js:210:7)
app_1        |     at IncomingMessage.<anonymous> (/code/node_modules/request/request.js:1091:12)
app_1        |     at Object.onceWrapper (events.js:314:30)
app_1        |     at emitNone (events.js:110:20)
app_1        |     at IncomingMessage.emit (events.js:207:7)
app_1        | got an error Error: could not fetch domains
app_1        |     at MyCoolAgent._login (/code/lib/AgentSDK.js:81:22)
app_1        |     at SDK.async.waterfall (/code/lib/AgentSDK.js:39:41)
app_1        |     at nextTask (/code/node_modules/async/dist/async.js:5273:14)
app_1        |     at next (/code/node_modules/async/dist/async.js:5280:9)
app_1        |     at /code/node_modules/async/dist/async.js:906:16
app_1        |     at Request.request [as _callback] (/code/lib/ExternalServices.js:25:9)
app_1        |     at Request.self.callback (/code/node_modules/request/request.js:188:22)
app_1        |     at emitTwo (events.js:125:13)
app_1        |     at Request.emit (events.js:213:7)
app_1        |     at Request.<anonymous> (/code/node_modules/request/request.js:1171:10)
app_1        |     at emitOne (events.js:115:13)
app_1        |     at Request.emit (events.js:210:7)
app_1        |     at IncomingMessage.<anonymous> (/code/node_modules/request/request.js:1091:12)
app_1        |     at Object.onceWrapper (events.js:314:30)
app_1        |     at emitNone (events.js:110:20)
app_1        |     at IncomingMessage.emit (events.js:207:7)


I about ready to give up and declare that liveperson is not stable for integration with bots and report this up to IBM. I have opened 3 cases with support and opened this issue on GitHub and its been a week with no ability to talk to a live person.  This is your example without modification and it does not work as advertised. I suggest you pull it or update the readme with instructions that work

Den

**Comment by dennisnotojr** [comment]
Once we get past the 503 error, then I will be back to my original issue of not seeing the bot agents go online. Buried in documentation I found this

**Note: In order to login as an application, you first need to have the "User Type - Bot" feature activated. Please contact your account team before moving forward.**

Don't know if that applies and support has not be helpful on this.

Den
