### ISSUE TITLE
GetClock example

### ISSUE THREAD

**Issue by kstrickland09** [LivePersonInc/developers-community#51]
In [Messaging Window API > Protocol Overview > Keep Alive](https://developers.liveperson.com/consumer-int-protocol-overview.html#keep-alive), the example code below returns "disconnected". Removing the period before "GetClock" returns a valid response.

`{"kind":"req","id":"1","type":".GetClock"}`

**Comment by EdenKupe** [comment]
Hey,

I've removed the period. Let me know if anything else needs doing.
