### ISSUE TITLE
Messaging Window API - Getting Started

### ISSUE THREAD

**Issue by kstrickland09** [LivePersonInc/developers-community#52]
In [Messaging Window API > Getting Started > Step 2](https://developers.liveperson.com/consumer-int-getting-started.html#step-2---create-a-token), the description after the command should be updated. Current version is:
> This will request the creation of a new identity. Extract the JWT from the response, and set it as a variable called LP_JWT in your shell. This new identity will be used in the next step.

There is a subtle but important difference with this proposed version, which clarifies that extracting the JWT is not a separate step but instead one of the actions performed by the command:

> This will request the creation of a new identity, extract the JWT from the response, and set it as a variable called LP_JWT in your shell. This new identity will be used in the next step.

**Comment by EdenKupe** [comment]
Hey,

I've updated the document with the new wording. 

Thanks!
