### ISSUE TITLE
Bancomer Movil - Push Notification issues SDK V2.7

### ISSUE THREAD

**Issue by refnandor** [LivePersonInc/developers-community#54]
These are the configurations about Push Notifications in our app (Bmovil) (lp account: 85237869):

1.- Add code lines in the class AppDelegate (application):

![image](https://user-images.githubusercontent.com/32464396/31100833-9def6410-a790-11e7-9315-cf6ce89f45f0.png)

![image](https://user-images.githubusercontent.com/32464396/31100842-aaa3677e-a790-11e7-90cb-e5bce4fffe0c.png)

2.- Enable push notification in the app:
![image](https://user-images.githubusercontent.com/32464396/31100893-d0fc5a5c-a790-11e7-8947-4ac9adafe676.png)

3.- Enabling the app in the LP console with the respective Bundle ID:

![image](https://user-images.githubusercontent.com/32464396/31100908-dca4cea2-a790-11e7-8e6c-638346abfe36.png)

4.- Uploading the developer certificates on the LP console and add the chain -DEV to the mobile app name:
![image](https://user-images.githubusercontent.com/32464396/31100918-ecbffdac-a790-11e7-9e8e-13ca38e289e4.png)

The push notifications are not working, can you please help us to find the problem?

Thanks

**Comment by EdenKupe** [comment]
@nirlachman-liveperson can you assist?

**Comment by EdenKupe** [comment]
Hey @refnandor, I think it would be best for you to contact Support for this issue. There's some debugging that needs to happen and they're the ones in charge of that. Please contact them via www.liveperson.com, just click to chat with them at the bottom right.

**Comment by dvillacis94** [comment]
Hi @refnandor which version of iOS are you using? also can you show the whole warning

**Comment by refnandor** [comment]
@dvillacis94 iOS 11

**Comment by dvillacis94** [comment]
if you could share the whole warning that would be great, meanwhile can we check that you actually have the right Certificates, and that the Notifications are functioning correctly on the APN, for this can you follow this instructions to test them, I understand that you're using Swift, the steps for Objective-C are the same:

Testing Push Notifications

It's important to make sure your Certificates are correct and everything is ready to Push Notifications from LiveEngage, to test add your device is ready, just follow this part.

From the App Store on your Mac, download the follwing App Easy APNs Provider
To get your Device Token, on your Xcode project, on the AppDelegate.swift file, locate the method didRegisterForRemoteNotificationsWithDeviceToken, and add the following:

    // Get Token & Parse it
    let token = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
    // Print Token
    print("Token:: \(token)")
Note: this should print the token on the Xcode Console, on the search field, just look for Token::

Launch **Easy APNs Provider** app:

1. Click on Add tokens, and add your Device Token,
2. Click on Choose Certificate File, and add your aps_development.cert file,
3. On Connect to: select gateway.sandbox.push.apple.com if you're using a Development Certificate,
**Note: On the Feedback status screen you should be able to see the Status Log, errors will be shown here.**
4. Click in Send APN
5. You should receive a Push Notification

**Comment by refnandor** [comment]
Thanks for your reply, I'm waiting for the results of this test

**Comment by refnandor** [comment]
Hey @dvillacis94. We tried but the Push notifications remain the same (not working). Can we have a debug session and see what the problem is?
Thanks

**Comment by orenkatz** [comment]
@refnandor before the debug session, can you please provide the results of the test using "Easy APNs Provider" like David suggested?
If it's not working, it means that the certificates used are incorrect or they are not the same certificates that were used to compile the App
You can use [this guide](https://developers.liveperson.com/consumer-experience-ios-sdk-createcertificate.html#creating-a-push-notification-certificate-der-format-crt-file) on how to create the certificates

**Comment by dvillacis94** [comment]
@refnandor I'm also noticing that your Certificate file and Key file are the same, you'll need to create 2 PEM files, please check @orenkatz guide on his comment

**Comment by orenkatz** [comment]
@refnandor did you manage to resolve the issue?

**Comment by orenkatz** [comment]
@refnandor we are closing this issue, please let us know if the solution we provided didn't help
