### ISSUE TITLE
Agent Workspace SDK / how to customise the notification message?

### ISSUE THREAD

**Issue by ericmm** [LivePersonInc/developers-community#540]
I'm trying to integrate the AgentSDK and I'm having some issue with customising the notification text. The link I'm referring to is https://developers.liveperson.com/agent-workspace-widget-sdk-methods.html#command

I followed the example below, it worked but the `data` is empty which showed a default message. 

```javascript
{
    var notifyWhenDone = function(err) {
        if (err) {
            // Do something with the error
        }
        // called when the command is completed successfully,
        // or when the action terminated with an error.
    };

    var cmdName = "Send Notification";
    var data = {};

    lpTag.agentSDK.command(cmdName, data, notifyWhenDone);
}
```

Then I tried `data = {text: 'test'}` and some others, and it did not work. 

Can you please let me know how I can customise the notification message? Thanks.

**Comment by j9t** [comment]
Hi @ericmm—thanks for the extreme patience here…! We’re going through all open issues, working to ensure (much faster) responses; please let us know if this is still relevant.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)
