### ISSUE TITLE
Missing service name for domains api for monitoring api

### ISSUE THREAD

**Issue by LPnsteenstra** [LivePersonInc/developers-community#555]
https://developers.liveperson.com/monitoring-api-overview.html

this page should include the service name for the domains api.  at the moment, there's no info for how to find the monitoring api domain

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)

**Comment by LPnsteenstra** [comment]
I just checked, and I found it in the "getting started" section, so it's
either fixed now or I was missing it before.  (It's usually in the overview
section.)
https://developers.liveperson.com/monitoring-api-getting-started.html

Thank you!!

On Mon, Jul 11, 2022 at 5:30 AM Jens Oliver Meiert ***@***.***>
wrote:

> @LPnsteenstra
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LPnsteenstra&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=j6uL9VkHNclsW3rnYFuypPBQdxl_Wf4XH03rPW9S40c&m=LDooC7jFDjAu9_VsXaLa8064Xw2Hd1buw4LteBi8ISqlxZEO7iju4tylBw9WMZRF&s=U6hBMdv2mcLvwFBWeHnVQxzPV8fn5wsgbHG32OddvtU&e=>,
> thanks for sharing this! Can you confirm with @itay1313
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_itay1313&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=j6uL9VkHNclsW3rnYFuypPBQdxl_Wf4XH03rPW9S40c&m=LDooC7jFDjAu9_VsXaLa8064Xw2Hd1buw4LteBi8ISqlxZEO7iju4tylBw9WMZRF&s=YVWmo2wfard_MHEM2ngUsGp8Pg363IiOic52YqP-rhg&e=>
> this is still a problem?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_555-23issuecomment-2D1180172208&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=j6uL9VkHNclsW3rnYFuypPBQdxl_Wf4XH03rPW9S40c&m=LDooC7jFDjAu9_VsXaLa8064Xw2Hd1buw4LteBi8ISqlxZEO7iju4tylBw9WMZRF&s=uyktJfgvhjUbGXbeV9HRwrG8pxkKsqbaA_EfC8cMDGE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMAW27EZCRQDU3P4KZLLPWDVTPSTFANCNFSM4LUTVKDA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=j6uL9VkHNclsW3rnYFuypPBQdxl_Wf4XH03rPW9S40c&m=LDooC7jFDjAu9_VsXaLa8064Xw2Hd1buw4LteBi8ISqlxZEO7iju4tylBw9WMZRF&s=KCNQBgtACRYdkP7TOTh-Qu4bJadgcil64gO8WCjMhRw&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

Nicholas Steenstra
Support Engr II

<https://pr.liveperson.com/2022-03-08-Fast-Company-names-LivePerson-the-1-Most-Innovative-AI-Company-in-the-World?utm_medium=email&utm_source=gmail&utm_campaign=signature&utm_content=2022FastCompany>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
