### ISSUE TITLE
Quick start guide still using SDK v4.3.2 rather than v5

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developers-community#559]
This is quite confusing as the rest of the documentation has been updated with the new methods but the quick start guide is out of date.

For example, the initialize method in v4 is used as:
initialize(final Context context, final String brandId, final InitLivePersonCallBack initCallBack)
whereas in v5 it is:
initialize(Context context, final InitLivePersonProperties initProperties)

The quick start guide still shows the v4 initialize method while the Messaging API's page shows the initialize method in its v5 version: 
https://developers.liveperson.com/mobile-app-messaging-sdk-for-android-sdk-apis-messaging-api.html#initialize-with-sdk-properties-object

**Comment by EdenKupe** [comment]
@Vam18 can you take a look at this please?

**Comment by j9t** [comment]
Hi @amirmLP, @EdenKupe, @Vam18—is this still relevant? (Was there work done to update the docs?)

**Comment by amirmLP** [comment]
Hi @j9t , this is fixed
