### ISSUE TITLE
[In-App Android SDK] Incorrect design attribute labeled

### ISSUE THREAD

**Issue by Hauuguu** [LivePersonInc/developers-community#56]
The first image labelled with a "1" [here](https://developers.liveperson.com/android-attributes-designsheet.html) doesn't match the attributes provided. Reproduced below:

![image](https://user-images.githubusercontent.com/14969006/31144693-7864f664-a84f-11e7-8086-b0c384efb032.png)

To change the default "My Brand" the attribute is `<string name="brand_name"></string>`, which can be found [here](https://developers.liveperson.com/android-modifying-string.html).

**Comment by EdenKupe** [comment]
Hey Josh,

Thanks for noticing this one. I've added the right attribute. In the future, I'm also looking into making this table more specific, by splitting up those numbers to make sure it's clear which attribute customizes which element.

Feel free to close this issue if you feel it's been addressed. Thanks again!
