### ISSUE TITLE
New Structured Contents: Maps

### ISSUE THREAD

**Issue by marcodagolini** [LivePersonInc/developers-community#57]
Hello!

It seems that the syntax explained in the documentation to visualize Maps with new structured contents is wrong.

Here below the correct one:

{
	"type": "map",
	"lo": 2323231312,
	"la": 313145,
	"click": {
		"metadata": [{
	        }],
		"actions": [{

		}]
	},
	"tooltip": "map tooltip"
}

So "lo" and "la" seem not to be strings, but numbers.

Again, "lo" and "la" is one ordered pair of number that identifies one position.
The correct order is "la" - "lo", not the vice-versa, this could bring misunderstandings.

Regards.

Marco Dagolini

**Comment by donmanguno** [comment]
We'll update the documentation accordingly. Thanks, Marco.
