### ISSUE TITLE
Unknown cookie appears when a conversation is started

### ISSUE THREAD

**Issue by vduilgerow** [LivePersonInc/developers-community#594]
Hello team, 

Hope you are well.  

There is a cookie called '_ga'  that is being set by the liveperson.net domain when a conversation is started  and there is no information available for it in the knowledge base:

https://developers.liveperson.com/cookies-and-liveengage-overview.html

Could you please have a look at adding information for it in the documentation when you have a moment. 

Many thanks.

![Cookie_001](https://user-images.githubusercontent.com/64085753/79885369-73beba80-83ff-11ea-8187-646870af5dff.jpg)

**Comment by vduilgerow** [comment]
Hey Jens,

All good, this is no longer relevant.

Many thanks,

On Mon, Jul 11, 2022 at 12:26 PM Jens Oliver Meiert <
***@***.***> wrote:

> Hi @vduilgerow
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vduilgerow&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=acCIaw8mHLKf0U1l5CSbdwakMxfupf5nfiHVuSEA0RM&m=ZhrJG6eMmlA1ykkYN84oUHwhmBUdYuzvsVDdxyf_E93szUsI6HgUxj4oGfHdWooT&s=eMSKEPnKRbdmrU9UI03txeiyn1VKi8qmoE2bpKo_ID8&e=>—thanks
> for the extreme patience here…! We’re going through all open issues,
> working to ensure (much faster) responses; please let us know if this is
> still relevant. (On scanning, this cookie looks related to Google
> Analytics, while the documentation covers LivePerson cookies.)
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_issues_594-23issuecomment-2D1180168857&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=acCIaw8mHLKf0U1l5CSbdwakMxfupf5nfiHVuSEA0RM&m=ZhrJG6eMmlA1ykkYN84oUHwhmBUdYuzvsVDdxyf_E93szUsI6HgUxj4oGfHdWooT&s=jJw2LVohYnuSWKfcHRtbtoNABFOZOwQzy96G-ofd8CQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_API556KPM4INRBLAT7VOV4TVTPSE7ANCNFSM53G263ZQ&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=acCIaw8mHLKf0U1l5CSbdwakMxfupf5nfiHVuSEA0RM&m=ZhrJG6eMmlA1ykkYN84oUHwhmBUdYuzvsVDdxyf_E93szUsI6HgUxj4oGfHdWooT&s=hEKeVEp4pKLFf1Ixkuxpvm_2B6irUCIdWVizEOxXDa4&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

Vasil Diulgerow
Shift Supervisor, Customer Service Department

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by j9t** [comment]
Thanks for confirming!
