### ISSUE TITLE
Engagement Attributes API - Chat AND Messaging

### ISSUE THREAD

**Issue by lp-wodell** [LivePersonInc/developers-community#6]
https://developers.liveperson.com/rt-interactions-engagement-attributes-engagement-attributes.html

The EAs API can be used for messaging as well as chat - in web messaging EAs can be used to determine which engagements show up.

**Comment by miki2826** [comment]
@lp-wodell, I don't see a reason to open issues on EA API in this repository since this repo handles only the messaging agent sdk.

Please take it with the relevant people.

Thanks,
Miki.

**Comment by EdenKupe** [comment]
Thanks, I've changed the indicators to reflect both chat and messaging!
