### ISSUE TITLE
wrong type in structured contents documentation

### ISSUE THREAD

**Issue by marcodagolini** [LivePersonInc/developers-community#62]
Hello Team

This documentation https://developers.liveperson.com/structured-content-templates.html contains one mistake.
The JSON defining the style here below...

"style": {
	"bold": true,
	"italic": true,
	"color": "#453533",
	"background-color": "#3E47A0",
	"size": small
}

...returns one error, "size" is a string.
So the correct JSON is:

"style": {
	"bold": true,
	"italic": true,
	"color": "#453533",
	"background-color": "#3E47A0",
	"size": "small"
}

Regards

Marco

**Comment by donmanguno** [comment]
Thanks for this feedback Marco. I have submitted a correction and it should appear soon.
