### ISSUE TITLE
Messaging Interactions API - {domain} is missing from the URL

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#65]
The example URL for the Messaging Interactions API is missing the {domain} part of the URL and is showing as:
https:///messaging_history/api/account/{accountID}/conversations/search?offset=0&limit=50

on the Messaging Interactions API pages.

Example page: 
https://developers.liveperson.com/data-messaging-interactions-conversations.html

![2017-10-27_1236](https://user-images.githubusercontent.com/9931822/32115104-853fd198-bb13-11e7-88b3-a25b7daa90ee.png)

**Comment by scottwestover** [comment]
I opened a pull request for this issue. #64

**Comment by orenkatz** [comment]
Thanks @scottwestover
