### ISSUE TITLE
How To Ingest Data From Liveperson With Python

### ISSUE THREAD

**Issue by ValAug** [LivePersonInc/developers-community#656]
How do you guys run this script? 

I created my AP key and authentication but I cannot find the way to run it. Thanking you in advance for your help.

```
Traceback (most recent call last):
  File "le.py", line 214, in <module>
    consumer_secret = sys.argv[1]
IndexError: list index out of range
```

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)
