### ISSUE TITLE
IDP problem / Failed to connect to the server

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#66]
one of our clients get's an error "Problem IDP" since last Thurday. Support [case ID: 00583344] redirected me here to get the best and fastest answers.

From the console, they get the following error:
```
globalAsyncEventsErrorCallback --> {"eventName":"LPMessagingSDKError","error":"idp url = https:\/\/lo.idp.liveperson.net\/api\/account\/62085844\/app\/default\/authenticate?v=2.0. Exception On Response Error :  response code: 500 body: {\"internalErrorCode\":\"9012\"}"}
```

They tested:
1)	Physical devices both android and iOS 
2)	All OS versions for example iOS – 9.3.4 , 10.3.1  Android - 6.0 , 6.0.1 etc

They use encrypted JWT:
```
eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0.leklJINaxuESu-nOPK8Kw6Tej6vitCtGlst4d8dGJa52zbX9F8of-I6yPrk_t63ZUgBGiWb1j5QkBpZU_DNNcLxAnj9MbfNNhGN7Nq7qLgPlhb2H6oDLJ5nAyKC8pRbLd2P79boQbO-I9JRv4PXMnI_fHoag4y2sOe1kUaGIL10.4LpManBcmlYx-xzAD2B8rQ.HcdgxAdhdPdTWTIrf0jaLpdMVSFVJz5SANKndZqnCuzlAkk3vuXBPgQ5eHV0agLOFOBqz-GVBHIp3mh30_lbpg0NVZ4AhoYiiKni-FoAqpH5kOIzJhOdLUNA2vrpDDj-8fj5ot-RXqXRqfkTV3oUSRrOZVt7xIJUK-HmDQ9U151Hw-uzvq3X8YQtb8n0BoXAPut83OC2BpsWbCDoNr5nPqJZTyhxHcfq2oTMb3ffTRBOoB5uEKoqtSXriHiq1J4XqTvv_Z5Yr-Rhh2Zb7KlCoudBMHDWCmuMzGX9dFxIV2Px2FlopBIB3i9zYjZZAPCSw8oIaLGd1AuWtyh7ig5fvoPOodCQJFM9HH5KYxM8FSaTLLqWnet_K6Mg0mR1AS0aR5W07EjwJMgCTzj0rAuygWIJFZTMWQ3SvLxAIXXfwsmRQbb6A4kRiwJ91TduBt1pGrbcBf8lIzxMsQZuzV_B9o-Xtxxhbqf7UhlJhZ7g51Y2CgYaJsA2Qk81xzL4iOxuTodxb-Axzmdc4gdehUqcWojXuNmj1Yqna1ZC2oYqCAbM1BA7FRRYjBiDiJIzZNS3ucMYL1vt3d3b5hBNZ9rk8C_sZLKqMGMqIYYV6X7gGa77QvgheQQetBJmOVkuGRIh-U0DOOxKO9cxqklWecYV_9-N3P6MZENfT0bWjT6NnM9pKYxTpdqU0-pqgsP6-jtUDBZqdJLUeVJqJmMEun6nHj1vTHjitzRX7gcL9YviCtwHhdFzAVVTPPf83uQ-_QWT-ETQf17_g9i2-8S13Sie1edRAYUlSB19nc4VRwaVSLx0BGvva9dUdnDVMPTR99iAuGSyZFDZ5hM6nmuv4kKNGZt3IttQfNTvPX0abqdCyNMkkw7JK9lznD-4H_L3VUehHsYNJs7jDnwlk4xYjVyS-dBetJ41Yx1H97bKGayfnrthcHYdwWYMbAVEAY7r_n66FARwwG-2FXaZcKOCVQuyhUeSPa7u2ixyw1k_FgP7AO5EobfRKfccJkaIpzWSu5G6cbVJTKugZhjdAG5dVu60W3M4DCxH2w_R7ginvmCiqZuDXgxjxB-NMxDi4AUhybRXIX3cyLrlQnh-E0PuswBj75Gmz5w60Ub2J9QeXGR71zxnJIYtL4cGhtRYka5Rx55F.sNtcCQvXmJl5rownRgNdVg
```

I was able to replicate the error by using the sample app (SDK v2.8 for Android).

**Comment by pmolensky** [comment]
_got a response from support by email; will keep this thread updated for others who might face the same issue_

Support suggested it might be related to the clients IdP-server being unreachable. But we're using the implicit flow, not the code flow. In the implicit flow, the authentication assertion is coming from the user, not the IdP-server. Or are we missing something here in the flow?

> **Implicit Flow**: In this flow, LivePerson Service does not get the authentication assertion directly from the customer server, but through the user. The assertion is signed by the customer Authorization Service, and optionally encrypted using the LivePerson Service key.
_Source: https://developers.liveperson.com/guides-authentication-introduction.html_

**Comment by Hauuguu** [comment]
Assuming we're talking about SDK 2.8, are you using setAuthKey or setHostAppJWT when calling showConversation?

I had the same issue and the end result that worked for me was something like this:
```java
LivePerson.showConversation(
    getCurrentActivity(), 
    new LPAuthenticationParams().setHostAppJWT(jwt), 
    new ConversationViewParams(false)
);
```

Hope this helps!

**Comment by pmolensky** [comment]
Cause for the error was found. As it turns out, there was a miscalculation in the token and set the expiration date in the past. Immediately failing the check by LiveEngage.

One remaining question, why does LiveEngage tries to retrieve a new token from the clients IdP-server in the implicit flow? Shouldn't it redirect the request to the app or return an error for the app to handle and re-issue a new (valid) token?

**Comment by orenkatz** [comment]
Hey @pmolensky 
You are right, in implicit mode, LivePerson is not checking against the client IDP, we just validate the token with the certificate.

**Comment by orenkatz** [comment]
@pmolensky Do you still experiencing any connection issues?

**Comment by pmolensky** [comment]
**ignore previous comment**
@Hauuguu's comment contains two changes:
1. `ConversationViewParams(isReadOnly())` > `ConversationViewParams(false)`
1. `setAuthKey(authCode)` > `setHostAppJWT(jwt)`
second change solved the error in the sample app.

Will ask the client to confirm their code.
