### ISSUE TITLE
String Localization android

### ISSUE THREAD

**Issue by krokozyabr-blr** [LivePersonInc/developers-community#67]
When trying to override strings according [guide](https://developers.liveperson.com/android-modifying-string.html) string on UI not changed

**Comment by dvillacis94** [comment]
Hi,

Can you please share, which version if the SDK are you using?,
as well as compileSdkVersion, minSdkVersion, and targetSdkVersion.

Thanks

**Comment by dvillacis94** [comment]
Hi @krokozyabr-blr,

To override strings, you'll need to add under your res folder, a new folder named "values-en" if the resource you're trying to add is in English, or the 2 digit ISO Code for the language you're trying to override, under that folder just create a strings.xml file, and just add the strings you want to override,

We'll update the documentation to match this.

**Comment by dvillacis94** [comment]
Hi @krokozyabr-blr,

Can you let us know if this solved the issue?

if not to keep the case open, and look for a solution.

**Comment by dvillacis94** [comment]
@krokozyabr-blr I'm closing the case, thanks for reporting this.
