### ISSUE TITLE
Watson connector example

### ISSUE THREAD

**Issue by naveedhan** [LivePersonInc/developers-community#68]
As you are patterning with Watson it will be nice to have an example for Watson bot connector

**Comment by donmanguno** [comment]
Thanks for the suggestion. We are aware of this gap and plan to add some examples for this use case in the future.

**Comment by donmanguno** [comment]
Hi @naveedhan.

LivePerson Watson integration actually doesn't require any code.  The configuration is done within the LiveEngage UI and the Watson website (as well as some behind the scenes configuration done by your LivePerson account team).

This document details the process: https://s3-eu-west-1.amazonaws.com/ce-sr/CA/Watson/Watson_configuration_guide.pdf

**Comment by naveedhan** [comment]
The document does not have any screen shots or details how to "Setup the connector" via live person interface. It simply states on page 10 that "our LivePerson team will support you with all of the backend configuration for your Watson connector. During this process, they will consult with you to ensure Watson is setup to reflect the brand image and consumer experience you want to deliver"

I have already asked the support team but they say they can't help even though we have subscribed and paid for bot integration. They say you need to do this with live person api's and there is no documentation avialable how to connect to watson via live person api's.

**Comment by donmanguno** [comment]
Hi @naveedhan 

Please email me at mmanguno@liveperson.com with your account number and we'll continue this discussion there.
