### ISSUE TITLE
[Users API] Update Users vs Update User (no difference noted?)

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#69]
https://developers.liveperson.com/administration-update-users.html
https://developers.liveperson.com/administration-update-user.html

There is no difference noted between the request bodies in this documentation. It would stand to reason that the Update User**S** method would allow for an array of agent IDs in the request body and not just a single agent ID. 

Note that none of the other plural vs singular methods note any differences either.

**Comment by orenkatz** [comment]
@EdenKupe can you please check the documentation?

**Comment by EdenKupe** [comment]
Hey, 

Seems like there's a difference in the method being used. For the Update User method, there's an extra expression in the URL:

``
/api/account/{accountId}/configuration/le-users/users/**{userId}**
``

This does not appear in the Update User**s** method.

**Comment by WildYorkies** [comment]
@EdenKupe The Request Body documentation shows that UserID parameter, though. I guess you should take that param out for the UserS method docs.

In any case, the documentation for this is too bare bones. It doesn't mention at all what payload you are sending for the update of users. For example, you have to send a json structure that has *at least* the user ID of the users you want to update and then the given changes you are making. What happens if you only include some properties and not all of them in the payload?

**Comment by EdenKupe** [comment]
Yeah, I agree that this document is lacking. That also causes the issue raised here (the problem is that both methods point to the same example, which is generic and too broad).

I'll link up with the VAULT team who are in charge of these APIs and try to get them to improve it.
