### ISSUE TITLE
CB getHoursType Function description needs a little work

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/developers-community#699]
https://developers.liveperson.com/conversation-builder-scripting-functions-get-set-contextual-data.html#get-type-of-hours

We had a customer try to implement this and it wasn't clear what was mandatory and what isn't. The  example code has the below hoursSpec:
`var hoursSpec = [
    "REG_HOURS~8:00~20:00",
    "AFTER_HOURS~20:00~8:00",
    "FRIDAY|WKEND_REG_HOURS~8:00~17:00",
    "FRIDAY|WKEND_AFTER_HOURS~17:00~08:00",
    "SATURDAY|WKEND_REG_HOURS~8:00~17:00",
    "SATURDAY|WKEND_AFTER_HOURS~17:00~08:00",
    "SUNDAY|WKEND_REG_HOURS~8:00~17:00",
    "SUNDAY|WKEND_AFTER_HOURS~17:00~08:00",
    "11.22.2018|HOLIDAY_THANKS~0:00~23:59",
    "12.25.2018|HOLIDAY_XMAS~0:00~23:59"
]`

**The Ask:**
The description doesn't say that the key `REG_HOURS`, `AFTER_HOURS` etc are completely arbitrary and can be whatever you want. CB doesn't automatically know that `WKEND_REG_HOURS` is Saturday or Sunday, it is mandatory to add `SATURDAY` and `SUNDAY` for CB to understand it is weekend. 

The only thing that is important is the time frames after the tilda. If there are two time frames that overlap, the latter is the time that takes affect.

**Comment by mferreira-lp** [comment]
@lp-tattwell Thank you for this feedback. I've logged internal ticket BA-4877 to track the update based on this find.

**Comment by mferreira-lp** [comment]
This section has been updated in consult with the SME team. https://developers.liveperson.com/conversation-builder-scripting-functions-get-set-contextual-data.html#get-type-of-hours
