### ISSUE TITLE
Allow filters for return

### ISSUE THREAD

**Issue by stevenwarejones** [LivePersonInc/developers-community#700]
Can you support contentToRetrieve on this api:
https://{domain}/messaging_history/api/account/{accountID}/conversations/conversation/search

We'd like to have it for audit and legal reasons.

Looking here at documentation:
https://developers.liveperson.com/messaging-interactions-api-methods-get-conversations-by-consumer-id.html

**Comment by j9t** [comment]
Hi @stevenwarejones—thanks for the extreme patience here…! We’re going through all open issues, working to ensure (much faster) responses; please let us know if this is still relevant.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)
