### ISSUE TITLE
Documentation issue - iOS json for push notification

### ISSUE THREAD

**Issue by roblumley** [LivePersonInc/developers-community#71]
I received an email from State Farm's dev team.  Is this something we are updating in the documentation?  Thanks!  

Rob Lumley
CSM - State Farm

"Morning, now that we got our testing back on line we discovered a new issue.   There appears to be two new values in the IOS json for Push Notification.   These are not documented in the online guide.
Push Notification Guide
https://developers.liveperson.com/push-service-overview.html
 
What we found
 
Recent Payload. (Today)
{
        "aps" : {
                "alert" : "Cyndi: How can I help you",
                "sound" : "default"
        },
        "push-service" : 1,
        "device-token" : "425450383030444630304d7c30337c3034",
        "backendService" : "ams",
        "conversationId" : "f02ef106-89b7-406c-8613-11dfac8559ec",
        "originatorId" : "8917914.59224514",
        "brandId" : "8917914",
        "badge" : 1,
        "sequence" : 3,
        "notificationType" : "apn"
}
 
 
When we started development, we had this payload.
{
        "aps" : {
                "alert" : "My Test: 123\\n",
                "sound" : "default"
        },
        "push-service" : 1,
        "device-token" : "425031544d3353333030317c337c34",
        "backendService" : "ams",
        "conversationId" : "13a1ca79-22eb-4a60-8cad-cd7f9dbdb9f3",
        "originatorId" : "qa90588718.2333061110",
        "brandId" : "qa90588711",
        "notificationType" : "apn"
}

**Comment by dvillacis94** [comment]
Hi @roblumley,

Apple has been adding more information into the JSON payload for the Push Notifications, that is something we can't control, we'll add this to the documentation, also is important to mention that those changes are only available on new releases of iOS.

**Comment by donmanguno** [comment]
As there has been no response for 8 days I am closing this issue now. The documentation will be updated to convey what David explained.
