### ISSUE TITLE
[Android] brand_name not displayed in app

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#72]
When the string "brand_name" is set in the strings.xml-file, the value is not displayed in the app.
For comparison, I also set the app_name in the strings.xml-file, which is displayed.

Build: sample app
OS: Android
Version: SDK v2.8.0

I've created an animated gif of my build and deployment in Android Studio to a virtual device.
![https://prnt.sc/h6yohr](https://image.prntscr.com/image/3v3_M7leR4KSXapzBxjFcw.gif)

I've triple checked the [documentation](https://developers.liveperson.com/android-modifying-string.html).
What did I do wrong?

**Comment by dvillacis94** [comment]
Hi @pmolensky,

To override strings, you'll need to add under your res folder, a new folder named "values-en" if the resource you're trying to add is in English, or the 2 digit ISO Code for the language you're trying to override, under that folder just create a strings.xml file, and just add the strings you want to override,

**Comment by pmolensky** [comment]
@dvillacis94 you're right. I'll go home and be ashamed :man_facepalming:

**Comment by WildYorkies** [comment]
>To override strings, you'll need to add under your res folder, a new folder named "values-en" if the resource you're trying to add is in English, or the 2 digit ISO Code for the language you're trying to override, under that folder just create a strings.xml file, and just add the strings you want to override,

@dvillacis94 When is your advice getting added to this page? https://developers.liveperson.com/android-modifying-string.html
