### ISSUE TITLE
[Android] Agent name display in conversation view

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#74]
When does the top text of the conversation view change to the agent name? 

And what should we do if we can't get the agent name to display properly? Is there a common fix for that?

![2017-11-08 11_04_58-in-app messaging sdk for android - attributes design sheet _ liveperson apis](https://user-images.githubusercontent.com/1299322/32559336-eed6f658-c474-11e7-9a4b-83d03ef03953.png)
![2017-11-08 11_05_18-in-app messaging sdk for android - attributes design sheet _ liveperson apis](https://user-images.githubusercontent.com/1299322/32559341-f0f1e57e-c474-11e7-9268-eecebf04f536.png)

**Comment by Hauuguu** [comment]
The brand name changes to the agent name once connected/assigned to an agent. In the interim you can set the brand name with the brand_name string resource under res/values/strings.xml.

I.e.
```xml
<resources>
	...
	<string name="brand_name">Brand Name Here</string>
    ...
</resources>
```

**Comment by orenkatz** [comment]
@WildYorkies Did @Hauuguu helped with your question?
