### ISSUE TITLE
CSDS domain attribute missing from the documentation

### ISSUE THREAD

**Issue by amirmLP** [LivePersonInc/developers-community#742]
Clients who use the Vanity URL feature need to override the default CSDS domain.
The Android document (https://developers.liveperson.com/mobile-app-messaging-sdk-for-android-sdk-attributes-5-0-and-above.html#general-style) has it under csds_url

The iOS document does not even though the attribute does exist (csdsDomain).

Please add it to the documentation.

Thanks

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)

**Comment by amirmLP** [comment]
Hi @j9t this is fixed now. Thanks
