### ISSUE TITLE
Messaging Windows APIs - Conversation Metadata

### ISSUE THREAD

**Issue by marcodagolini** [LivePersonInc/developers-community#77]
Hello Team!

For what i read the answer body when we receive one event should be:
{"changes":[{"sequence":0,"originatorId":"","serverTimestamp":0,"event":{"type":"ContentEvent","contentType":"text/plain","message":""}

For what i know, the element "changes" does not exist.
The correct element name is "change".

Regards

Marco

**Comment by donmanguno** [comment]
Hi Marco,
Can you clarify the context you're referring to? According to my tests both MessagingEventNotifications and ExConversationChangeNotifications always contain an array called "changes" regardless of the number of changes included in that notification.  This appears to be the standard for all event notifications from the Messaging service, and I have confirmed that it is true in the Messaging Window API (see the following examples from [our codepen](https://codepen.io/liveperson/pen/xRzXXd?editors=0010)):
```
socket.onNotification(withType('MessagingEvent'),
    body => body.changes.forEach(change => {...
```
```
function handleConversationNotification(socket,notificationBody,openConvs) {
  notificationBody.changes.forEach(change => {...
```

**Comment by marcodagolini** [comment]
Hello Mark!

Don't mind, you're totally right!
I was mislead due the assignment "body.changes.forEach(change => ......"
Shame on me!

Marco
