### ISSUE TITLE
Looking for unminified JS Chat SDK

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#790]
Question from one of our clients, do we have a readable (unminified) version of the [Javascript Chat SDK](https://lpcdn.lpsnmedia.net/api/chat/public/lpChat.min.js)?
_Documentation: [Client Side Configuration > Javascript Chat SDK > Getting Started > Retrieve SDK](https://developers.liveperson.com/javascript-chat-sdk-overview.html#getting-started)_

**Comment by j9t** [comment]
Hi @pmolensky—thanks for the extreme patience here…! We’re going through all open issues, working to ensure (much faster) responses; please let us know if this is still relevant.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)
