### ISSUE TITLE
Push service for android app

### ISSUE THREAD

**Issue by lapto093** [LivePersonInc/developers-community#82]
Hi, 
We're implementing Live Person chat for Android app, we'll launch the app in China, just trying to make sure that your push services are working on that market.
Pls help to answer that question.

Thanks
Lap To

**Comment by donmanguno** [comment]
Hi Lap To,

We have not tested much with non-Google push services, so if you're planning to target devices without Google Play Services there might be an issue. Which push service(s) are you considering?

**Comment by donmanguno** [comment]
Hi @lapto093,

I have to close this issue now due to inactivity, but I can re-open it if you return to let us know which push service you would like to implement aside from FCM.
