### ISSUE TITLE
Login service API - refresh recommendation?

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#83]
Hi, the Login Service API has a refresh method. How often/when should this method be called?
I assume, this should be shorter (or equal) than the `sessionTTl` response value (milliseconds) of the User/Application Login method, correct?

**Comment by devin-liu** [comment]
The liveengage interface refreshes the login every 3 minutes-- that is a good baseline.

**Comment by EdenKupe** [comment]
Hey guys,

Consulted with RnD and three minutes does indeed make sense. I will update the documentation to include regarding this best practice.

Thanks!
