### ISSUE TITLE
How can i modify a strings?

### ISSUE THREAD

**Issue by nirav124u** [LivePersonInc/developers-community#84]
Hi ..

i want to change a first welcome message with my custom message.
Default message is  "How can i help you today ?"
i want to change this message to  "This is test message".

I reviewed a modifying strings article. Link https://developers.liveperson.com/android-modifying-string.html

i am overriding 'lp_first_message' string in my string.xml file with this value.
<string name="lp_first_message">This is test message..</string>

but still welcome message is not getting changed.

Could you pls. help me in how to change this message?

**Comment by pmolensky** [comment]
I had the same issue a few weeks ago:

> To override strings, you'll need to add under your res folder, a new folder named "values-en" if the resource you're trying to add is in English, or the 2 digit ISO Code for the language you're trying to override, under that folder just create a strings.xml file, and just add the strings you want to override,
[Thanks to David](72#issuecomment-342213523)

**Comment by orenkatz** [comment]
@nirav124u Did @pmolensky worked for you?

**Comment by donmanguno** [comment]
@nirav124u I'm going to close this case now due to lack of activity.
