### ISSUE TITLE
Messaging Interactions API - source values unclear

### ISSUE THREAD

**Issue by pmolensky** [LivePersonInc/developers-community#85]
_Requested to move PR #60 to issue by @EdenKupe_
The [Messaging Interactions API](https://developers.liveperson.com/data-messaging-interactions-conversations.html) mentions the following possible values as a source:
- APP
- WEB
- AGENT
- SMS
- FACEBOOK

I see a value `SHARK` for interactions started from the website. And no `WEB` values, or is there a difference between the two?

**Comment by EdenKupe** [comment]
Thanks, I'll get this over to the PM in charge of our Data APIs.

**Comment by EdenKupe** [comment]
Hey,

So, apparently the name for our WEB parameter is SHARK. They are one and the same. I've updated the documentation to reflect this, adding in SHARK (WEB) so that it's clearer. 

Closing the issue for now, feel free to reopen if anymore work is needed. Thanks!
