### ISSUE TITLE
sid in visit Information API

### ISSUE THREAD

**Issue by mkwong04** [LivePersonInc/developers-community#87]
I encounter "Unauthorized account access" error when using the visit Information API.

The application already have its api key granted access to "Real Time Interactions" of API

Below are sequences involve
1) obtain base uri via get Domain for "agentVep"
2) perform login using Login API 
3) start agent session
4) accept a chat request
5) get chat info to obtain visitorId
6) generate 0-legged OAuth1 header with api key/secret/accessToken/accessSecret and invoke get visit info API

Get https://va.v.liveperson.net/api/account/{accountId}/monitoring/visitors/{vistorId obtained in step 5}/visits/current/state?v=1&filter=agent&sid={rtSessionId from chat Info in step 5}

the response body is something like this
visit info : {"time":1512008639373,"message":"Unauthorized account access","internalCode":10}

Is there anyway to find out the cause? 

is the sid used correct? if not where and how can we obtain it?

**Comment by donmanguno** [comment]
Hi @mkwong04,

The Visit Information API uses a Visitor ID and Session ID that are not directly available in the LiveEngage UI. Rather, these can be obtained from within the visitor's browser, either from the parameters of the network calls being made to our monitoring service, or from the visitor's cookies.

For example, on our login page (authentication.liveperson.net) you are monitored by our Support account. The screenshot below shows the relevant cookies from my own visit: LPVID and LPSID-[your-acount-number]:
![image](https://user-images.githubusercontent.com/10452169/33439464-7df8b8e2-d5bb-11e7-8c43-efffc78a4c5a.png)

**Comment by devin-liu** [comment]
Hi Mark, the documentation is wrong. That API takes the information in this format:

    `https://va.v.liveperson.net/api/account/${accountId}/monitoring/visitors/${sharkVisitorId}/visits/current/state?NC=true&v=1&filter=agent&sid=${sharkSessionId}`

sharkVisitorId and sharkSessionId are also available from the chat info.

**Comment by mkwong04** [comment]
Thanks for the info, i tried with the sharkVisitorId and sharkSessionId, but still encounter the same error, anything i may have missed out?

There are a few possible points of error source i can think of, but i need a way to isolate them.
i) the access grant is not properly done (will double check with account admin)
ii) the oauth1 token generated (i am using org.scribe's scribe library to generate the 0-legged OAuth1, my co-worker is using that successfully with engagement history API, so unlikely be the culprit)
iii) the visit info API is used incorrectly since document is not that clear (based on devin-liu's comment doc may not be up to date)

The returned error (_e.g. {"time":1512116355885,"message":"Unauthorized account access","internalCode":10}_ ) is too general to figure out what may went wrong.

Is there any suggestion where i can look further to resolve the issue? Thanks in advance

**Comment by scottwestover** [comment]
@mkwong04 For your API keys, can you make sure that that the Visit Information / Engagement Attributes API is selected?

![2017-12-04_1057](https://user-images.githubusercontent.com/9931822/33561923-f759411a-d8e1-11e7-930d-6b201c77adff.png)

If it is selected, I would try creating a new set of API keys in the LiveEngage console.

I ran into the same issue where the visitor information was selected on one of my API keys sets, and I kept getting the same unauthorized error. 

However, I created a new set of API keys in the LiveEngage console, and then I was able to fetch the visitor information without any issues.

**Comment by mkwong04** [comment]
Thanks everyone for advises, updates on the issue.

It is working now. it is related to the API access grant setting, account manage help to double check and confirm the setting and issue resolve.

Also confirm that the API is using sharkVisitorId and sharkSessionId. Liveperson API document should be updated.
