### ISSUE TITLE
2.9.3.0.1367: Crash when setting configuration.checkmarkReadColor = UIColor.clear

### ISSUE THREAD

**Issue by rplankenhorn** [LivePersonInc/developers-community#90]
I get this crash when I am trying to configure checkmarkReadColor.  I am using the SDK within a React Native project and had no issues in prior versions with older versions of Xcode.  If I comment out the configuration line, I am able to move past this crash to another crash.

![live_person_crash_2](https://user-images.githubusercontent.com/228338/33446991-727f3f3e-d5c7-11e7-9094-9128d17ef80a.jpg)

**Comment by dvillacis94** [comment]
Hi,

Which version of the CocoaPod are you using? (2.X.X.X)

**Comment by rplankenhorn** [comment]
Any update on this?

**Comment by dvillacis94** [comment]
We're working on replicating this, are you making the configurations via Xcode or React-Native?

**Comment by rplankenhorn** [comment]
I have confirmed that this issue is present in all of the following versions:
- 2.9.0.11.1329
- 2.9.1.1.1344
- 2.9.2.0.1352
- 2.9.3.0.1367

But there are no issues with 2.8.4.5.1297-xcode91.  Is this a supported version?

**Comment by rplankenhorn** [comment]
@dvillacis94 The configuration is done via Native iOS code.

**Comment by dvillacis94** [comment]
So you're only calling the init and showConversation through a Bridge? or are you do something on React-Native with the SDK?

**Comment by rplankenhorn** [comment]
We have a view that we expose to React and inside that view we have a controller that we add as a child controller.  That controller makes all the calls to the SDK.  We are only making the calls to get the authorCode from within React.

**Comment by donmanguno** [comment]
Closing issue. This works in pod '2.8.4.5.1297-xcode91' and React is not currently officially supported in the 2.9.x versions.

**Comment by rplankenhorn** [comment]
This issue is no longer happening in 3.0.0.
