### ISSUE TITLE
Releases on Github don't match the Podspec file

### ISSUE THREAD

**Issue by rplankenhorn** [LivePersonInc/developers-community#92]
The SDK release version number should match the same version that is in the Podspec file per Cocoapods community convention.  Currently, the versions listed on the SDK Github site are like this:  2.9.2, 2.9.3, etc but the Podspec file has them listed like this:  2.9.3.0.1367.

**Comment by orenkatz** [comment]
@rplankenhorn is it blocking you from using it for any reason?

**Comment by rplankenhorn** [comment]
No.  I just have to go into the pod spec repo and look at the newest folder to get the latest version.  For other Cocoapods projects, the version in the Podspec matches the version on the repo.  Take a look at [AlamoFire release](https://github.com/Alamofire/Alamofire/releases) and [AlamoFire pod spec](https://github.com/CocoaPods/Specs/tree/master/Specs/d/a/2/Alamofire).  Notice how the folder names match up with the releases on the main repo.  Having the versions consistent means that when you are updating the Podfile, you only have to go to the main repo to see what the latest version is.

**Comment by donmanguno** [comment]
Hi @rplankenhorn,

Since we only publicly release one version of each release (as in MAJOR.MINOR.RELEASE) you can target the entire release in your podfile as such:

`pod 'LPMessagingSDK', '~>2.5.3.0'`

This will ensure that you get the highest version of 2.5.3.x, and there will be only one.

**Comment by rplankenhorn** [comment]
I tried that and it doesn't work.  Since the version doesn't match exactly, it doesn't pull the latest version.

**Comment by shaymLP** [comment]
@rplankenhorn, Using 'pod update' will get you the latest SDK version automatically.

**Comment by orenkatz** [comment]
@rplankenhorn as @donmanguno mentioned, below is the logic for pod files:
'> 0.1' Any version higher than 0.1
'>= 0.1' Version 0.1 and any higher version
'< 0.1' Any version lower than 0.1
'<= 0.1' Version 0.1 and any lower version
In addition to the logic operators CocoaPods has an optimistic operator ~>:

'~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
'~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
'~> 0' Version 0 and higher, this is basically the same as not having it.

Taken from here - https://guides.cocoapods.org/using/the-podfile.html

**Comment by donmanguno** [comment]
Closing this issue as resolved.
