### ISSUE TITLE
"-Dev" or "-DEV" for app name string?

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#93]
https://developers.liveperson.com/push-service-configuration.html This doc has "-Dev"

https://developers.liveperson.com/consumer-experience-ios-sdk-pushnotifications.html#configuring-push-notifications This doc has "-DEV"

Does this difference matter?

**Comment by dvillacis94** [comment]
It needs to be -Dev, the service is case sensitive. Where are working on unifying the documentation regarding this matter.

**Comment by EdenKupe** [comment]
Hey,

I've fixed this specific instance of this mistake. @dvillacis94 , let me know if you guys find any more issues as you work to unify the documents around this specific issue.

Thanks!

**Comment by donmanguno** [comment]
I'm closing this issue @WildYorkies
