### ISSUE TITLE
Required vs Optional Body Parameters For Server Chat API

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#95]
The documentation for the Server Chat API does not list what parameters are required vs what parameters are optional for each of the methods. 

![2017-12-06_1403](https://user-images.githubusercontent.com/9931822/33680014-508b2868-da8e-11e7-96c1-60b61cf99b00.png)

Example page: https://developers.liveperson.com/consumer-experience-server-chat-start-chat.html

This makes it very hard to query the API. Can this please be updated?

**Comment by EdenKupe** [comment]
Hey Scott,

We're aware of these issues. However, Udi Dagan who should take care of it is currently at capacity. Could you please report this issue to Support so that they can open a bug and assign it to DevSupport? They can then see how/when they can get this resolved.

Thanks!

**Comment by scottwestover** [comment]
@EdenKupe Thanks for the quick response. I will do that.
