### ISSUE TITLE
sending message directly to chat -- bypassing the agent input with agentSDK

### ISSUE THREAD

**Issue by bsotiroff** [LivePersonInc/developers-community#957]
Is it possible to use the agentSDK to send chats directly from the 3rd party widget to the conversation, without having to send them through the agent's input?

I am currently implementing "Write ChatLine" in order to send responses from the widget directly to the agent's input. I would like to bypass the input altogether and send it directly to the chat with a mouse click.

It looks like both lpTag.agentSDK.cmdNames.write and writeSC both support the use of quickReplies, however this just provides the visitor to reply to the agent's message easier. In the code example 2 'Write ChatLine' with Quick Replies, there is a quickReply "action" called publishText. I'm wondering if this could be used some how to get the direct-to-chat behavior that I would like?
```javascript
      quickReplies: {
        "type": "quickReplies",
        "itemsPerRow": 8,
        "replies": [
          {
            "type": "button",
            "tooltip": "yes i do",
            "title": "yes",
            "click": {
              "actions": [
                {
                  "type": "publishText",
                  "text": "yep"
                }
              ],
...
```

**Comment by j9t** [comment]
Hi @bsotiroff—thanks for the extreme patience. Is this still relevant?

**Comment by j9t** [comment]
(Closing this one in recognition that this was in need of a response a long time ago. We can reopen as soon as we have confirmation this persists.)
