### ISSUE TITLE
Body parameters for Server Chat API - Start Chat Method are unclear

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#96]
The Body parameters that are listed for the Start Chat method of the Server Chat API, do not align with the parameters that are used in the Request Body Example.

The example Request Body uses the following parameters: LETagVisitorId, LETagSessionId, and LETagContextId, however, none of these are listed in the Body parameters table that is above it.

Here is the example request body that is shown:
```
{"request":{"skill":"Sales","interactionTimeout":40,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36","LETagVisitorId":"rloXnVgEQ-iQuoOytvKNqA","LETagSessionId":"rN82d4rATN6EuiA4cJwaPg","LETagContextId":"2","engagementId":27469613,"campaignId":26948813,"language":"en-US"}}
```

Also, the table mentions using a 'visitorId' parameter, but when I replace the 'LETagVisitorId', the API returns a 401 Unauthorized status with the following error message:
```
{
    "error": {
        "time": "2017-12-06T14:09:08.703-05:00",
        "message": "Invalid User",
        "internalCode": 10
    }
}
```

Documentation URL: https://developers.liveperson.com/consumer-experience-server-chat-start-chat.html

Can this please be updated?

**Comment by EdenKupe** [comment]
Same as Issue #95
