### ISSUE TITLE
Issue calling Start Chat method of Server Chat API

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/developers-community#97]
I am trying to call the start chat method of the Server Chat API in Postman, but I keep getting a 401 Unauthorized status, and the following error message:
```
{
    "error": {
        "time": "2017-12-06T16:29:45.438-05:00",
        "message": "Bad captcha",
        "internalCode": 10
    }
}
```

I looked through the documentation, but could not find a list of error codes for this API call, and I could not find any reference to captcha being used in this API.

https://developers.liveperson.com/consumer-experience-server-chat-start-chat.html

For reference, here is the URL I was using: 
```
https://va-e.convep.liveperson.net/api/account/28561192/chat/request.json?v=1&appKey=721c180b09eb463d9f3191c41762bb68
```

and here is the Body that I used:
```
{
	"request": {
		"LETagVisitorId": "NmZWYzNmNhNmY0ZDY2NzMy",
		"LETagSessionId": "wTCjUJEVT9WZmFqdpXwWrg",
		"LETagContextId": "1",
		"engagementId": "327510414",
		"campaignId": "264712514",
		"skillId": -1
	}
}
```

Is there something else that I need to pass?

**Comment by EdenKupe** [comment]
Same as Issue #95

**Comment by scottwestover** [comment]
The issue was tied to an account config setting that was enabled on the account. Once the "Common.Unified_window_captcha" feature was turned off, the API worked correctly.
