### ISSUE TITLE
[JS Chat API] Closing a chat that got an error request (because the agent/skill went offline) before starting a new one

### ISSUE THREAD

**Issue by WildYorkies** [LivePersonInc/developers-community#99]
I am trying to follow the engineering recommendations about closing a chat that got an error request (because the agent/skill went offline) before starting a new one. Here is the situation:
 
- I changed our code so when we restart a chat, we call .endChat() on our previous chat (this chat got an error response from LivePerson)
- I save this .endChat() call and throw an alert if it brings and error (this to be able to show it in the video)
- An alert get’s printed saying that the chat couldn’t be ended. My theory here is that since I didn’t properly start a chat, I’m also not able to end it because there’s no reference of that chat in Liveperson’s servers. Please let me know if this assumption is right. If I’m wrong in this, the the .endChat() call is not being called correctly or it’s not returning what we expect.
 
I tried to use other methods that look available in the JS SDK object **but have no documentation**, except for the last one. The methods are .unbind(), .clearSessionData() and .disposeVisitor(). They seem to work on the objective of ending the previous chat session, but we are not sure if these are suitable options to do this.
 
![image](https://user-images.githubusercontent.com/1299322/33953497-21c8e6b2-e003-11e7-85ed-b9e9c0f5bb56.png)
 
To  summarize:
 
- Can we call .endChat() on a chat object that hasn’t been properly started (no functioning chat). This is related to the video.
- If we can’t, how do we go about “restarting” the chat with new data (going for a skill instead of an agent) and ending the previous request.
- Can we use .unbind(), .clearSessionData() and .disposeVisitor for clearing the previous chat sessions?

**Comment by orenkatz** [comment]
Hey @WildYorkies 
@donmanguno already started to work on it offline and will sync with you outside Github.
Closing this issue here.
